---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords: Requirements 
summary: SnapCenter Plug-in for Microsoft SQL ServerのバックアップからSQL Serverデータベースをリストアする前に、以下の要件を満たしていることを確認する必要があります。 
---
= データベースをリストアする際の要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft SQL ServerのバックアップからSQL Serverデータベースをリストアする前に、以下の要件を満たしていることを確認する必要があります。

* ターゲットSQL Serverインスタンスがオンラインで、稼働している必要があります。
+
これは、ユーザ データベースのリストア処理とシステム データベースのリストア処理の両方に当てはまります。

* リモート管理サーバまたはリモート検証サーバ上でスケジュールされているジョブも含め、リストアするSQL Serverデータに対して実行予定のSnapCenter処理をすべて無効にしておく必要があります。
* システム データベースが機能していない場合は、最初にSQL Serverユーティリティを使用してシステム データベースを再構築しておく必要があります。
* プラグインをインストールするときに、可用性グループ（AG）のバックアップをリストアする権限を他のロールに付与します。
+
次のいずれかの条件に該当する場合、AGのリストアが失敗します。

+
** RBACユーザがプラグインをインストールし、管理者がAGバックアップをリストアしようとした場合
** 管理者がプラグインをインストールし、RBACユーザがAGバックアップをリストアしようとした場合


* カスタム ログ ディレクトリのバックアップを代替ホストにリストアする場合は、SnapCenter Serverとプラグイン ホストに同じバージョンのSnapCenterがインストールされている必要があります。
* Microsoftの更新プログラムKB2887595をインストールしておく必要があります。KB2887595の詳細については、Microsoftのサポート サイトを参照してください。
+
https://support.microsoft.com/kb/2887595["Microsoft サポート記事 2887595: Windows RT 8.1、Windows 8.1、および Windows Server 2012 R2 更新プログラムのロールアップ: 2013 年 11 月"]

* リソース グループまたはデータベースをバックアップしておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートするユーザには、SnapCenter管理者がユーザに対してソースとデスティネーションの両方のボリューム用にStorage Virtual Machine（SVM）を割り当てておく必要があります。
+
管理者によるユーザへのリソースの割り当てについては、SnapCenterのインストール情報を参照してください。

* データベースをリストアする前に、すべてのバックアップ ジョブとクローン ジョブを停止しておく必要があります。
* データベースのサイズがテラバイト（TB）単位の場合、リストア処理がタイムアウトになることがあります。
+
次のコマンドを実行して、 SnapCenter Server の RESTTimeout パラメータの値を 20000000 ミリ秒に増やす必要があります: Set-SmConfigSettings -Agent -configSettings @{"RESTTimeout" = "20000000"}。タイムアウト値は、データベースのサイズに応じて変更できます。設定可能な最大値は、86,400,000ミリ秒です。



データベースがオンライン状態のときにリストアする場合は、[Restore]ページでオンライン リストア オプションを有効にする必要があります。
