---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: 'SnapCenterを使用して SQL Server システムおよびユーザー データベースをバックアップするには、データベース、SQL Server インスタンス、可用性グループ (AG) などのリソース タイプを選択する必要があります。Snapshotテクノロジを通じて、リソースが配置されているボリュームのオンラインの読み取り専用コピーが作成されます。' 
---
= サポートされるバックアップのタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してSQL Serverのシステム データベースとユーザ データベースをバックアップするには、リソース タイプ（データベース、SQL Serverインスタンス、可用性グループ[AG]など）を選択する必要があります。Snapshotテクノロジを通じて、リソースが配置されているボリュームのオンラインの読み取り専用コピーが作成されます。

コピーのみのオプションを選択して、SQL Serverがトランザクション ログを切り捨てないように指定できます。SQL Serverの管理に他のバックアップ アプリケーションも使用している場合は、このオプションを指定する必要があります。トランザクション ログが変更されずに保持されるため、任意のバックアップ アプリケーションでデータベースをリストアできます。コピーのみのバックアップは、スケジュールされたバックアップとは関係なく実行され、またデータベースのバックアップおよびリストア手順には影響しません。

|===
| バックアップ タイプ | 説明 | コピーのみのオプションを選択した場合 


 a| 
フル バックアップとログ バックアップ
 a| 
システム データベースがバックアップされ、トランザクション ログが切り捨てられます。

SQL Serverは、データベースにコミット済みのエントリを削除することによってトランザクション ログを切り捨てます。

このオプションを選択すると、フル バックアップの完了後にトランザクション ログが作成されてトランザクション情報がキャプチャされます。通常はこのオプションを選択します。ただし、バックアップ時間が短い場合は、フル バックアップでトランザクション ログ バックアップを実行しないように選択することもできます。

masterシステム データベースとmsdbシステム データベースについては、ログ バックアップを作成できません。modelシステム データベースのログ バックアップは作成できます。
 a| 
システム データベース ファイルとトランザクション ログがバックアップされ、ログは切り捨てられません。

コピーのみのバックアップは差分ベースまたは差分バックアップとしては使用できず、差分ベースには影響しません。コピーのみのフル バックアップのリストアは、通常のフル バックアップのリストアと同じです。



 a| 
フル データベース バックアップ
 a| 
システム データベース ファイルがバックアップされます。

master、model、msdbの各システム データベースのフル データベース バックアップを作成できます。
 a| 
システム データベース ファイルがバックアップされます。



 a| 
トランザクション ログ バックアップ
 a| 
切り捨てられたトランザクション ログがバックアップされ、最新のトランザクション ログのバックアップ後にコミットされたトランザクションのみがコピーされます。

フル データベース バックアップに加えてトランザクション ログを頻繁にバックアップするスケジュールを設定すると、リカバリ ポイントをより細かく選択できます。
 a| 
トランザクション ログが切り捨てられずにバックアップされます。

このバックアップ タイプは、定期的なログ バックアップには影響しません。コピーのみのログ バックアップは、オンラインのリストア処理を実行する場合に便利です。

|===