---
permalink: protect-scsql/concept_what_you_can_do_with_the_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: SnapCenter Plug-in for Microsoft SQL Serverをインストールした環境では、SnapCenterを使用してSQL Serverデータベースをバックアップ、リストア、クローニングすることができます。 
---
= SnapCenter Plug-in for Microsoft SQL Serverの機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft SQL Serverをインストールした環境では、SnapCenterを使用してSQL Serverデータベースをバックアップ、リストア、クローニングすることができます。

SQL Serverデータベースとデータベース リソースのバックアップ処理、リストア処理、クローニング処理をサポートする、次のタスクを実行できます。

* SQL Serverデータベースと関連するトランザクション ログをバックアップする
+
masterシステム データベースとmsdbシステム データベースについては、ログ バックアップを作成できません。modelシステム データベースのログ バックアップは作成できます。

* データベース リソースをリストアする
+
** マスター システム データベース、msdbシステム データベース、モデル システム データベースをリストアできます。
** 複数のデータベース、インスタンス、可用性グループのリストアはできません。
** システム データベースは、別のパスにはリストアできません。


* 本番環境のデータベースのポイントインタイム クローンを作成する
+
tempdbシステム データベースに対して、バックアップ、リストア、クローニング、クローン ライフサイクルの各処理は実行できません。

* バックアップ処理をただちに検証するか、あとで検証する
+
SQL Serverシステム データベースの検証はサポートされていません。SnapCenterは、検証処理を実行するためにデータベースをクローニングします。SnapCenterは、SQL Serverシステム データベースをクローニングできません。そのため、これらのデータベースの検証はサポートされていません。

* バックアップ処理とクローニング処理のスケジュールを設定する
* バックアップ処理、リストア処理、クローニング処理を監視する



NOTE: Plug-in for SQL Serverでは、SMB共有のSQL Serverデータベースのバックアップとリカバリはサポートされません。
