---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords: migrate resources 
summary: 'SnapCenter Plug-in for Microsoft Windows を使用してNetAppストレージ システムをプロビジョニングした後、 SnapCenterグラフィカル ユーザー インターフェイス (GUI) または PowerShell コマンドレットを使用して、リソースをNetAppストレージ システムに移行したり、あるNetApp LUN から別のNetApp LUN に移行したりできます。' 
---
= NetAppストレージ システムへのリソースの移行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft Windowsを使用してNetAppストレージ システムをプロビジョニングしたら、SnapCenterグラフィカル ユーザ インターフェイス（GUI）またはPowerShellコマンドレットを使用して、リソースをNetAppストレージ システムに移行するか、またはあるNetApp LUNから別のNetApp LUNに移行できます。

.開始する前に
* SnapCenter Serverにストレージ システムを追加しておく必要があります。
* SQL Serverリソースを更新（検出）しておく必要があります。


ウィザードの各ページのフィールドのほとんどはわかりやすいもので、説明を必要としません。以下の手順では、説明が必要な一部のフィールドを取り上げます。

.手順
. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. [リソース] ページで、[表示] ドロップダウン リストから [データベース] または [インスタンス] を選択します。
. リストからデータベースまたはインスタンスのいずれかを選択し、「移行」をクリックします。
. [Resources]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
*データベース名* (オプション)
 a| 
移行対象としてインスタンスを選択した場合は、[*データベース*] ドロップダウン リストからそのインスタンスのデータベースを選択する必要があります。



 a| 
*目的地を選択*
 a| 
データ ファイルとログ ファイルの移行先を選択します。

データ ファイルとログ ファイルは、選択したNetAppドライブの下のDataフォルダとLogフォルダにそれぞれ移動されます。フォルダ構造にフォルダがない場合は、フォルダが作成されたうえでリソースが移行されます。



 a| 
*データベースファイルの詳細を表示* (オプション)
 a| 
このオプションは、1つのデータベースの複数のファイルを移行する場合に選択します。


NOTE: *インスタンス* リソースを選択した場合、このオプションは表示されません。



 a| 
*オプション*
 a| 
ソースからデータベースのコピーを削除するには、「*元の場所にある移行されたデータベースのコピーを削除*」を選択します。

オプション: *データベースをデタッチする前に、テーブルに対して UPDATE STATISTICS を実行します*。

|===
. [Verify]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
*データベース整合性チェックオプション*
 a| 
移行前にデータベースの整合性を確認するには、「事前に実行」を選択します。移行後にデータベースの整合性をチェックするには、「実行後」を選択します。



 a| 
*DBCC CHECKDB オプション*
 a| 
** 整合性チェックをデータベースの物理構造に制限し、破損したページ、チェックサム障害、およびデータベースに影響する一般的なハードウェア障害を検出するには、*PHYSICAL_ONLY* オプションを選択します。
** すべての情報メッセージを抑制するには、*NO_INFOMSGS* オプションを選択します。
** オブジェクトごとに報告されたすべてのエラーを表示するには、*ALL_ERRORMSGS* オプションを選択します。
** 非クラスター化インデックスをチェックしない場合は、*NOINDEX* オプションを選択します。
+
SQL Serverデータベースは、Microsoft SQL ServerのDatabase Consistency Checker（DBCC）を使用して、データベース内のオブジェクトの論理的な整合性と物理的な整合性をチェックします。

+

NOTE: このオプションを選択すると、実行時間を短縮できます。

** 内部データベース スナップショットを使用する代わりに、チェックを制限してロックを取得するには、**TABLOCK** オプションを選択します。


|===
. 概要を確認し、[**完了**] をクリックします。

