---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords: clone strategy 
summary: クローニング戦略を定義しておくと、それに従ってデータベースのクローニングを実行することができます。 
---
= SQL Serverのクローニング戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローニング戦略を定義しておくと、それに従ってデータベースのクローニングを実行することができます。

. クローニング処理に関連する制限事項を確認します。
. 必要なクローンのタイプを決定します。




== クローニング処理の制限事項

データベースをクローニングする前に、クローニング処理の制限事項を確認しておく必要があります。

* Oracle の 11.2.0.4 から 12.1.0.1 までのバージョンを使用している場合、_renamedg_ コマンドを実行するとクローン操作がハング状態になります。この問題を修正するには、Oracleパッチ19544733を適用します。
* （WindowsホストでMicrosoft iSCSIイニシエータを使用するなどして）ホストに直接接続されているLUNから、同じWindowsホスト上のVMDKかRDM LUN、または別のWindowsホストにデータベースをクローニングすることはできません。その逆も同様です。
* ボリューム マウント ポイントのルート ディレクトリを共有ディレクトリにすることはできません。
* クローンを含むLUNを新しいボリュームに移動すると、そのクローンは削除できなくなります。




== クローニング処理のタイプ

SnapCenterを使用して、SQL Serverデータベースのバックアップまたは本番環境のデータベースをクローニングすることができます。

* データベース バックアップからのクローニング
+
クローンされたデータベースは、新しいアプリケーションを開発するためのベースラインとして機能し、運用環境で発生するアプリケーション エラーを分離するのに役立ちます。クローンされたデータベースは、ソフト データベース エラーからの回復にも使用できます。

* クローンのライフサイクル
+
SnapCenter を使用すると、実稼働データベースがビジーでないときに実行される定期的なクローン ジョブをスケジュールできます。


