---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: SnapCenterを使用してSQL Serverリソースをバックアップする前に、リソースまたはリソース グループのバックアップ ポリシーを作成することができます。また、リソース グループの作成時や単一のリソースのバックアップ時にバックアップ ポリシーを作成することも可能です。 
---
= SQL Serverデータベースのバックアップ ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してSQL Serverリソースをバックアップする前に、リソースまたはリソース グループのバックアップ ポリシーを作成することができます。また、リソース グループの作成時や単一のリソースのバックアップ時にバックアップ ポリシーを作成することも可能です。

.開始する前に
* データ保護戦略を定義しておく必要があります。
* SnapCenterのインストール、ホストの追加、リソースの特定、ストレージ システム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* ログ バックアップ用のホスト ログ ディレクトリを設定しておく必要があります。
* SQL Serverリソースを更新（検出）しておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートするユーザには、SnapCenter管理者がユーザに対してソースとデスティネーションの両方のボリューム用にStorage Virtual Machine（SVM）を割り当てておく必要があります。
+
管理者によるユーザへのリソースの割り当てについては、SnapCenterのインストール情報を参照してください。

* プリスクリプトとポストスクリプトでPowerShellスクリプトを実行する場合は、web.configファイルのusePowershellProcessforScriptsパラメータの値をtrueに設定する必要があります。
+
デフォルト値はfalseです。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"] 。


.タスク概要
* バックアップ ポリシーとは、バックアップを管理および保持する方法やリソースやリソース グループをバックアップする頻度を定めた一連のルールです。レプリケーションとスクリプトの設定を指定することもできます。ポリシーでオプションを指定しておくことで、別のリソース グループにポリシーを再利用して時間を節約することができます。
+
SCRIPTS_PATHは、プラグイン ホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。

+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、API を介して Swagger から表示できます: API /4.7/configsettings

+
GET APIを使用すると、キーの値を表示できます。SET APIはサポートされません。

* SnapLock
+
** [Retain the backup copies for a specific number of days]オプションを選択した場合は、SnapLockの保持期間をここで指定した保持日数以下にする必要があります。
+
Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、ポリシーで指定した数よりも多くのSnapshotが保持される可能性があります。

+
ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。







== ステップ1: ポリシー名を作成する

. 左側のナビゲーション ペインで、[*設定*] を選択します。
. [設定]ページで、[*ポリシー*]を選択します。
. *新規*を選択します。
. *名前*ページで、ポリシー名と詳細を入力します。




== ステップ2: ポリシーオプションを構成する

. ポリシー タイプ ページで、次の手順を実行します。
+
.. ストレージタイプを選択します。
.. ポリシーの範囲を選択します。
+
[role="tabbed-block"]
====
.フル バックアップとログ バックアップ
--
データベース ファイルとトランザクション ログをバックアップし、トランザクション ログを切り捨てます。

... *完全バックアップとログバックアップ*を選択します。
... 各Snapshotにバックアップするデータベースの最大数を入力します。
+

NOTE: 同時に複数のバックアップ処理を実行する場合は、この値を増やす必要があります。



--
.フル バックアップ
--
データベース ファイルをバックアップします。

... *完全バックアップ*を選択します。
... 各Snapshotにバックアップするデータベースの最大数を入力します。デフォルト値は100です。
+

NOTE: 同時に複数のバックアップ処理を実行する場合は、この値を増やす必要があります。



--
.ログ バックアップ
--
... トランザクション ログをバックアップします。
... *ログバックアップ*を選択します。


--
.コピーのみのバックアップ
--
... 別のバックアップ アプリケーションを使用してリソースをバックアップする場合は、[*コピーのみのバックアップ*] を選択します。


トランザクション ログが変更されずに保持されるため、任意のバックアップ アプリケーションでデータベースをリストアできます。通常、他の状況ではコピーのみのオプションを使用しないでください。


NOTE: Microsoft SQL は、セカンダリ ストレージの *完全バックアップとログ バックアップ* オプションとともに *コピーのみのバックアップ* オプションをサポートしていません。

--
====






== ステップ3: 可用性グループの設定を構成する

. [Availability Group Settings]セクションで、次の操作を実行します。
+
.. Backup on preferred backup replica only
+
優先バックアップ レプリカのみをバックアップする場合は、このオプションを選択します。優先バックアップ レプリカは、SQL ServerのAGに対して指定されているバックアップ設定によって決まります。

.. バックアップするレプリカを選択します。
+
バックアップするプライマリまたはセカンダリのAGレプリカを選択します。

.. バックアップ優先度（最小および最大のバックアップ優先度）を選択します
+
バックアップするAGレプリカを決めるための、バックアップの最小優先順位と最大優先順位を指定します。たとえば、最小優先順位を10、最大優先順位を50に設定すると、優先順位が10より高く50より低いすべてのAGレプリカがバックアップ用とみなされます。

+
デフォルトでは、最小優先順位は1、最大優先順位は100です。



+

NOTE: クラスタ構成では、ポリシーで設定された保持設定に従って、バックアップがクラスタの各ノードに保持されます。AGの所有者ノードが変更された場合、保持設定に従ってバックアップが作成され、以前の所有者ノードのバックアップが保持されます。AGの保持設定はノード レベルでのみ適用されます。





== ステップ4: スナップショットとレプリケーションの設定を構成する

. スナップショットとレプリケーション ページで、次の手順を実行します。
+
.. *オンデマンド*、*時間別*、*日次*、*週次*、または*月次*を選択してスケジュール タイプを指定します。
+
ポリシーに対して選択できるスケジュール タイプは1つだけです。

+

NOTE: リソース グループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、および頻度）を指定することができます。これにより、ポリシーとバックアップ間隔が同じである複数のリソース グループを作成できますが、各ポリシーに異なるバックアップ スケジュールを割り当てることもできます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間 (DST) 中はスケジュールは実行されません。







== ステップ5: 最新の保持設定を構成する

. 「最新の保持設定」セクションで、バックアップ タイプ ページで選択したバックアップ タイプに応じて、次のアクションの 1 つ以上を実行します。


[role="tabbed-block"]
====
.特定のコピー数
--
特定の数のSnapshotのみを保持します。

. *過去 <数値> 日間のログ バックアップを保持する* オプションを選択し、保持する日数を指定します。この上限に近づいた場合は、古いコピーを削除できます。


--
.特定の日数
--
バックアップ コピーを特定の日数だけ保持します。

. *[過去 <数値> 日間の完全バックアップに適用可能なログ バックアップを保持する]* オプションを選択し、ログ バックアップ コピーを保持する日数を指定します。


--
====


== ステップ6: スナップショットの設定を構成する

. 完全バックアップの保持設定では、次の操作を実行します。
+
.. 保存するスナップショットの合計数を指定します
+
... 保持するスナップショットの数を指定するには、[*保持するコピー数*] を選択します。
... Snapshotの数が指定した数を超えると、古いものから順にSnapshotが削除されます。
+

IMPORTANT: デフォルトでは、保持数の値は2に設定されています。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗することがあります。

+

NOTE: 最大保持値は 1018 です。保持期間が基盤となるNetApp ONTAPバージョンでサポートされている値よりも高い値に設定されている場合、バックアップは失敗します。







. スナップショットを保存する期間
+
.. スナップショットを削除する前に保持する日数を指定する場合は、「*コピーを保持する期間*」を選択します。


. *スナップショット コピーのロック期間* を選択し、期間を日数、月数、または年数で指定します。
+
SnapLock保持期間は100年未満にする必要があります。

. ポリシーラベルを選択します。
+

NOTE: リモート レプリケーションのプライマリ スナップショットにSnapMirrorラベルを割り当てることで、プライマリ スナップショットによってスナップショット レプリケーション操作をSnapCenterからONTAPセカンダリ システムにオフロードできるようになります。これは、ポリシー ページでSnapMirrorまたはSnapVaultオプションを有効にしなくても実行できます。





== ステップ7: セカンダリレプリケーションオプションを構成する

. [セカンダリ レプリケーション オプションの選択] セクションで、次のセカンダリ レプリケーション オプションの 1 つまたは両方を選択します。


[role="tabbed-block"]
====
.SnapMirror を更新
--
ローカル Snapshot コピーの作成後に SnapMirror を更新

. 別のボリュームにバックアップ セットのミラー コピーを作成する場合（SnapMirror）は、このオプションを選択します。
+
このオプションは、SnapMirrorアクティブ同期に対して有効にする必要があります。

+
セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

+
見るlink:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["[Topology]ページでのSQL Serverのバックアップとクローンの表示"] 。



--
.SnapVault を更新
--
Snapshotコピーの作成後にSnapVaultを更新します。

. ディスクツーディスクのバックアップ レプリケーションを実行する場合は、このオプションを選択します。
+
セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

+
SnapLock がSnapLock Vault と呼ばれるONTAPのセカンダリにのみ設定されている場合、[トポロジ] ページの [更新] ボタンをクリックすると、 ONTAPから取得されたセカンダリのロック期間が更新されます。

+
SnapLock Vaultの詳細については、 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["バックアップ デスティネーションのSnapshotコピーのWORM状態へのコミット"]

+
見るlink:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["[Topology]ページでのSQL Serverのバックアップとクローンの表示"] 。



--
.エラー時の再試行回数
--
. レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。


--
====


== ステップ8: スクリプト設定を構成する

. [Script]ページで、バックアップ処理の前またはあとに実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

+

NOTE: プリスクリプトやポストスクリプトのパスに、ドライブや共有を含めることはできません。パスは、SCRIPTS_PATHの相対パスである必要があります。

+

NOTE: セカンダリ ストレージがSnapshotの最大数に達しないように、ONTAPでSnapMirrorの保持ポリシーを設定する必要があります。





== ステップ9: 検証設定を構成する

[Verification]ページで、次の手順を実行します。

. [Run verification for following backup schedules]セクションで、実行頻度を選択します。
. [Database consistency check options]セクションで、次の操作を実行します。
+
.. Limit the integrity structure to physical structure of the database (PHYSICAL_ONLY)
+
... 整合性チェックをデータベースの物理構造に制限し、破損したページ、チェックサム障害、およびデータベースに影響する一般的なハードウェア障害を検出するには、[整合性構造をデータベースの物理構造に制限する (PHYSICAL_ONLY)] を選択します。


.. Suppress all information messages (NO INFOMSGS)
+
... すべての情報メッセージを抑制するには、[すべての情報メッセージを抑制 (NO_INFOMSGS)] を選択します。このオプションはデフォルトで選択されています。


.. Display all reported error messages per object (ALL_ERRORMSGS)
+
... オブジェクトごとに報告されたすべてのエラーを表示するには、*オブジェクトごとに報告されたすべてのエラー メッセージを表示する (ALL_ERRORMSGS)* を選択します。


.. Do not check nonclustered indexes (NOINDEX)
+
... 非クラスター化インデックスをチェックしない場合は、[非クラスター化インデックスをチェックしない (NOINDEX)] を選択します。SQL Serverデータベースは、Microsoft SQL ServerのDatabase Consistency Checker（DBCC）を使用して、データベース内のオブジェクトの論理的な整合性と物理的な整合性をチェックします。


.. 内部データベーススナップショット (TABLOCK) を使用する代わりに、チェックを制限してロックを取得します。
+
... 内部データベース スナップショットを使用する代わりにチェックを制限し、ロックを取得するには、[*内部データベース スナップショット コピーを使用する代わりにチェックを制限し、ロックを取得する (TABLOCK)*] を選択します。




. *ログ バックアップ* セクションで、*完了時にログ バックアップを検証する* を選択して、完了時にログ バックアップを検証します。
. *検証スクリプト設定*セクションで、検証操作の前または後に実行するプレスクリプトまたはポストスクリプトのパスと引数を入力します。
+

NOTE: プリスクリプトやポストスクリプトのパスに、ドライブや共有を含めることはできません。パスは、SCRIPTS_PATHの相対パスである必要があります。





== ステップ10: 概要を確認する

. 概要を確認し、[完了] を選択します。

