---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenterは、クレデンシャルを使用してSnapCenterの処理を実行するユーザを認証します。SnapCenterプラグインのインストールに使用するクレデンシャルと、データベースやWindowsファイルシステムでのデータ保護処理に使用するクレデンシャルをそれぞれ作成する必要があります。 
---
= SnapCenter Plug-ins Package for Windowsのクレデンシャルの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterは、クレデンシャルを使用してSnapCenterの処理を実行するユーザを認証します。SnapCenterプラグインのインストールに使用するクレデンシャルと、データベースやWindowsファイルシステムでのデータ保護処理に使用するクレデンシャルをそれぞれ作成する必要があります。

.開始する前に
* プラグインのインストール前にWindowsクレデンシャルを設定する必要があります。
* このクレデンシャルには、管理者権限（リモート ホストに対する管理者権限を含む）を設定する必要があります。
* WindowsホストでのSQL認証
+
プラグインのインストール後にSQLクレデンシャルを設定する必要があります。

+
SnapCenter Plug-in for Microsoft SQL Serverを導入する場合は、プラグインのインストール後にSQLクレデンシャルを設定する必要があります。このクレデンシャルは、SQL Serverのsysadmin権限があるユーザに対して設定します。

+
SQL認証方式は、SQL Serverインスタンスに照らして認証します。したがって、SQL ServerインスタンスがSnapCenterで検出されなければなりません。そのため、SQLクレデンシャルを追加する前に、ホストの追加とプラグイン パッケージのインストールを完了し、リソースをリフレッシュしておく必要があります。SQL Server認証は、スケジュール設定やリソース検出などの処理を実行する際に必要になります。



.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*資格情報*]をクリックします。
. *新規*をクリックします。
. [Credential]ページで、クレデンシャルの設定に必要な情報を指定します。
+
|===
| フィールド | 操作 


 a| 
資格情報名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザー名/パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者
+
SnapCenterプラグインをインストールするシステムのドメイン管理者を指定します。[Username]フィールドの有効な形式は次のとおりです。

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** ローカル管理者（ワークグループの場合のみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。ユーザー名フィールドの有効な形式は次のとおりです。 `UserName`

+
パスワードには二重引用符 (") やバッククォート (`) を使用しないでください。未満記号（<）と感嘆符（!）を組み合わせて使用したりしないでください。たとえば、lessthan<!10、lessthan10<!、バックティック`12 などです。





 a| 
Authentication Mode
 a| 
使用する認証モードを選択します。SQL認証モードを選択した場合は、SQL ServerインスタンスとそのSQLインスタンスのホストも指定する必要があります。

|===
. [OK]をクリックします。


クレデンシャルの設定が完了したら、必要に応じて[User and Access]ページでユーザやユーザ グループにクレデンシャルを割り当てることができます。
