---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: SnapCenterを使用して、リソース グループまたはデータベースからクローンを作成できます。オンデマンド クローンを実行することも、リソース グループまたはデータベースの定期的なクローン操作をスケジュールすることもできます。バックアップを定期的にクローニングすると、クローンを使用してアプリケーションの開発、データの取り込み、またはデータのリカバリを行うことができます。 
---
= クローン ライフサイクルの実行
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用して、リソース グループまたはデータベースからクローンを作成できます。クローニングはオンデマンドで実行することも、リソース グループまたはデータベースに対して定期的なクローニング処理をスケジュール設定することもできます。バックアップを定期的にクローニングすると、クローンを使用してアプリケーションの開発、データの取り込み、またはデータのリカバリを行うことができます。

SnapCenterでは、複数のサーバで同時に複数のクローニング処理を実行するようにスケジュールを設定できます。

.開始する前に
* スタンドアロン データベース インスタンスをクローニングする場合は、マウント ポイント パスが存在すること、および専用ディスクであることを確認してください。
* フェイルオーバー クラスタ インスタンス（FCI）をクローニングする場合は、マウント ポイントが存在すること、共有ディスクであること、およびパスとFCIが同じSQLリソース グループに属していることを確認してください。
* ソース データベースまたはターゲット インスタンスがクラスタ共有ボリューム（CSV）上にある場合、クローニングされたデータベースはCSV上に配置されます。



NOTE: 仮想環境（VMDK / RDM）の場合は、マウント ポイントが専用ディスクであることを確認してください。

.タスク概要
* SCRIPTS_PATHは、プラグイン ホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、API を介して Swagger から表示できます: API /4.7/configsettings

+
GET APIを使用すると、キーの値を表示できます。SET APIはサポートされません。

* [Clone lifecycle]ウィザードの各ページのフィールドのほとんどはわかりやすいもので、説明を必要としません。以下の手順では、説明が必要なフィールドを取り上げます。
* ONTAP 9.12.1以前のバージョンでは、Snapshotのロック期間を指定すると、改ざん防止Snapshotから作成されたクローンにSnapLockの有効期限が継承されます。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。


.手順
. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. [リソース] ページで、[表示] リストから [データベース] または [リソース グループ] を選択します。
. リソース グループまたはデータベースを選択し、[*ライフサイクルの複製*] をクリックします。
. [Options]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
Clone job name
 a| 
クローン ライフサイクル ジョブに、ジョブを監視および変更する際にわかりやすい名前を指定します。



 a| 
Clone server
 a| 
クローンをどのホストに配置するかを選択します。



 a| 
Clone instance
 a| 
データベースのクローニング先となるクローン インスタンスを選択します。指定したクローン サーバ上のSQLインスタンスを選択する必要があります。



 a| 
Clone suffix
 a| 
クローン データベースに付加される、データベースがクローンであることを示すサフィックスを入力します。クローン リソース グループの作成に使用する各SQLインスタンスには、一意なデータベース名が必要です。たとえば、クローン リソース グループに SQL インスタンス "`inst1`" からのソース データベース "`db1`" が含まれており、"`db1`" が "`inst1`" にクローンされている場合、クローン データベース名は "`db1__clone`" になります。データベースは同じインスタンスに複製されるため、「`__clone`」は必須のユーザー定義サフィックスです。  「`db1`」が SQL インスタンス「`inst2`」にクローンされる場合、データベースは別のインスタンスにクローンされるため、クローン データベース名は「`db1`」のままになります (サフィックスはオプションです)。



 a| 
Auto assign mount point / Auto assign volume mount point under path
 a| 
マウント ポイントを自動的に割り当てるか、またはパスを指定してボリューム マウント ポイントを自動的に割り当てるかを選択します。[Auto assign volume mount point under path]を選択した場合は、ディレクトリを指定できます。指定したディレクトリにマウント ポイントが作成されます。このオプションを選択する場合は、ディレクトリが空であることを事前に確認しておく必要があります。ディレクトリにデータベースが格納されている場合、そのデータベースはマウント処理後に無効な状態になります。

|===
. [Location]ページで、クローンを作成するストレージの場所を選択します。
. [Script]ページで、クローニング処理の前またはあとに実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

+

NOTE: プリスクリプトやポストスクリプトのパスに、ドライブや共有を含めることはできません。パスは、SCRIPTS_PATHの相対パスである必要があります。

+
デフォルトのスクリプト タイムアウトは60秒です。

. [Schedule]ページで、次のいずれかを実行します。
+
** クローンジョブをすぐに実行するには、[今すぐ実行] を選択します。
** クローン操作を実行する頻度、クローン スケジュールを開始する日時、クローン操作を実行する日、スケジュールの有効期限、スケジュールの有効期限が切れた後にクローンを削除するかどうかを決定する場合は、[スケジュールの構成] を選択します。


. 通知ページの *電子メール設定* ドロップダウン リストから、電子メールを送信するシナリオを選択します。
+
また、送信者と受信者のEメール アドレス、およびEメールの件名を指定する必要があります。実行されたクローン操作のレポートを添付する場合は、「*ジョブ レポートの添付*」を選択します。

+

NOTE: Eメール通知を利用する場合は、GUIまたはPowerShellのSet-SmSmtpServerコマンドを使用して、SMTPサーバの詳細を指定しておく必要があります。

+
EMSについては、 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["EMSデータ収集の管理"]

. 概要を確認し、[完了] をクリックします。


*モニター* > *ジョブ* ページを使用して、クローン作成プロセスを監視する必要があります。
