---
permalink: protect-scsql/task_reseed_availability_group_databases.html 
sidebar: sidebar 
keywords: reseed 
summary: '再シードは、可用性グループ (AG) データベースを復元するためのオプションです。セカンダリ データベースがAG内のプライマリ データベースと同期していない場合は、セカンダリ データベースを再シードできます。' 
---
= 可用性グループ データベースの再シード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
再シードは、可用性グループ（AG）データベースをリストアするためのオプションです。セカンダリ データベースがAG内のプライマリ データベースと同期していない場合は、セカンダリ データベースを再シードできます。

.開始する前に
* リストアするセカンダリAGデータベースのバックアップを作成しておく必要があります。
* SnapCenter Serverとプラグイン ホストには、同じバージョンのSnapCenterがインストールされている必要があります。


.タスク概要
* プライマリ データベースには再シード処理を実行できません。
* 可用性グループからレプリカ データベースが削除されると、再シード処理を実行できません。レプリカが削除されると、再シード処理は失敗します。
* SQL可用性グループ データベースで再シード処理を実行する際には、その可用性グループ データベースのレプリカ データベースでログ バックアップがトリガーされないようにしてください。再シード処理中にログ バックアップがトリガーされると、再シード処理は失敗し、「The mirror database, "database_name" has insufficient transaction log data to preserve the log backup chain of the principal database」というエラー メッセージが表示されます。


.手順
. 左側のナビゲーション ペインで [リソース] をクリックし、リストから [SnapCenter Plug-in for SQL Server] を選択します。
. [リソース] ページで、[表示] リストから [データベース] を選択します。
. リストからセカンダリAGデータベースを選択します。
. *再シード*をクリックします。
. *モニター* > *ジョブ* をクリックして、操作の進行状況を監視します。

