---
permalink: protect-sco/backup_types.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: Oracle データベースでサポートされているバックアップの種類。 
---
= Oracleデータベースでサポートされるバックアップ タイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップ タイプでは、作成するバックアップのタイプを指定します。SnapCenterでは、Oracleデータベースに対してオンライン バックアップ タイプとオフライン バックアップ タイプがサポートされます。



== オンライン バックアップ

データベースがオンライン状態のときに作成されるバックアップを、オンライン バックアップと呼びます。ホット バックアップとも呼ばれるオンライン バックアップでは、データベースをシャットダウンすることなくバックアップを作成できます。

オンライン バックアップでは、次のファイルのバックアップを作成できます。

* データ ファイルと制御ファイルのみ
* アーカイブ ログ ファイルのみ（この場合はデータベースがバックアップ モードになりません）
* データベース全体（データ ファイル、制御ファイル、およびアーカイブ ログ ファイル）




== オフライン バックアップ

データベースがマウント済み状態またはシャットダウン状態のときに作成されるバックアップを、オフライン バックアップと呼びます。オフライン バックアップはコールド バックアップとも呼ばれます。オフライン バックアップにはデータ ファイルと制御ファイルのみを含めることができます。オフライン マウント バックアップまたはオフライン シャットダウン バックアップのいずれかを作成できます。

* オフライン マウント バックアップを作成する場合は、データベースがマウント済み状態であることを確認する必要があります。
+
データベースがそれ以外の状態であると、バックアップ処理は失敗します。

* オフライン シャットダウン バックアップを作成する場合は、データベースはどの状態でもかまいません。
+
データベースは、バックアップを作成するために必要な状態に変更されます。バックアップが作成されると、データベースは元の状態に戻ります。


