---
permalink: protect-sco/discover-oracle-database.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter がOracle データベースを検出する方法。 
---
= SnapCenterのOracleデータベース検出方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースは、 SnapCenterによって管理されるホスト上の Oracle データベースです。使用できるデータベースを検出したあとに、それらのデータベースをリソース グループに追加してデータ保護処理を実行できます。

次のセクションでは、さまざまなタイプとバージョンのOracleデータベースを検出するためにSnapCenterが使用するプロセスについて説明します。



== Oracle バージョン 11__g__ から 12__c__R1 の場合

.RACデータベース
RAC データベースは、/etc/oratab エントリに基づいてのみ検出されます。/etc/oratabファイルにデータベース エントリが含まれている必要があります。

.スタンドアロン
スタンドアロン データベースは、/etc/oratabエントリに基づいてのみ検出されます。

.ASM
ASMインスタンス エントリが/etc/oratabファイルに含まれている必要があります。

.RAC One Node
RAC One Nodeデータベースは、/etc/oratabエントリに基づいてのみ検出されます。データベースは、nomount、mount、または open のいずれかの状態である必要があります。/etc/oratabファイルにデータベース エントリが含まれている必要があります。

データベースがすでに検出され、バックアップがデータベースに関連付けられている場合、RAC One Nodeデータベースのステータスは名前変更または削除とマークされます。

データベースを再配置した場合は、次の手順を実行する必要があります。

. フェイルオーバーされたRACノードの/etc/oratabファイルに、再配置されたデータベースのエントリを手動で追加します。
. リソースを手動で更新します。
. リソース ページから RAC One Node データベースを選択し、「データベース設定」をクリックします。
. データベースを設定して、データベースを現在ホストしているRACノードに優先クラスタ ノードを設定します。
. SnapCenterの処理を実行します。
. あるノードから別のノードにデータベースを再配置したときに、以前のノードのoratabエントリが削除されていない場合は、同じデータベースが2回表示されないように、oratabエントリを手動で削除します。




== Oracleバージョン12cR2から18c、19c、または21cの場合

.RACデータベース
RACデータベースはsrvctl configコマンドを使用して検出されます。/etc/oratabファイルにデータベース エントリが含まれている必要があります。

.スタンドアロン
スタンドアロン データベースは、/etc/oratabファイルのエントリとsrvctl configコマンドの出力に基づいて検出されます。

.ASM
ASMインスタンス エントリが/etc/oratabファイルに含まれている必要はありません。

.RAC One Node
RAC One Nodeデータベースは、srvctl configコマンドのみを使用して検出されます。データベースは、nomount、mount、または open のいずれかの状態である必要があります。データベースがすでに検出され、バックアップがデータベースに関連付けられている場合、RAC One Nodeデータベースのステータスは名前変更または削除とマークされます。

データベースを再配置する場合は、次の手順を実行する必要があります。リソースを手動で更新します。 。リソース ページから RAC One Node データベースを選択し、「データベース設定」をクリックします。 。データベースを設定して、データベースを現在ホストしているRACノードに優先クラスタ ノードを設定します。 。SnapCenterの処理を実行します。


NOTE: /etc/oratab ファイルに Oracle 12__c__R2 および 18__c__ データベース エントリがあり、同じデータベースが srvctl config コマンドで登録されている場合、 SnapCenter は重複するデータベース エントリを削除します。古いデータベース エントリがある場合、データベースは検出されますが、データベースは到達不能になり、ステータスはオフラインになります。
