---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter がOracle データベースを検出する方法。 
---
= RACセットアップにおける優先ノード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle Real Application Clusters (RAC) セットアップでは、 SnapCenterがバックアップ操作を実行するために使用する優先ノードを指定できます。優先ノードを指定しない場合は、SnapCenterによって自動的に優先ノードが割り当てられ、そのノードにバックアップが作成されます。

優先ノードには、RACデータベース インスタンスが存在するクラスタ ノードを1つまたは複数指定できます。バックアップ処理は、指定したノードでのみ、指定した順序で実行されます。

.例
RACデータベースcdbracに3つのインスタンスがあり、cdbrac1はnode1に、cdbrac2はnode2に、cdbrac3はnode3に置かれているとします。

node1とnode2のインスタンスが優先ノードとして設定され、node2に第1優先順位、node1に第2優先順位が指定されています。バックアップ処理を実行すると、まず第1優先ノードであるnode2で処理が試行されます。

node2がバックアップできる状態にない場合（ホストでプラグイン エージェントが実行されていない、ホスト上のデータベース インスタンスが指定したタイプのバックアップを行うのに必要な状態にない、Flex ASM構成のnode2上のデータベース インスタンスがローカルASMインスタンスによって処理されていない、などの複数の原因が考えられます）、node1で処理が試行されます。

node3は、優先ノードのリストに含まれていないため、バックアップには使用されません。



== Flex ASMセットアップ

Flex ASMセットアップでは、カーディナリティがRACクラスタ内のノード数より少ない場合、リーフ ノードは優先ノードとしてリストされません。Flex ASMクラスタ ノードのロールに変更があった場合は、優先ノードが更新されるように手動で検出する必要があります。



== 必要なデータベースの状態

バックアップを正常に完了するには、優先ノード上のRACデータベース インスタンスが必要な状態であることが必要です。

* オンライン バックアップを作成する場合は、設定された優先ノードのRACデータベース インスタンスの1つがオープン状態であることが必要です。
* オフライン マウント バックアップを作成する場合は、設定された優先ノードのRACデータベース インスタンスの1つがマウント状態であり、かつ他の優先ノードを含むその他すべてのインスタンスがマウント状態またはそれより低いレベルの状態であることが必要です。
* オフライン シャットダウン バックアップを作成する場合は、RACデータベース インスタンスはどの状態でもかまいませんが、優先ノードを指定する必要があります。

