---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: Oracleデータベースをクローニングする前に、前提条件が満たされていることを確認する必要があります。 
---
= Oracleデータベースをクローニングするための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracleデータベースをクローニングする前に、前提条件が満たされていることを確認する必要があります。

* SnapCenterを使用してデータベースのバックアップを作成しておく必要があります。
+
クローニング処理を行うには、オンラインのデータ バックアップとログのバックアップ、またはオフラインでの（マウントまたはシャットダウンの）バックアップが正常に作成されている必要があります。

* 制御ファイルまたはRedoログ ファイルのパスをカスタマイズする場合は、必要なファイルシステムまたはAutomatic Storage Management（ASM）ディスク グループを事前にプロビジョニングしておく必要があります。
+
デフォルトでは、クローン データベースのRedoログ ファイルと制御ファイルは、クローン データベースのデータ ファイル用にSnapCenterによってプロビジョニングされたASMディスク グループまたはファイルシステムに作成されます。

* NFS 経由で ASM を使用している場合は、asm_diskstring パラメータで定義されている既存のパスに _/var/opt/snapcenter/scu/clones/*/*_ を追加する必要があります。
* asm_diskstring パラメータでは、ASMFD を使用している場合は _AFD:*_ を構成し、ASMLIB を使用している場合は _ORCL:*_ を構成する必要があります。
+
asm_diskstringパラメータを編集する方法については、以下を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["asm_diskstringにディスクパスを追加する方法"^] 。

* 代替ホストにクローンを作成する場合は、代替ホストが次の要件を満たしている必要があります。
+
** 代替ホストにSnapCenter Plug-in for Oracle Database をインストールする必要があります。
** クローン ホストは、プライマリ ストレージまたはセカンダリ ストレージから LUN を検出できる必要があります。
+
*** プライマリ ストレージまたはセカンダリ (Vault または Mirror) ストレージから代替ホストにクローンを作成する場合は、セカンダリ ストレージと代替ホストの間で iSCSI セッションが確立されていること、または FC 用に適切にゾーン分けされていることを確認します。
*** Vault またはミラー ストレージから同じホストにクローンを作成する場合は、Vault またはミラー ストレージとホストの間で iSCSI セッションが確立されていること、または FC 用に適切にゾーン分けされていることを確認してください。
*** 仮想化環境でクローンを作成する場合は、プライマリまたはセカンダリ ストレージと代替ホストをホストする ESX サーバーの間で iSCSI セッションが確立されていること、または FC 用に適切にゾーン分けされていることを確認します。
+
詳細については、 https://docs.netapp.com/us-en/ontap-sanhost/["ホストユーティリティのドキュメント"] 。



** ソース データベースが ASM データベースの場合:
+
*** クローンが実行されるホスト上で ASM インスタンスが起動され、実行されている必要があります。
*** クローンされたデータベースのアーカイブ ログ ファイルを専用の ASM ディスク グループに配置する場合は、クローン操作の前に ASM ディスク グループをプロビジョニングする必要があります。
*** データ ディスク グループの名前は構成できますが、クローンが実行されるホスト上の他の ASM ディスク グループでその名前が使用されていないことを確認してください。
+
ASMディスク グループ上のデータ ファイルは、SnapCenterクローン ワークフローの一部としてプロビジョニングされます。



** NVMeの場合は、NVMeユーティリティがインストールされている必要があります。


* ログ バックアップを使用した代替ホストへのクローニングの際にセカンダリ ロケータを検出するには、データLUNとログLUNの保護タイプ（mirror、vault、mirror-vaultなど）を同じものにする必要があります。
* 12_c_ データベースのバックアップをクローンするためのシード PDB 関連情報を取得するには、ソース データベース パラメータ ファイルで exclude_seed_cdb_view の値を FALSE に設定する必要があります。
+
シードPDBとは、CDBがPDBを作成する際に使用する、システム付属のテンプレートです。シードPDBの名前はPDB$SEEDです。PDB$SEEDについては、Oracle Doc ID 1940806.1を参照してください。

+

NOTE: 12_c_ データベースをバックアップする前に値を設定する必要があります。

* SnapCenterはautofsサブシステムによって管理されるファイルシステムのバックアップをサポートしています。データベースをクローニングする場合は、データ マウント ポイントがautofsマウント ポイントのルートの下に配置されないようにしてください。プラグイン ホストのrootユーザには、autofsマウント ポイントのルートの下にディレクトリを作成する権限がないためです。
+
制御ログ ファイルとRedoログ ファイルがデータ マウント ポイントにある場合は、制御ファイルのパスを変更し、Redoログ ファイルのパスも適切に変更する必要があります。

+

NOTE: クローニングされた新しいマウント ポイントはautofsサブシステムに手動で登録できます。クローニングされた新しいマウント ポイントが自動的に登録されることはありません。

* TDE (自動ログイン) があり、同じホストまたは別のホストにデータベースを複製する場合は、_/etc/ORACLE/WALLET/$ORACLE_SID_ の下にあるウォレット (キー ファイル) をソース データベースから複製されたデータベースにコピーする必要があります。
* Oracle Linux 7 以降または Red Hat Enterprise Linux (RHEL) 7 以降のストレージ エリア ネットワーク (SAN) 環境でクローン作成を正常に実行するには、_/etc/lvm/lvm.conf_ で use_lvmetad = 0 の値を設定し、lvm2-lvmetad サービスを停止する必要があります。
* Oracleデータベース11.2.0.3以降を使用していて、補助インスタンスのデータベースIDがNIDスクリプトを使用して変更されている場合は、13366202 Oracleパッチをインストールする必要があります。
* ボリュームをホストするアグリゲートがStorage Virtual Machine（SVM）の割り当て済みアグリゲート リストに含まれていることを確認します。
* NVMeで接続から除外する必要のあるターゲット ポートがある場合は、ターゲットのノード名とポート名を/var/opt/snapcenter/scu/etc/nvme.confファイルに追加します。
+
ファイルが存在しない場合は、次の例に示すようにファイルを作成する必要があります。

+
....
blacklist {
nn-0x<target_node_name_1>:pn-0x<target_port_name_1>
nn-0x<target_node_name_2>:pn-0x<target_port_name_2>
}
....
* iSCSIプロトコルとFCプロトコルが混在するigroupを使用して、LUNがAIXホストにマッピングされていないことを確認します。詳細については、以下を参照してください。  https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_Plug-in_for_Oracle_operations_fail_with_error_Unable_to_discover_the_device_for_LUN_LUN_PATH["LUNのデバイスを検出できないというエラーが発生し、操作が失敗しました"^] 。

