---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem 
summary: SnapCenterは、物理マシンと仮想マシンの両方でさまざまなストレージ タイプをサポートしています。SnapCenter Plug-ins Package for LinuxまたはSnapCenter Plug-ins Package for AIXをインストールする前に、ストレージ タイプがサポートされていることを確認する必要があります。 
---
= Plug-in for Oracle Databaseでサポートされるストレージ タイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterは、物理マシンと仮想マシンの両方でさまざまなストレージ タイプをサポートしています。SnapCenter Plug-ins Package for LinuxまたはSnapCenter Plug-ins Package for AIXをインストールする前に、ストレージ タイプがサポートされていることを確認する必要があります。

SnapCenterでは、LinuxおよびAIXのストレージ プロビジョニングはサポートされていません。



== Linuxでサポートされるストレージ タイプ

次の表に、Linuxでサポートされるストレージ タイプを示します。

|===
| マシン | ストレージ タイプ 


 a| 
物理サーバ
 a| 
* FC接続LUN
* iSCSI接続LUN
* NFS接続ボリューム
* NVMe-FC
* NVMe/TCP




 a| 
VMware ESXi
 a| 
* FCまたはiSCSI HBAで接続されたRDM LUNホスト バス アダプタ（HBA）のスキャンは、SnapCenterがホストに存在するすべてのホスト バス アダプタをスキャンするため、完了までに時間がかかることがあります。
+
_/opt/ NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ にある *LinuxConfig.pm* ファイルを編集して、*SCSI_HOSTS_OPTIMIZED_RESCAN* パラメータの値を 1 に設定し、HBA_DRIVER_NAMES にリストされている HBA のみを再スキャンすることができます。

* iSCSIイニシエータでゲスト システムに直接接続されたiSCSI LUN
* NFSデータストア上のVMDK
* NVMe/TCP 経由で作成された VMFS 上の VMDK
+

NOTE: RACは、共有VMDKをサポートするESX 8.0U2でサポートされます。

* ゲスト システムに直接接続されたNFSボリューム
* NFSとSANの両方に存在するvVolデータストア
+
vVolデータストアは、ONTAP Tools for VMware vSphereでのみプロビジョニングできます。



|===


== AIXでサポートされるストレージ タイプ

次の表に、AIXでサポートされるストレージ タイプを示します。

|===
| マシン | ストレージ タイプ 


 a| 
物理サーバ
 a| 
* FC接続およびiSCSI接続のLUN
+
SAN環境では、ASM、LVM、SANファイルシステムがサポートされます。

+

NOTE: AIXおよびファイルシステムでのNFSはサポートされていません。

* 拡張ジャーナリング ファイルシステム（JFS2）
+
SANファイルシステムおよびLVMレイアウトでのインライン ロギングをサポートします。



|===
その https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"]サポートされているバージョンに関する最新情報が含まれています。
