---
permalink: protect-sco/task_define_a_backup_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: バックアップ戦略を定義すると、データベースを正常に復元または複製する手段が確保されます。 
---
= Oracleデータベースのバックアップ戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースを正常にリストアまたはクローニングできるように、バックアップ戦略を定義します。

バックアップ戦略の大部分は、サービス レベル アグリーメント（SLA）、目標復旧時間（RTO）、および目標復旧時点（RPO）によって決まります。

* SLAとは、求められるサービス レベル、およびサービスに関連する問題（サービスの可用性やパフォーマンスなど）への対応を定義したものです。
* RTOは、サービスの停止からビジネス プロセスの復旧までに必要となる時間を定義したものです。
* RPOは、障害発生後に通常処理を再開するためにバックアップ ストレージからリカバリする必要があるファイルの経過時間を定義したものです。




== バックアップ対象としてサポートされるOracleデータベース構成

SnapCenterでは、各種のOracleデータベース構成のバックアップがサポートされます。

* Oracle Standalone
* Oracle Real Application Clusters（RAC）
* Oracle Standalone Legacy
* Oracle Standalone Container Database（CDB）
* Oracle Data Guardスタンバイ
+
Data Guardスタンバイ データベースで作成できるのは、オフライン マウント バックアップのみです。オフライン シャットダウン バックアップ、アーカイブ ログのみのバックアップ、フル バックアップはサポートされていません。

* Oracle Active Data Guardスタンバイ
+
Active Data Guardスタンバイ データベースで作成できるのは、オンライン バックアップのみです。アーカイブ ログのみのバックアップとフル バックアップはサポートされていません。

+

NOTE: Data Guardスタンバイ データベースまたはActive Data Guardスタンバイ データベースのバックアップを作成する場合は、管理されたリカバリ プロセス（MRP）が事前に停止し、バックアップが作成されたあとにMRPが開始されます。

* Automatic Storage Management（ASM）
+
** ASM スタンドアロンおよび仮想マシン ディスク (VMDK) 上の ASM RAC
+

NOTE: Oracleデータベースでサポートされているすべてのリストア方式の中で、VMDK上のASM RACデータベースで実行できるのはConnect and Copyリストアだけです。

** ASM スタンドアロンおよび Raw デバイス マッピング (RDM) 上の ASM RAC ASMLib の有無にかかわらず、ASM 上の Oracle データベースでバックアップ、復元、およびクローン操作を実行できます。
** Oracle ASMフィルタ ドライバ（ASMFD）
+

NOTE: PDB移行およびPDBクローニング処理はサポートされていません。

** Oracle Flex ASM




サポートされているOracleバージョンの最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^] 。



== Oracleデータベースでサポートされるバックアップ タイプ

バックアップ タイプでは、作成するバックアップのタイプを指定します。SnapCenterでは、Oracleデータベースに対してオンライン バックアップ タイプとオフライン バックアップ タイプがサポートされます。



=== オンライン バックアップ

データベースがオンライン状態のときに作成されるバックアップを、オンライン バックアップと呼びます。ホット バックアップとも呼ばれるオンライン バックアップでは、データベースをシャットダウンすることなくバックアップを作成できます。

オンライン バックアップでは、次のファイルのバックアップを作成できます。

* データファイルと制御ファイルのみ
* アーカイブ ログ ファイルのみ（この場合はデータベースがバックアップ モードになりません）
* データベース全体（データファイル、制御ファイル、およびアーカイブ ログ ファイル）




=== オフライン バックアップ

データベースがマウント済み状態またはシャットダウン状態のときに作成されるバックアップを、オフライン バックアップと呼びます。オフライン バックアップはコールド バックアップとも呼ばれます。オフライン バックアップにはデータファイルと制御ファイルのみを含めることができます。オフライン マウント バックアップまたはオフライン シャットダウン バックアップのいずれかを作成できます。

* オフライン マウント バックアップを作成する場合は、データベースがマウント済み状態であることを確認する必要があります。
+
データベースがそれ以外の状態であると、バックアップ処理は失敗します。

* オフライン シャットダウン バックアップを作成する場合は、データベースはどの状態でもかまいません。
+
データベースは、バックアップを作成するために必要な状態に変更されます。バックアップが作成されると、データベースは元の状態に戻ります。





== SnapCenterのOracleデータベース検出方法

「リソース」となるのは、ホスト上でSnapCenterによって管理されているOracleデータベースです。使用できるデータベースを検出したあとに、それらのデータベースをリソース グループに追加してデータ保護処理を実行できます。さまざまなタイプとバージョンのOracleデータベースを検出するためにSnapCenterが実行するプロセスを理解しておく必要があります。

|===
| Oracle バージョン 11__g__ から 12__c__R1 の場合 | Oracle バージョン 12__c__R2 から 18__c__ の場合 


 a| 
*RAC データベース*: RAC データベースは、/etc/oratab エントリに基づいてのみ検出されます。

/etc/oratabファイルにデータベース エントリが含まれている必要があります。
 a| 
*RAC データベース*: RAC データベースは、srvctl config コマンドを使用して検出されます。



 a| 
*スタンドアロン*: スタンドアロン データベースは、/etc/oratab エントリに基づいてのみ検出されます。

/etc/oratabファイルにデータベース エントリが含まれている必要があります。
 a| 
*スタンドアロン*: スタンドアロン データベースは、/etc/oratab ファイル内のエントリと srvctl config コマンドの出力に基づいて検出されます。



 a| 
*ASM*: ASM インスタンス エントリは /etc/oratab ファイルで使用可能である必要があります。
 a| 
*ASM*: ASM インスタンス エントリは /etc/oratab ファイルに存在する必要はありません。



 a| 
*RAC One Node*: RAC One Node データベースは、/etc/oratab エントリに基づいてのみ検出されます。

データベースは、_nomount_、_mount_、または _open_ 状態のいずれかである必要があります。/etc/oratabファイルにデータベース エントリが含まれている必要があります。

データベースがすでに検出され、バックアップがデータベースに関連付けられている場合、RAC One Nodeデータベースのステータスは名前変更または削除とマークされます。

データベースを再配置した場合は、次の手順を実行する必要があります。

. フェイルオーバーされたRACノードの/etc/oratabファイルに、再配置されたデータベースのエントリを手動で追加します。
. リソースを手動で更新します。
. リソース ページから RAC One Node データベースを選択し、*データベース設定* をクリックします。
. データベースを設定して、データベースを現在ホストしているRACノードに優先クラスタ ノードを設定します。
. SnapCenterの処理を実行します。



NOTE: あるノードから別のノードにデータベースを再配置したときに、以前のノードのoratabエントリが削除されていない場合は、同じデータベースが2回表示されないように、oratabエントリを手動で削除する必要があります。
 a| 
*RAC One Node*: RAC One Node データベースは、srvctl config コマンドのみを使用して検出されます。

データベースは、_nomount_、_mount_、または _open_ 状態のいずれかである必要があります。データベースがすでに検出され、バックアップがデータベースに関連付けられている場合、RAC One Nodeデータベースのステータスは名前変更または削除とマークされます。

データベースを再配置した場合は、次の手順を実行する必要があります。

. リソースを手動で更新します。
. リソース ページから RAC One Node データベースを選択し、**データベース設定** をクリックします。
. データベースを設定して、データベースを現在ホストしているRACノードに優先クラスタ ノードを設定します。
. SnapCenterの処理を実行します。


|===

NOTE: /etc/oratab ファイルに Oracle 12__c__R2 および 18__c__ データベース エントリがあり、同じデータベースが srvctl config コマンドで登録されている場合、 SnapCenter は重複するデータベース エントリを削除します。古いデータベース エントリがある場合、データベースは検出されますが、データベースは到達不能になり、ステータスはオフラインになります。



== RACセットアップにおける優先ノード

Oracle Real Application Clusters（RAC）セットアップでは、バックアップ処理が実行される優先ノードを指定できます。優先ノードを指定しない場合は、SnapCenterによって自動的に優先ノードが割り当てられ、そのノードにバックアップが作成されます。

優先ノードには、RACデータベース インスタンスが存在するクラスタ ノードを1つまたは複数指定できます。バックアップ処理は、これらの優先ノードで優先順位に従ってトリガーされます。

例: RAC データベース cdbrac には、ノード 1 の cdbrac1、ノード 2 の cdbrac2、ノード 3 の cdbrac3 という 3 つのインスタンスがあります。node1とnode2のインスタンスが優先ノードとして設定され、node2に第1優先順位、node1に第2優先順位が指定されています。バックアップ処理を実行すると、まず第1優先ノードであるnode2で処理が試行されます。node2がバックアップできる状態にない場合（ホストでプラグイン エージェントが実行されていない、ホスト上のデータベース インスタンスが指定したタイプのバックアップを行うのに必要な状態にない、Flex ASM構成のnode2上のデータベース インスタンスがローカルASMインスタンスによって処理されていない、などの複数の原因が考えられます）、node1で処理が試行されます。node3は、優先ノードのリストに含まれていないため、バックアップには使用されません。

Flex ASMセットアップでは、カーディナリティがRACクラスタ内のノード数より少ない場合、リーフ ノードは優先ノードとしてリストされません。Flex ASMクラスタ ノードのロールに変更があった場合は、優先ノードが更新されるように手動で検出する必要があります。



=== 必要なデータベースの状態

バックアップを正常に完了するには、優先ノード上のRACデータベース インスタンスが必要な状態であることが必要です。

* オンライン バックアップを作成する場合は、設定された優先ノードのRACデータベース インスタンスの1つがオープン状態であることが必要です。
* オフライン マウント バックアップを作成する場合は、設定された優先ノードのRACデータベース インスタンスの1つがマウント状態であり、かつ他の優先ノードを含むその他すべてのインスタンスがマウント状態またはそれより低いレベルの状態であることが必要です。
* オフライン シャットダウン バックアップを作成する場合は、RACデータベース インスタンスはどの状態でもかまいませんが、優先ノードを指定する必要があります。




== Oracle Recovery Managerを使用してバックアップをカタログ化する方法

Oracle Recovery Manager（RMAN）でOracleデータベースのバックアップをカタログ化することにより、Oracle RMANリポジトリにバックアップ情報を保存できます。

カタログ化されたバックアップは、あとからブロックレベルのリストア処理や表領域のポイントインタイム リカバリ処理に使用できます。カタログ化されたバックアップが不要となった場合は、カタログ情報を削除できます。

カタログ化するためには、データベースの状態が少なくともマウント済み状態であることが必要です。カタログ化を実行できるのは、データ バックアップ、アーカイブ ログ バックアップ、およびフル バックアップです。複数のデータベースを含むリソース グループのバックアップに対してカタログ化を有効にすると、データベースごとにカタログ化が実行されます。Oracle RACデータベースの場合は、データベースが少なくともマウント済み状態になっている優先ノードでカタログ化が実行されます。


NOTE: RACデータベースのバックアップをカタログ化する場合は、そのデータベースに対して他のジョブが実行されていないことを確認します。別のジョブが実行されている場合は、カタログ化処理がキューに登録されずに失敗します。

デフォルトでは、ターゲット データベースの制御ファイルがカタログ化に使用されます。外部カタログ データベースを追加する場合は、SnapCenterグラフィカル ユーザ インターフェイス（GUI）から[Database Settings]ウィザードを使用して外部カタログのクレデンシャルとTransparent Network Substrate（TNS）名を指定することにより、そのデータベースを設定できます。外部カタログ データベースはCLIから設定することもできます。その場合は、Configure-SmOracleDatabaseコマンドを、-OracleRmanCatalogCredentialNameオプションおよび-OracleRmanCatalogTnsNameオプションとともに実行します。

SnapCenter GUIでOracleバックアップ ポリシーを作成する際にカタログ化オプションを有効にした場合は、バックアップ処理の一環としてOracle RMANを使用してバックアップがカタログ化されます。バックアップのカタログ化を遅らせて実行することもできます。その場合は、Catalog-SmBackupWithOracleRMANコマンドを実行します。バックアップをカタログ化したあとに、Get-SmBackupDetailsコマンドを実行して、カタログ化されたバックアップの情報（カタログ化されたデータファイルのタグ、制御ファイルのカタログ パス、カタログ化されたアーカイブ ログの場所など）を取得できます。

SnapCenter 3.0では、ASMディスク グループ名が16文字以上である場合に、バックアップに対してSC_HASHCODEofDISKGROUP_DBSID_BACKUPIDという命名形式が使用されます。一方、ディスク グループ名が16文字未満である場合は、バックアップに対してDISKGROUPNAME_DBSID_BACKUPIDという命名形式が使用されます。これはSnapCenter 2.0で使用される形式と同じです。


NOTE: HASHCODEofDISKGROUPは自動生成される2～10桁の番号で、各ASMディスク グループに固有です。

バックアップに関するRMANリポジトリ情報が古くなってバックアップのリポジトリ レコードがその物理ステータスと一致しなくなった場合は、クロスチェックを実行してリポジトリ情報を更新できます。たとえば、ユーザがオペレーティング システム コマンドでディスクからアーカイブ ログを削除した場合、実際にはディスクにログがないにもかかわらず、制御ファイルにはディスクにログがあることが示されます。クロスチェック処理では、制御ファイルの情報を更新できます。クロスチェックを有効にするには、Set-SmConfigSettingsコマンドを実行し、ENABLE_CROSSCHECKパラメータにTRUEを割り当てます。デフォルト値はFALSEです。

`sccli Set-SmConfigSettings-ConfigSettingsTypePlugin-PluginCodeSCO-ConfigSettings "KEY=ENABLE_CROSSCHECK, VALUE=TRUE"`

カタログ情報を削除するには、Uncatalog-SmBackupWithOracleRMANコマンドを実行します。SnapCenter GUIではカタログ情報を削除できません。ただし、バックアップを削除するとき、またはカタログ化されたバックアップに関連する保持設定とリソース グループを削除するときに、カタログ化されたバックアップの情報も削除されます。


NOTE: SnapCenterホストを強制的に削除する場合は、そのホストに関連するカタログ化されたバックアップの情報が削除されません。ホストを強制的に削除する場合は、事前にそのホストに関連するすべてのカタログ化されたバックアップの情報を削除しておく必要があります。

処理時間がORACLE_PLUGIN_RMAN_CATALOG_TIMEOUTパラメータに指定されたタイムアウト値を超えたためにカタログ化やカタログ化解除が失敗した場合は、次のコマンドを実行してパラメータの値を変更する必要があります。

`/opt/Netapp/snapcenter/spl/bin/sccli Set-SmConfigSettings-ConfigSettingsType Plugin -PluginCode SCO-ConfigSettings "KEY=ORACLE_PLUGIN_RMAN_CATALOG_TIMEOUT,VALUE=user_defined_value"`

パラメータの値を変更したら、次のコマンドを実行してSnapCenter Plug-in Loader（SPL）サービスを再起動します。

`/opt/NetApp/snapcenter/spl/bin/spl restart`

コマンドで使用できるパラメータとその説明は、Get-Help command_nameを実行して確認できます。あるいは、 https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenterソフトウェア コマンド リファレンス ガイド"^] 。



== バックアップ スケジュール

バックアップ頻度（スケジュール タイプ）はポリシーで指定され、バックアップ スケジュールはリソース グループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは1時間ごとにバックアップする必要がありますが、ほとんど使用されないリソースは1日に1回バックアップすれば十分です。その他の要因としては、組織におけるリソースの重要性、サービス レベル アグリーメント（SLA）、目標復旧時点（RPO）などがあります。

SLAは、求められるサービス レベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対応を定義したものです。RPOは、障害発生後に通常処理を再開するためにバックアップ ストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLAとRPOはデータ保護戦略に関わる要件です。

使用頻度の高いリソースであっても、フル バックアップは1日に1～2回で十分です。たとえば、定期的なトランザクション ログ バックアップを実行すれば、必要なバックアップが作成されます。データベースを頻繁にバックアップするほど、 SnapCenterが復元時に使用するトランザクション ログが少なくなり、復元操作が高速化されます。

バックアップ スケジュールには、次の2つの要素があります。

* バックアップ頻度
+
バックアップ頻度 (バックアップを実行する頻度) は、一部のプラグインでは _スケジュール タイプ_ と呼ばれ、ポリシー構成の一部です。ポリシーでは、バックアップ頻度として、毎時、毎日、毎週、または毎月を選択できます。頻度を選択しなかった場合は、オンデマンドのみのポリシーが作成されます。  *設定* > *ポリシー* をクリックすると、ポリシーにアクセスできます。

* バックアップ スケジュール
+
バックアップ スケジュール（バックアップが実行される日時）は、リソース グループ設定の一部です。たとえば、週次バックアップのポリシーが構成されたリソース グループがある場合は、毎週木曜日の午後 10 時にバックアップするようにスケジュールを構成できます。  *リソース* > *リソース グループ* をクリックすると、リソース グループのスケジュールにアクセスできます。





== バックアップの命名規則

Snapshotのデフォルトの命名規則を使用するか、カスタマイズした命名規則を使用できます。デフォルトのバックアップ命名規則ではSnapshot名にタイムスタンプが追加されるので、コピーが作成されたタイミングを特定できます。

Snapshotでは、次のデフォルトの命名規則が使用されます。

`resourcegroupname_hostname_timestamp`

バックアップ リソース グループには、次の例のように論理的な名前を付ける必要があります。

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
この例では、各構文要素に次の意味があります。

* _dts1_ はリソース グループ名です。
* _mach1x88_ はホスト名です。
* _03-12-2015_23.17.26_ は日付とタイムスタンプです。


または、[スナップショット コピーにカスタム名形式を使用する] を選択して、リソースまたはリソース グループを保護しながらスナップショット名の形式を指定することもできます。たとえば、customtext_resourcegroup_policy_hostnameやresourcegroup_hostnameなどの形式です。デフォルトでは、Snapshot名にタイムスタンプのサフィックスが追加されます。



== バックアップ保持オプション

バックアップ コピーを保持する日数を選択するか、または保持するバックアップ コピーの数（ONTAPでは最大255個のコピー）を指定することができます。たとえば、組織の必要に応じて、10日分のバックアップ コピーや130個のバックアップ コピーを保持できます。

ポリシーを作成する際に、バックアップ タイプおよびスケジュール タイプの保持オプションを指定できます。

SnapMirrorレプリケーションを設定すると、デスティネーション ボリュームに保持ポリシーがミラーリングされます。

SnapCenter は、スケジュール タイプに一致する保持ラベルを持つ保持されたバックアップを削除します。リソースまたはリソース グループに対してスケジュール タイプが変更されると、古いスケジュール タイプ ラベルのバックアップがシステムに残ることがあります。


NOTE: バックアップ コピーを長期にわたって保持する場合は、SnapVaultバックアップを使用する必要があります。



== プライマリ ストレージ ボリュームまたはセカンダリ ストレージ ボリュームを使用したバックアップ コピーの検証

プライマリ ストレージ ボリュームまたはSnapMirror / SnapVaultセカンダリ ストレージ ボリュームでバックアップ コピーを検証することができます。セカンダリ ストレージ ボリュームを使用して検証を行うと、プライマリ ストレージ ボリュームの負荷が軽減されます。

プライマリ ストレージ ボリュームまたはセカンダリ ストレージ ボリュームにあるバックアップを検証すると、すべてのプライマリSnapshotとセカンダリSnapshotが検証済みとマークされます。

SnapMirrorおよびSnapVaultセカンダリ ストレージ ボリューム上のバックアップ コピーを検証するには、SnapRestoreのライセンスが必要です。
