---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: 「Refresh-SmClone」コマンドを実行してクローンを更新できます。このコマンドを実行すると、データベースのバックアップが作成され、既存のクローンは削除され、同じ名前のクローンが作成されます。 
---
= クローンの更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_Refresh-SmClone_ コマンドを実行してクローンを更新できます。このコマンドを実行すると、データベースのバックアップが作成され、既存のクローンは削除され、同じ名前のクローンが作成されます。


NOTE: PDBクローンは更新できません。

*必要なもの*

* スケジュールされたバックアップを有効にしないで、オンライン フル バックアップまたはオフライン データ バックアップ ポリシーを作成します。
* ポリシーで、バックアップが失敗した場合に限り、Eメール通知を設定します。
* 不要なバックアップがなくなるように、オンデマンド バックアップの保持数を適切に定義します。
* クローン更新処理用に指定したリソース グループには、オンライン フル バックアップまたはオフライン データ バックアップ ポリシーのみが関連付けられていることを確認します。
* データベースが1つだけのリソース グループを作成します。
* クローン更新コマンド用にcronジョブを作成する場合は、データベース リソース グループでSnapCenterスケジュールとcronスケジュールが重なっていないことを確認します。
+
クローン更新コマンド用に作成したcronジョブでは、必ず24時間ごとにOpen-SmConnectionを実行します。

* クローンSIDがホストで一意であることを確認します。
+
複数のクローン更新処理で同じクローン仕様ファイルを使用する場合、または同じクローンSIDを指定してクローン仕様ファイルを使用する場合は、ホスト上でそのSIDを持つ既存のクローンが削除され、クローンが作成されます。

* バックアップ ポリシーがセカンダリ保護で有効になっていること、およびセカンダリ バックアップを使用してクローンを作成するために、クローン仕様ファイルが "`-IncludeSecondaryDetails`" を使用して作成されていることを確認します。
+
** プライマリ クローン仕様ファイルが指定されているが、ポリシーでセカンダリ更新オプションが選択されている場合は、バックアップが作成され、更新がセカンダリに転送されます。ただし、クローンはプライマリ バックアップから作成されます。
** プライマリ クローン仕様ファイルが指定され、ポリシーでセカンダリ更新オプションが選択されていない場合、バックアップはプライマリ上に作成され、クローンはプライマリから作成されます。




*手順*

. 指定されたユーザーのSnapCenter Server との接続セッションを開始します: _Open-SmConnection_
. 指定されたバックアップから Oracle データベース クローン仕様を作成します: _New-SmOracleCloneSpecification_
+

NOTE: セカンダリ データ保護ポリシーが、統合されたmirror-vaultである場合は、-IncludeSecondaryDetailsのみを指定します。-SecondaryStorageTypeを指定する必要はありません。

+
このコマンドによって、指定のソース データベースとそのバックアップに対して、Oracleデータベースのクローン仕様ファイルが自動的に作成されます。作成するクローン データベースに対して自動的に生成される値がこの仕様ファイルに取り込まれるようにするために、クローン データベースのSIDも指定する必要があります。

+

NOTE: クローン仕様ファイルは、_/var/opt/snapcenter/sco/clone_specs_ に作成されます。

. _Refresh-SmClone_ を実行します。
+
「PL-SCO-20032: canExecute 操作がエラーで失敗しました: PL-SCO-30031: Redo ログ ファイル +SC_2959770772_clmdb/clmdb/redolog/redo01_01.log が存在します」というエラー メッセージが表示されて操作が失敗する場合は、_-WaitToTriggerClone_ に高い値を指定します。

+
UNIXコマンドの詳細については、 https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["SnapCenterソフトウェア コマンド リファレンス ガイド"^] 。


