---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: データベースのリストアとリカバリを行う前に戦略を定義しておくと、リストア処理とリカバリ処理を正常に実行できるようになります。 
---
= Oracleデータベースのリストアおよびリカバリ戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースのリストアとリカバリを行う前に戦略を定義しておくと、リストア処理とリカバリ処理を正常に実行できるようになります。



== リストア処理とリカバリ処理でサポートされるバックアップのタイプ

SnapCenterでは、さまざまなタイプのOracleデータベース バックアップのリストアとリカバリがサポートされます。

* オンライン データ バックアップ
* オフライン シャットダウン データ バックアップ
* オフライン マウント データ バックアップ
+

NOTE: オフライン シャットダウンまたはオフライン マウント データ バックアップをリストアする場合、SnapCenterはデータベースをオフライン状態のままにします。データベースを手動でリカバリし、ログをリセットする必要があります。

* フル バックアップ
* Data Guardスタンバイ データベースのオフライン マウント バックアップ
* Active Data Guardスタンバイ データベースのデータのみのオンライン バックアップ
+

NOTE: Active Data Guardスタンバイ データベースのリカバリは実行できません。

* Real Application Clusters（RAC）構成でのオンライン データ バックアップ、オンライン フル バックアップ、オフライン マウント バックアップ、オフライン シャットダウン バックアップ
* Automatic Storage Management（ASM）構成でのオンライン データ バックアップ、オンライン フル バックアップ、オフライン マウント バックアップ、オフライン シャットダウン バックアップ




== Oracleデータベースでサポートされるリストア方式のタイプ

SnapCenterでは、Oracleデータベースに対してConnect and CopyリストアとIn Placeリストアがサポートされます。SnapCenterは、リストア処理時に、リストアに使用されるファイルシステムでデータ損失が生じないようにするための適切なリストア方式を決定します。


NOTE: SnapCenterでは、ボリュームベースのSnapRestoreはサポートされません。



=== Connect and Copyリストア

データベース レイアウトがバックアップと異なる場合や、バックアップ作成後にファイルが追加された場合は、Connect and Copyリストアが実行されます。Connect and Copyリストア方式では、次のタスクが実行されます。

*手順*

. Snapshotからボリュームがクローニングされ、クローニングされたLUNまたはボリュームを使用してホスト上にファイルシステム スタックが構築されます。
. クローニングされたファイルシステムから元のファイルシステムにファイルがコピーされます。
. クローニングされたファイルシステムがホストからアンマウントされ、クローニングされたボリュームがONTAPから削除されます。



NOTE: Flex ASMセットアップ（RACクラスタ内のノード数よりもカーディナリティが少ない）またはVMDKかRDM上のASM RACデータベースでは、Connect and Copyリストア方式のみがサポートされます。

In Placeリストアを強制的に有効にした場合でも、次のシナリオではSnapCenterがConnect and Copyリストアを実行します。

* セカンダリストレージシステムからの復元
* データベース インスタンスが設定されていないOracle RACセットアップのノードに存在するASMディスク グループをリストアする場合
* Oracle RACセットアップで、いずれかのピア ノードでASMインスタンスまたはクラスタ インスタンスが実行されていない場合、またはピア ノード自体が停止している場合
* 制御ファイルのみをリストアする場合
* ASMディスク グループに存在する表領域の一部をリストアする場合
* ディスク グループがデータ ファイル、spファイル、パスワード ファイルの間で共有されている場合
* RAC環境のリモート ノードで、SnapCenter Plug-in Loader（SPL）サービスがインストールされていないか実行されていない場合
* Oracle RACに新たに追加されたノードがSnapCenter Serverで認識されていない場合




=== In Placeリストア

データベース レイアウトがバックアップとほぼ同じであり、かつストレージとデータベース スタックで設定変更が行われていない場合は、In Placeリストアが実行されて、ファイルまたはLUNのリストアがONTAP上で実行されます。SnapCenterでは、In Placeリストア方式の一環としてSingle File SnapRestore（SFSR）のみがサポートされます。


NOTE: NetApp ONTAP は、セカンダリ ロケーションからのインプレース リストアをサポートします。

データベースでIn Placeリストアを実行する場合は、ASMディスク グループにデータファイルだけがあることを確認してください。ASMディスク グループまたはデータベースの物理構造に変更を加えた場合は、バックアップを作成する必要があります。In Placeリストアを実行すると、ディスク グループにバックアップ時と同じ数のデータファイルが格納されます。

ディスク グループまたはマウント ポイントが次の基準と一致する場合は、In Placeリストアが自動的に適用されます。

* バックアップ後に新しいデータファイルが追加されていない（外部ファイル チェック）
* バックアップ後にASMディスクまたはLUNの追加、削除、または再作成が行われていない（ASMディスク グループの構造変更チェック）
* LVMディスク グループに対してLUNの追加、削除、または再作成が行われていない（LVMディスク グループの構造変更チェック）



NOTE: In Placeリストアを強制的に有効にすることもできます。有効にするには、GUI、SnapCenter CLI、またはPowerShellコマンドレットを使用して、外部ファイル チェックおよびLVMディスク グループの構造変更チェックを無効にします。



==== ASM RACでのIn Placeリストアの実行

SnapCenterでは、リストアを実行するノードがプライマリ ノードと呼ばれ、ASMディスク グループがあるRAC上のその他すべてのノードがピア ノードと呼ばれます。SnapCenterは、ストレージ リストア処理を実行する前に、ASMディスク グループがマウント状態にあるすべてのノードで、ディスマウントするASMディスク グループの状態を変更します。ストレージのリストアが完了すると、SnapCenterはASMディスク グループの状態をリストア処理前の状態に変更します。

SAN環境では、ストレージ リストア処理の前に、SnapCenterがすべてのピア ノードからデバイスを削除し、LUNのマッピング解除処理を実行します。ストレージ リストア処理が完了すると、SnapCenterはLUNマッピング処理を実行し、すべてのピア ノードでデバイスを構築します。SAN環境のLUN上にOracle RAC ASMレイアウトが存在する場合は、リストア中に、ASMディスク グループが存在するRACクラスタのすべてのノードでSnapCenterがLUNのマッピング解除、LUNのリストア、およびLUNのマッピングを実行します。リストア前にRACノードのすべてのイニシエータがLUNに使用されていなかった場合でも、リストア後はSnapCenterがすべてのRACノードのすべてのイニシエータを含む新しいigroupを作成します。

* ピア ノードでリストア前の処理中にエラーが発生した場合は、リストア前の処理が成功したピア ノードでSnapCenterが自動的にASMディスク グループの状態をリストア実行前の状態にロールバックします。プライマリ ノードおよび処理が失敗したピア ノードでは、ロールバックがサポートされません。新たなリストアを実行する前に、ピア ノードの問題を手動で修正し、プライマリ ノード上のASMディスク グループをマウント状態に戻す必要があります。
* リストア処理中にエラーが発生した場合は、リストア処理が失敗し、ロールバックは実行されません。新たなリストアを実行する前に、ストレージ リストアの問題を手動で修正し、プライマリ ノード上のASMディスク グループをマウント状態に戻す必要があります。
* いずれかのピア ノードでリストア後の処理中にエラーが発生した場合、SnapCenterは他のピア ノードでリストア処理を続行します。このピア ノードでリストア後の問題を手動で修正する必要があります。




== Oracleデータベースでサポートされるリストア処理のタイプ

SnapCenterでは、Oracleデータベースに対してさまざまなタイプのリストア処理を実行できます。

データベースをリストアする前に、バックアップが検証されて、実際のデータベース ファイルと比較して足りないファイルがないかどうかが確認されます。



=== フル リストア

* データファイルのみをリストア
* 制御ファイルのみをリストア
* データファイルと制御ファイルをリストア
* Data GuardスタンバイとActive Data Guardスタンバイ データベースのデータファイル、制御ファイル、およびRedoログ ファイルをリストア




=== パーシャル リストア

* 選択した表領域のみをリストア
* 選択したPluggable Database（PDB）のみをリストア
* 1つのPDBの選択した表領域のみをリストア




== Oracleデータベースでサポートされるリカバリ処理のタイプ

SnapCenterでは、Oracleデータベースに対してさまざまなタイプのリカバリ処理を実行できます。

* 最後のトランザクションまで（すべてのログ）のデータベース
* 特定のSystem Change Number（SCN）までのデータベース
* 特定の日時までのデータベース
+
リカバリの日時は、データベース ホストのタイムゾーンに基づいて指定する必要があります。

+
SnapCenterでは、Oracleデータベースに対して[No recovery]オプションも用意しています。




NOTE: スタンバイとしてのデータベース ロールで作成されたバックアップを使用してリストアを行った場合、Plug-in for Oracle Databaseではリカバリがサポートされません。物理スタンバイ データベースは、常に手動でリカバリする必要があります。



== Oracleデータベースのリストアとリカバリに関する制限事項

リストア処理とリカバリ処理を実行する前に、制限事項を確認しておく必要があります。

Oracle の 11.2.0.4 から 12.1.0.1 までのバージョンを使用している場合、_renamedg_ コマンドを実行すると、復元操作がハング状態になります。この問題を修正するには、Oracleパッチ19544733を適用します。

次のリストア処理とリカバリ処理はサポートされていません。

* ルート コンテナ データベース（CDB）の表領域のリストアとリカバリ
* 一時表領域およびPDBに関連付けられた一時表領域のリストア
* 複数のPDBから同時に行う表領域のリストアとリカバリ
* ログ バックアップのリストア
* 別の場所へのバックアップのリストア
* Data GuardスタンバイまたはActive Data Guardスタンバイ データベース以外の構成でのRedoログ ファイルのリストア
* SPFILEおよびパスワード ファイルのリストア
* 同じホスト上に既存のデータベース名を使用して再作成され、SnapCenterで管理されていて、有効なバックアップがあるデータベースに対してリストア処理を実行すると、DBIDが異なる場合でも、新しく作成されたデータベース ファイルが上書きされます。
+
これを回避するには、次のいずれかの操作を実行します。

+
** データベースが再作成された後にSnapCenterリソースを検出する
** 再作成したデータベースのバックアップを作成する






== 表領域のポイントインタイム リカバリに関する制限事項

* SYSTEM、SYSAUX、およびUNDO表領域のポイントインタイム リカバリ（PITR）はサポートされていない
* 表領域のPITRを他のタイプのリストアと一緒に実行することはできない
* 名前が変更された表領域を、名前を変更する前の状態に戻す場合は、表領域の以前の名前を指定する必要がある
* ある表領域の表に対する制約が別の表領域に含まれている場合は、両方の表領域をリカバリする必要がある
* 表とそのインデックスが異なる表領域に格納されている場合は、PITRを実行する前にインデックスを削除する必要がある
* PITRを使用して、現在のデフォルト表領域をリカバリすることはできない
* 次のいずれかのオブジェクトを含む表領域は、PITRを使用してリカバリすることはできない：
+
** 基礎となるオブジェクト（マテリアライズド・ビューなど）または含まれるオブジェクト（パーティション表など）を持つオブジェクト（ただし、基礎となるオブジェクトまたは含まれるオブジェクトのすべてがリカバリ・セットに含まれていない場合）
+
また、パーティション表のパーティションが異なる表領域に格納されている場合は、PITRを実行する前に表を削除するか、PITRを実行する前にすべてのパーティションを同じ表領域に移動する必要があります。

** セグメントを元に戻すまたはロールバックする
** 複数の受信者を持つ Oracle 8 互換の高度なキュー
** SYSユーザーが所有するオブジェクト
+
これらのタイプのオブジェクトの例としては、PL/SQL、Javaクラス、呼び出しプログラム、ビュー、シノニム、ユーザ、特権、ディメンション、ディレクトリ、シーケンスがあります。







== Oracleデータベースのリストア処理のソースとデスティネーション

プライマリ ストレージまたはセカンダリ ストレージにあるバックアップ コピーからOracleデータベースをリストアすることができます。データベースは、同じデータベース インスタンスの同じ場所にしかリストアできません。ただし、Real Application Cluster（RAC）セットアップでは、データベースを他のノードにリストアできます。



=== リストア処理のソース

プライマリ ストレージまたはセカンダリ ストレージ上のバックアップからデータベースをリストアすることができます。複数ミラー構成でセカンダリ ストレージ上のバックアップからリストアする場合は、セカンダリ ストレージ ミラーをソースとして選択できます。



=== リストア処理のデスティネーション

データベースは、同じデータベース インスタンスの同じ場所にしかリストアできません。

RACセットアップでは、クラスタ内の任意のノードからRACデータベースをリストアできます。
