---
permalink: protect-sco/task_define_a_clone_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, cloning type, clone name, limitations 
summary: データベースをクローニングする前に戦略を定義しておくと、クローニング処理を確実に成功させることができます。 
---
= Oracleデータベースのクローニング戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データベースをクローニングする前に戦略を定義しておくと、クローニング処理を確実に成功させることができます。



== クローニングでサポートされるバックアップのタイプ

SnapCenterでは、Oracleデータベースの各種バックアップのクローニングがサポートされます。

* オンライン データ バックアップ
* オンライン フル バックアップ
* オフライン マウント バックアップ
* オフライン シャットダウン バックアップ
* Data Guardスタンバイ データベースおよびActive Data Guardスタンバイ データベースのバックアップ
* Real Application Clusters（RAC）構成でのオンライン データ バックアップ、オンライン フル バックアップ、オフライン マウント バックアップ、オフライン シャットダウン バックアップ
* Automatic Storage Management（ASM）構成でのオンライン データ バックアップ、オンライン フル バックアップ、オフライン マウント バックアップ、オフライン シャットダウン バックアップ
+

IMPORTANT: マルチパス構成ファイルのuser_friendly_namesオプションがyesに設定されている場合、SAN構成はサポートされません。




NOTE: アーカイブ ログ バックアップのクローニングはサポートされていません。



== Oracleデータベースでサポートされるクローニングのタイプ

Oracle データベース環境では、 SnapCenter はデータベース バックアップのクローン作成をサポートします。バックアップのクローニングは、プライマリ ストレージ システムおよびセカンダリ ストレージ システムから行うことができます。

SnapCenter Server は、 NetApp FlexCloneテクノロジーを使用してバックアップを複製します。

クローンを更新するには、「Refresh-SmClone」コマンドを実行します。このコマンドを実行すると、データベースのバックアップが作成され、既存のクローンは削除され、同じ名前のクローンが作成されます。


NOTE: クローンの更新処理は、UNIXコマンドを使わないと実行できません。



== Oracleデータベースのクローンの命名規則

SnapCenter 3.0 以降、ファイル システムのクローンに対して使用される命名規則は、ASM ディスク グループのクローンに対して使用される命名規則とは異なります。

* SANファイルシステムまたはNFSファイルシステムの命名規則は、FileSystemNameofsourcedatabase_CLONESIDです。
* ASMディスク グループの命名規則は、SC_HASHCODEofDISKGROUP_CLONESIDです。
+
HASHCODEofDISKGROUPは、自動生成される2～10桁の数値で、各ASMディスク グループに固有です。





== Oracleデータベースのクローニングに関する制限事項

データベースをクローニングする前に、クローニング処理の制限事項を確認しておく必要があります。

* Oracle の 11.2.0.4 から 12.1.0.1 までのバージョンを使用している場合、_renamedg_ コマンドを実行するとクローン操作がハング状態になります。この問題を修正するには、Oracleパッチ19544733を適用します。
* （WindowsホストでMicrosoft iSCSIイニシエータを使用するなどして）ホストに直接接続されているLUNから、同じWindowsホスト上のVMDKかRDM LUN、または別のWindowsホストにデータベースをクローニングすることはできません。その逆も同様です。
* ボリューム マウント ポイントのルート ディレクトリを共有ディレクトリにすることはできません。
* クローンを含むLUNを新しいボリュームに移動すると、そのクローンは削除できなくなります。

