---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html 
sidebar: sidebar 
keywords:  
summary: コピーの破損時など、レプリカ コピーを再シードする必要がある場合は、SnapCenterの再シード機能を使用して最新のバックアップに再シードできます。 
---
= Exchangeのパッシブ ノード レプリカの再シード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コピーの破損時など、レプリカ コピーを再シードする必要がある場合は、SnapCenterの再シード機能を使用して最新のバックアップに再シードできます。

.開始する前に
再シードするデータベースのバックアップを作成しておく必要があります。

+ ノード間の遅延を回避するには、再シード操作を実行する前に新しいバックアップを作成するか、最新のバックアップを持つホストを選択します。

.手順
. 左側のナビゲーション ウィンドウで、[*リソース*] をクリックし、リストから [*Microsoft Exchange Server プラグイン*] を選択します。
. [Resources]ページで、[View]リストから適切なオプションを選択します。
+
|===
| オプション | 説明 


 a| 
単一のデータベースを再シードする
 a| 
表示リストから*データベース*を選択します。



 a| 
DAG内のデータベースを再シードする
 a| 
表示リストから*データベース可用性グループ*を選択します。

|===
. 再シードするリソースを選択します。
. 「コピーの管理」ページで、「再シード」をクリックします。
. 再シード ウィザードの正常でないデータベース コピーのリストから、再シードするものを選択し、[次へ] をクリックします。
. ホスト ウィンドウで、再シードするバックアップがあるホストを選択し、[次へ] をクリックします。
. 通知ページの *電子メール設定* ドロップダウン リストから、電子メールを送信するシナリオを選択します。
+
また、送信者と受信者のEメール アドレス、およびEメールの件名を指定する必要があります。

. 概要を確認し、[完了] をクリックします。
. ページ下部の[Activity]パネルを展開すると、ジョブのステータスを表示できます。
+

NOTE: パッシブ データベース コピーが他社ストレージにある場合、再シード処理はサポートされません。


