---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenterは、クレデンシャルを使用してSnapCenterの処理を実行するユーザを認証します。プラグイン パッケージのインストールに使用するクレデンシャルと、データベースでのデータ保護処理に使用するクレデンシャルをそれぞれ作成する必要があります。 
---
= SnapCenter Plug-in for Windowsのクレデンシャルの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterは、クレデンシャルを使用してSnapCenterの処理を実行するユーザを認証します。プラグイン パッケージのインストールに使用するクレデンシャルと、データベースでのデータ保護処理に使用するクレデンシャルをそれぞれ作成する必要があります。

.タスク概要
Windowsホストにプラグインをインストールするには、クレデンシャルを設定する必要があります。Windowsのクレデンシャルは、ホストを導入してプラグインをインストールしたあとに作成することも可能ですが、SVMを追加したあと、ホストの導入とプラグインのインストールを開始する前に作成することを推奨します。

このクレデンシャルには、管理者権限（リモート ホストに対する管理者権限を含む）を設定します。

個々のリソース グループのクレデンシャルを設定する場合で、ユーザ名に完全なadmin権限が割り当てられていない場合は、少なくともリソース グループとバックアップの権限を割り当てる必要があります。

.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*資格情報*]をクリックします。
. *新規*をクリックします。
+
[Credential]ウィンドウが表示されます。

. [Credential]ページで次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
資格情報名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザー名
 a| 
認証に使用するユーザ名を入力します。

** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者またはSnapCenterプラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。ユーザ名フィールドの有効な形式は次のとおりです。

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** ローカル管理者（ワークグループの場合のみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。ユーザー名フィールドの有効な形式は次のとおりです。 `UserName`





 a| 
パスワード
 a| 
認証に使用するパスワードを入力します。



 a| 
認証
 a| 
認証モードとして[Windows]を選択します。

|===
. [OK]をクリックします。

