---
permalink: protect-sce/task_define_a_restore_strategy_for_exchange_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Exchange Serverのリストア戦略を定義しておくと、その定義に従ってデータベースを実行することができます。 
---
= Exchangeデータベースのリストア戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exchange Serverのリストア戦略を定義しておくと、その定義に従ってデータベースを実行することができます。



== Exchange Serverでのリストア処理のソース

プライマリ ストレージにあるバックアップ コピーからExchange Serverデータベースをリストアすることができます。

データベースはプライマリ ストレージからのみリストアできます。



== Exchange Serverでサポートされるリストア処理のタイプ

SnapCenterを使用して、Exchangeのリソースに対してさまざまなタイプのリストア処理を実行できます。

* 最新の状態へのリストア
* 過去のある時点（ポイントインタイム）へのリストア




=== 最新の状態へのリストア

最新の状態へのリストア処理では、障害発生時点までデータベースがリカバリされます。SnapCenterでは、この処理が次の順序で実行されます。

. 選択したフル データベース バックアップからデータベースがリストアされます。
. バックアップされたすべてのトランザクション ログと、最新のバックアップ以降に作成された新しいログが適用されます。
+
トランザクション ログは再生されて選択したすべてのデータベースに適用されます。

+
リストアの完了後、Exchangeにより新しいログ チェーンが作成されます。

+
|===


| *ベスト プラクティス:* 復元が完了したら、新しい完全バックアップとログ バックアップを実行することをお勧めします。 
|===
+
最新の状態へのリストア処理を実行するには、連続したトランザクション ログ セットが必要です。

+
最新の状態へのリストアを実行すると、リストアに使用したバックアップは、ポイントインタイム リストア処理にしか使用できなくなります。

+
すべてのバックアップに最新の状態へのリストア機能を使用する必要がない場合は、バックアップ ポリシーを使用してシステムのトランザクション ログ バックアップ保持を設定できます。





=== 過去のある時点（ポイントインタイム）へのリストア

ポイントインタイム リストア処理では、データベースが過去の特定の時点にリストアされます。ポイントインタイム リストア処理は次の状況で発生します。

* バックアップ トランザクション ログの所定の時点までデータベースがリストアされた。
* データベースがリストアされ、一部のバックアップ トランザクション ログだけが適用された。

