---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenterを使用してMicrosoft Exchange Serverリソースをバックアップする前に、Exchangeリソースまたはリソース グループのバックアップ ポリシーを作成することができます。また、リソース グループの作成時や単一のリソースのバックアップ時にバックアップ ポリシーを作成することも可能です。 
---
= Exchange Serverデータベースのバックアップ ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してMicrosoft Exchange Serverリソースをバックアップする前に、Exchangeリソースまたはリソース グループのバックアップ ポリシーを作成することができます。また、リソース グループの作成時や単一のリソースのバックアップ時にバックアップ ポリシーを作成することも可能です。

.開始する前に
* データ保護戦略を定義しておく必要があります。
+
詳細については、Exchangeデータベースのデータ保護戦略の定義に関する説明を参照してください。

* SnapCenterのインストール、ホストの追加、リソースの特定、ストレージ システム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* Exchange Serverリソースを更新（検出）しておく必要があります。
* Snapshotをミラーまたはバックアップにレプリケートするユーザには、SnapCenter管理者がユーザに対してソースとデスティネーションの両方のボリューム用にStorage Virtual Machine（SVM）を割り当てておく必要があります。
* PowerShellスクリプトをプレスクリプトとポストスクリプトで実行したい場合は、 `usePowershellProcessforScripts`パラメータをtrueに設定する `web.config`ファイル。
+
デフォルト値はfalseです。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"] 。


.タスク概要
* バックアップ ポリシーとは、バックアップを管理および保持する方法やリソースやリソース グループをバックアップする頻度を定めた一連のルールです。また、スクリプト設定を指定することもできます。ポリシーでオプションを指定しておくことで、別のリソース グループにポリシーを再利用して時間を節約することができます。
* フル バックアップの保持設定は、ポリシーごとに固有です。フル バックアップの保持数が4のポリシーAを使用するデータベースやリソースでは4つのフル バックアップが保持され、同じデータベースやリソースのポリシーBには影響しません。ポリシーBの保持数が3であれば、ポリシーBを使用すると3つのフル バックアップが保持されます。
* ログ バックアップの保持設定はポリシーの違いを超えて影響を及ぼし、データベースやリソースのすべてのログ バックアップに適用されます。したがって、ポリシーBを使用してフル バックアップを実行すると、そのログ保持設定は、同じデータベースやリソースの、ポリシーAで作成されたログ バックアップに影響します。同様に、ポリシーAのログ保持設定は、同じデータベースの、ポリシーBで作成されたログ バックアップに影響します。
* SCRIPTS_PATHは、プラグイン ホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、API を介して Swagger から表示できます: API /4.7/configsettings

+
GET APIを使用すると、キーの値を表示できます。SET APIはサポートされません。

+
|===


| *ベスト プラクティス:* 保持する完全バックアップとログ バックアップの総数に基づいて、セカンダリ保持ポリシーを構成することをお勧めします。セカンダリ保持ポリシーについては、データベースとログが異なるボリュームにある場合はそれぞれのバックアップに3つのSnapshotを保持でき、データベースとログが同じボリュームにある場合はそれぞれのバックアップに2つのSnapshotを保持できることを念頭に置いて設定してください。 
|===
* SnapLock
+
** [Retain the backup copies for a specific number of days]オプションを選択した場合は、SnapLockの保持期間をここで指定した保持日数以下にする必要があります。
+
Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、ポリシーで指定した数よりも多くのSnapshotが保持される可能性があります。

+
ONTAP 9.12.1以前のバージョンでは、SnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。





.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. *新規*をクリックします。
. 「名前」ページで、ポリシー名と詳細を入力します。
. 「バックアップ タイプとレプリケーション」ページで、次の手順を実行します。
+
.. バックアップ タイプを選択します。
+
|===
| 状況 | 操作 


 a| 
データベース ファイルと必要なトランザクション ログをバックアップ
 a| 
*完全バックアップとログバックアップ*を選択します。

データベースはログを切り捨てるかたちでバックアップされ、切り捨てられたログを含むすべてのログがバックアップされます。


NOTE: これは推奨されるバックアップ タイプです。



 a| 
データベース ファイルとコミットされていないトランザクション ログをバックアップ
 a| 
*完全バックアップ*を選択します。

データベースはログを切り捨てるかたちでバックアップされ、切り捨てられたログはバックアップされません。



 a| 
すべてのトランザクション ログをバックアップ
 a| 
*ログバックアップ*を選択します。

アクティブ ファイルシステム上のすべてのトランザクション ログがバックアップされ、ログの切り捨ては行われません。

ライブ ログと同じディスクに _scebackupinfo_ ディレクトリが作成されます。このディレクトリには、Exchangeデータベースの変更内容の差分へのポインタが格納されており、完全なログ ファイルとは異なります。



 a| 
トランザクション ログ ファイルの切り捨てなしで、すべてのデータベース ファイルとトランザクション ログをバックアップ
 a| 
*バックアップのコピー*を選択します。

すべてのデータベースとすべてのログがバックアップされ、ログの切り捨ては行われません。通常このタイプのバックアップは、レプリカの再シードのほか、問題のテストや診断のために使用します。

|===
+

NOTE: ログ バックアップに必要なスペースは、最新の状態（UTM）保持設定ではなく、フル バックアップ保持設定に基づいて定義する必要があります。

+

NOTE: Exchangeボリューム（LUN）を扱う場合は、ログとデータベースに個別のバックアップ ポリシーを作成して、同じラベルを使用し、ラベルごとにログ ポリシーのkeep（保持）の値をデータベース ポリシーの値の2倍に設定します。詳細については、 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["SnapCenter for Exchange バックアップは、Vault の宛先ログボリュームにスナップショットの半分のみを保存します。"^]

.. [Database Availability Group Settings]セクションで、操作を選択します。
+
|===
| フィールド | 操作 


 a| 
アクティブコピーをバックアップする
 a| 
選択したデータベースのアクティブ コピーのみをバックアップする場合は、このオプションを選択します。

データベース可用性グループ（DAG）については、DAG内のすべてのデータベースのアクティブ コピーのみがバックアップされます。

パッシブ コピーはバックアップされません。



 a| 
Back up copies on servers to be selected at backup job creation time
 a| 
選択したサーバ上のデータベースのコピー（アクティブとパッシブの両方）をバックアップする場合は、このオプションを選択します。

DAGについては、選択したサーバ上のすべてのデータベースのアクティブ コピーとパッシブ コピーの両方がバックアップされます。

|===
+

NOTE: クラスタ構成では、ポリシーで設定された保持設定に従って、バックアップがクラスタの各ノードに保持されます。クラスタの所有者ノードが変更された場合、以前の所有者ノードのバックアップが保持されます。保持設定はノード レベルでのみ適用されます。

.. スケジュール頻度セクションで、*オンデマンド*、*時間別*、*日次*、*週次*、*月次*の 1 つ以上の頻度タイプを選択します。
+

NOTE: リソース グループを作成する際に、バックアップ処理のスケジュール（開始日と終了日）を指定することができます。これにより、ポリシーとバックアップ間隔が同じである複数のリソース グループを作成できますが、各ポリシーに異なるバックアップ スケジュールを割り当てることもできます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間 (DST) 中はスケジュールは実行されません。

.. ポリシーラベルを選択します。
+

NOTE: リモート レプリケーションのプライマリ スナップショットにSnapMirrorラベルを割り当てることで、プライマリ スナップショットによってスナップショット レプリケーション操作をSnapCenterからONTAPセカンダリ システムにオフロードできるようになります。これは、ポリシー ページでSnapMirrorまたはSnapVaultオプションを有効にしなくても実行できます。

.. [セカンダリ レプリケーション オプションの選択] セクションで、次のセカンダリ レプリケーション オプションの 1 つまたは両方を選択します。
+
|===
| フィールド | 操作 


 a| 
Update SnapMirror after creating a local Snapshot
 a| 
別のボリュームにバックアップ セットのミラー コピーを保持する場合（SnapMirror）は、このオプションを選択します。

セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。

このオプションは、SnapMirrorアクティブ同期に対して有効にする必要があります。


IMPORTANT: Exchange ONTAPボリュームに対してSnapMirrorアクティブ同期が設定されている場合は、プライマリのみのポリシーは使用できません。SnapCenterではこれが許可されていません。「Mirror」オプションを有効にする必要があります。

トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

見るlink:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["[Topology]ページでのExchangeバックアップの表示"] 。



 a| 
Update SnapVault after creating a local Snapshot
 a| 
ディスクツーディスクのバックアップ レプリケーションを実行する場合は、このオプションを選択します。



 a| 
Error retry count
 a| 
レプリケーションの最大試行回数を入力します。この回数を超えると処理が停止します。

|===
+

NOTE: セカンダリ ストレージでSnapshotの上限に達しないように、ONTAPでセカンダリ ストレージのSnapMirror保持ポリシーを設定する必要があります。



. [Retention]ページで、保持設定を指定します。
+
表示されるオプションは、前に選択したバックアップ タイプと頻度タイプによって異なります。

+

NOTE: 最大保持値は 1018 です。保持数を、使用しているONTAPバージョンがサポートする値よりも大きい値に設定すると、バックアップが失敗します。

+

IMPORTANT: SnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗することがあります。

+
.. [Log backups retention settings]セクションで、次のいずれかを選択します。
+
|===
| 状況 | 操作 


 a| 
特定の数のログ バックアップのみを保持
 a| 
*ログが保持される完全バックアップの数*を選択し、最新の状態に復元可能な完全バックアップの数を指定します。

最新の状態（UTM）保持設定は、フル バックアップまたはログ バックアップを通じて作成されたログ バックアップに適用されます。たとえば、UTM保持設定が過去5回分のフル バックアップのログ バックアップを保持するようになっている場合、過去5回分のフル バックアップのログ バックアップが保持されます。

フル / ログ バックアップの一部として作成されたログ フォルダは、UTM処理の流れの中で自動的に削除されます。ログ フォルダを手動で削除することはできません。たとえば、フル バックアップやフル / ログ バックアップの保持設定が1カ月に設定され、UTM保持期間が10日に設定されている場合、これらのバックアップの一環として作成されたログ フォルダは、UTM保持設定に従って削除されます。そのため、ログ フォルダは10日間しか保持されず、その他のバックアップはすべてポイントインタイム リストアの対象としてマークされます。

最新の状態へのリストアを実行しない場合は、UTM保持設定の値を0に設定します。これにより、ポイントインタイム リストア処理が有効になります。

*ベスト プラクティス:* この設定は、完全バックアップの保持設定セクションのスナップショットの合計数 (完全バックアップ) の設定と同じにすることが最適です。これにより、フル バックアップごとにログ ファイルが保持されます。



 a| 
バックアップ コピーを特定の日数だけ保持
 a| 
*最後のログ バックアップを保持する* オプションを選択し、ログ バックアップ コピーを保持する日数を指定します。

フル バックアップが保持される日数まで、ログ バックアップが保持されます。



 a| 
Snapshot locking period
 a| 
*スナップショット コピーのロック期間*を選択し、日、月、または年を選択します。

SnapLock保持期間は100年未満にする必要があります。

|===
+
バックアップ タイプとして [*ログ バックアップ*] を選択した場合、ログ バックアップは完全バックアップの最新保持設定の一部として保持されます。

.. [Full backup retention settings]セクションで、次のいずれかをオンデマンド バックアップ用に選択し、続けてフル バックアップ用にもいずれかを選択します。
+
|===
| フィールド | 操作 


 a| 
Retain only a specific number of Snapshots
 a| 
保持する完全バックアップの数を指定する場合は、「*保持するスナップショット コピーの合計数*」オプションを選択し、保持するスナップショット (完全バックアップ) の数を指定します。

フル バックアップの数が指定した数を超えると、指定した数を超えるフル バックアップが、最も古いコピーから順に削除されます。



 a| 
Retain full backups for a specific number of days
 a| 
*スナップショット コピーの保存期間* オプションを選択し、スナップショット (完全バックアップ) を保存する日数を指定します。



 a| 
プライマリスナップショットのロック期間
 a| 
*プライマリ スナップショット コピーのロック期間*を選択し、日、月、または年を選択します。

SnapLock保持期間は100年未満にする必要があります。



 a| 
セカンダリスナップショットのロック期間
 a| 
*セカンダリ スナップショット コピーのロック期間*を選択し、日、月、または年を選択します。

|===
+
DAG構成のホストにフル バックアップがなくログ バックアップのみのデータベースがある場合は、次の方法でログ バックアップが保持されます。

+
*** デフォルトでは、 SnapCenter はDAG 内の他のすべてのホストでこのデータベースの最も古い完全バックアップを見つけ、完全バックアップの前にこのホストで作成されたすべてのログ バックアップを削除します。
*** _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_ ファイルにキー *MaxLogBackupOnlyCountWithoutFullBackup* を追加することで、ログ バックアップのみを使用する DAG 内のホスト上のデータベースに対する上記のデフォルトの保持動作をオーバーライドできます。
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
この例では、値が10になっています。これは、ホストで保持できるログ バックアップが最大10個であることを意味します。





. [Script]ページで、バックアップ処理の前またはあとに実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+
** プレスクリプトのバックアップ引数には、「`$Database`」と「`$ServerInstance`」が含まれます。
** PostScript バックアップ引数には、「`$Database`」、「`$ServerInstance`」、「`$BackupName`」、「`$LogDirectory`」、および「`$LogSnapshot`」が含まれます。
+
SNMPトラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

+

NOTE: プリスクリプトやポストスクリプトのパスに、ドライブや共有を含めることはできません。パスは、SCRIPTS_PATHの相対パスである必要があります。



. 概要を確認し、[完了] をクリックします。

