---
permalink: protect-sce/task_configure_snapmanager_7_x_for_exchange_and_snapcenter_plug_in_for_exchange_to_coexist.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter Plug-in for Microsoft Exchange ServerとSnapManager for Microsoft Exchange Serverを共存させるには、SnapManager for Microsoft Exchange Serverがインストールされているのと同じExchange ServerにSnapCenter Plug-in for Microsoft Exchange Serverをインストールし、SnapManager for Exchangeのスケジュールを無効にして、SnapCenter Plug-in for Microsoft Exchange Serverで新しいスケジュールとバックアップを設定する必要があります。 
---
= SnapManager 7.x for ExchangeとSnapCenterの共存の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for Microsoft Exchange ServerとSnapManager for Microsoft Exchange Serverを共存させるには、SnapManager for Microsoft Exchange Serverがインストールされているのと同じExchange ServerにSnapCenter Plug-in for Microsoft Exchange Serverをインストールし、SnapManager for Exchangeのスケジュールを無効にして、SnapCenter Plug-in for Microsoft Exchange Serverで新しいスケジュールとバックアップを設定する必要があります。

.開始する前に
* SnapManager for Microsoft Exchange ServerとSnapDrive for Windowsがすでにインストールされていて、SnapManager for Microsoft Exchange ServerのバックアップがシステムのSnapInfoディレクトリに保存されている必要があります。
* SnapManager for Microsoft Exchange Serverで作成した不要なバックアップを削除または再利用しておく必要があります。
* SnapManager for Microsoft Exchange Serverで作成したすべてのスケジュールを、Windowsスケジューラで一時停止または削除しておく必要があります。
* SnapCenter Plug-in for Microsoft Exchange ServerとSnapManager for Microsoft Exchange Serverは同じExchange Serverに共存させることができますが、既存のSnapManager for Microsoft Exchange Server環境をSnapCenterにアップグレードすることはできません。
+
SnapCenterにはアップグレード オプションが用意されていません。

* SnapCenterでは、SnapManager for Microsoft Exchange ServerのバックアップからのExchangeデータベースのリストアがサポートされていません。
+
SnapCenter Plug-in for Microsoft Exchange Serverのインストール後にSnapManager for Microsoft Exchange Serverをアンインストールせずに、SnapManager for Microsoft Exchange Serverのバックアップをあとからリストアする場合は、追加の手順を実行する必要があります。



.手順
. すべての DAG ノードで PowerShell を使用して、 SnapDrive for Windows VSS ハードウェア プロバイダーが登録されているかどうかを確認します: _vssadmin list providers_
+
[listing]
----
C:\Program Files\NetApp\SnapDrive>vssadmin list providers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Provider name: 'Data ONTAP VSS Hardware Provider'
   Provider type: Hardware
   Provider Id: {ddd3d232-a96f-4ac5-8f7b-250fd91fd102}
   Version: 7. 1. 4. 6845
----
. SnapDriveディレクトリから、 SnapDrive for WindowsからVSSハードウェアプロバイダーの登録を解除します：_navssprv.exe -r service –u_
. VSS ハードウェア プロバイダーが削除されたことを確認します: _vssadmin list providers_
. ExchangeホストをSnapCenterに追加して、SnapCenter Plug-in for Microsoft WindowsとSnapCenter Plug-in for Microsoft Exchange Serverをインストールします。
. すべてのDAGノードのSnapCenter Plug-in for Microsoft Windowsディレクトリから、VSSハードウェアプロバイダが登録されていることを確認します: _vssadmin list providers_
+
[listing]
----
[PS] C:\Windows\system32>vssadmin list providers
vssadmin 1.1 - Volume Shadow Copy Service administrative command-line tool
(C) Copyright 2001-2013 Microsoft Corp.

Provider name: 'Data ONTAP VSS Hardware Provider'
   Provider type: Hardware
   Provider Id: {31fca584-72be-45b6-9419-53a3277301d1}
   Version: 7. 0. 0. 5561
----
. SnapManager for Microsoft Exchange Serverのバックアップ スケジュールを停止します。
. SnapCenter GUIを使用して、オンデマンド バックアップの作成、スケジュール済みバックアップの設定、保持設定の指定を行います。
. SnapManager for Microsoft Exchange Serverをアンインストールします。
+
SnapManager for Microsoft Exchange Serverをすぐにアンインストールせずに、SnapManager for Microsoft Exchange Serverのバックアップをあとからリストアする場合は、次の手順を実行します。

+
.. すべての DAG ノードから Microsoft Exchange Server 用SnapCenterプラグインの登録を解除します: _navssprv.exe -r service -u_
+
[listing]
----
C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows>navssprv.exe -r service -u
----
.. _C:\Program Files\ NetApp\ SnapDrive\_ ディレクトリから、すべての DAG ノードにSnapDrive for Windows を登録します: _navssprv.exe -r service -a hostname\\username -p password_



