---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: PowerShellコマンドレットを使用してバックアップとリストアを実行する前に、Storage Virtual Machine（SVM）接続とクレデンシャルを作成する必要があります。 
---
= Exchange Server用のPowerShellコマンドレットを使用したストレージ システム接続とクレデンシャルの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShellコマンドレットを使用してバックアップとリストアを実行する前に、Storage Virtual Machine（SVM）接続とクレデンシャルを作成する必要があります。

.開始する前に
* PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。
* ストレージ接続を作成するには、Infrastructure Adminロールの権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ストレージ システム接続の追加中は、ホスト プラグインのインストールが進行中であってはなりません。ホスト キャッシュが更新されず、 SnapCenter GUI にデータベースのステータスが「バックアップに使用できません」または「 NetAppストレージ上にありません」と表示される可能性があるためです。

* ストレージ システムの名前は一意である必要があります。
+
SnapCenterでは、別々のクラスタに属している場合でも、複数のストレージ システムに同じ名前を付けることはサポートされません。SnapCenterでサポートする各ストレージ システムには、一意な名前とデータLIFの一意なIPアドレスが必要です。



.手順
. PowerShell接続セッションを開始するには、 `Open-SmConnection`コマンドレット。
+
PowerShellセッションを開く例を次に示します。

+
[listing]
----
PS C:\> Open-SmConnection
----
. ストレージシステムへの新しい接続を作成するには、 `Add-SmStorageConnection`コマンドレット。
+
新しいストレージ システム接続を作成する例を次に示します。

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. 新しい実行アカウントを作成するには、 `Add-Credential`コマンドレット。
+
Windowsクレデンシャルを使用してExchangeAdminという名前の新しいRun Asアカウントを作成する例を次に示します。

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。
