---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Plug-in for Windowsをインストールする前に、特定のインストール要件を確認しておく必要があります。 
---
= SnapCenter Plug-in for Microsoft Windowsのインストール要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Plug-in for Windowsをインストールする前に、特定のインストール要件を確認しておく必要があります。

ユーザがPlug-in for Windowsの使用を開始するためには、SnapCenter管理者が事前にSnapCenter Serverをインストールして設定し、前提条件となるタスクを実行する必要があります。

* Plug-in for Windowsをインストールするには、SnapCenter admin権限が必要です。
+
SnapCenter adminロールには管理者権限が必要です。

* SnapCenter Serverをインストールして設定しておく必要があります。
* Windowsホストにプラグインをインストールする際、組み込みでないクレデンシャルを指定する場合や、ユーザがローカル ワークグループに属している場合は、ホストのUACを無効にする必要があります。
* バックアップ レプリケーションが必要な場合は、SnapMirrorとSnapVaultをセットアップする必要があります。




== SnapCenter Plug-ins Package for Windowsをインストールするホストの要件

SnapCenter Plug-ins Package for Windowsをインストールする前に、ホスト システムのスペースとサイジングに関する基本的な要件を理解しておく必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティング システム
 a| 
Microsoft Windows

サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^] 。

Windows クラスター セットアップを使用している場合は、Windows リモート管理 (WinRM) もインストールして構成する必要があります。



 a| 
ホスト上のSnapCenterプラグインに必要な最小RAM
 a| 
1 GB



 a| 
ホスト上のSnapCenterプラグインに必要なインストールおよびログの最小スペース
 a| 
5 GB


NOTE: 十分なディスク スペースを割り当てて、ログ フォルダによるストレージ消費を監視する必要があります。必要なログ スペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスク スペースがない場合は、最近実行した処理のログが作成されません。



 a| 
必要なソフトウェア パッケージ
 a| 
* ASP.NET Core ランタイム 8.0.12 (およびそれ以降のすべての 8.0.x パッチ) ホスティング バンドル
* PowerShell Core 7.4.2


サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^] 。

.NET特有のトラブルシューティング情報については、以下を参照してください。 https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["インターネットに接続できないレガシー システムでは、 SnapCenter のアップグレードまたはインストールは失敗します。"]

|===


== Plug-in for Windowsのクレデンシャルの設定

SnapCenterは、クレデンシャルを使用してSnapCenterの処理を実行するユーザを認証します。SnapCenterプラグインのインストールに使用するクレデンシャルと、Windowsファイルシステムでのデータ保護処理に使用するクレデンシャルをそれぞれ作成する必要があります。

*必要なもの*

* プラグインのインストール前にWindowsクレデンシャルを設定する必要があります。
* このクレデンシャルには、管理者権限（リモート ホストに対する管理者権限を含む）を設定する必要があります。
* 個々のリソース グループのクレデンシャルを設定する場合で、ユーザに完全なadmin権限が割り当てられていない場合は、少なくともリソース グループとバックアップの権限を割り当てる必要があります。


*手順*

. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*資格情報*]をクリックします。
. *新規*をクリックします。
. [Credential]ページで次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
資格情報名
 a| 
クレデンシャルの名前を入力します。



 a| 
ユーザー名/パスワード
 a| 
認証に使用するユーザ名とパスワードを入力します。

** ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者またはSnapCenterプラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。ユーザ名フィールドの有効な形式は次のとおりです。

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** ローカル管理者（ワークグループの場合のみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。ユーザー名フィールドの有効な形式は次のとおりです。 `UserName`

+
パスワードには二重引用符 (") やバッククォート (`) を使用しないでください。未満記号（<）と感嘆符（!）を組み合わせて使用したりしないでください。たとえば、lessthan<!10、lessthan10<!、バックティック`12 などです。





 a| 
パスワード
 a| 
認証に使用するパスワードを入力します。

|===
. [OK]をクリックします。
+
クレデンシャルの設定が完了したら、必要に応じて[User and Access]ページでユーザやユーザ グループにクレデンシャルを割り当てることができます。





== Windows Server 2016以降でのgMSAの設定

Windows Server 2016以降では、作成したグループ管理サービス アカウント（gMSA）を通じて、管理対象ドメイン アカウントからサービス アカウントのパスワードを自動管理できます。

.開始する前に
* Windows Server 2016以降のドメイン コントローラが必要です。
* ドメインのメンバーであるWindows Server 2016以降のホストが必要です。


.手順
. KDSルート キーを作成し、gMSA内のオブジェクトごとに一意のパスワードを生成します。
. 各ドメインについて、Windowsドメインコントローラから次のコマンドを実行します: Add-KDSRootKey -EffectiveImmediately
. gMSAを作成して設定します。
+
.. 次の形式でユーザ グループ アカウントを作成します。
+
 domainName\accountName$
.. コンピュータ オブジェクトをグループに追加します。
.. 作成したユーザ グループを使用してgMSAを作成します。
+
次に例を示します。

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. 走る `Get-ADServiceAccount`サービス アカウントを確認するコマンド。


. ホストでgMSAを設定します。
+
.. gMSAアカウントを使用するホストで、Windows PowerShell用のActive Directoryモジュールを有効にします。
+
これを行うには、PowerShellから次のコマンドを実行します。

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. ホストを再起動します。
.. PowerShell コマンド プロンプトから次のコマンドを実行して、ホストに gMSA をインストールします。 `Install-AdServiceAccount <gMSA>`
.. 次のコマンドを実行して、gMSA アカウントを確認します。 `Test-AdServiceAccount <gMSA>`


. ホスト上の設定済みgMSAに管理者権限を割り当てます。
. SnapCenter Serverで設定済みのgMSAアカウントを指定してWindowsホストを追加します。
+
SnapCenter Serverにより、選択したプラグインがホストにインストールされ、プラグインのインストール時には指定したgMSAがサービスのログオン アカウントとして使用されます。


