---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: SnapCenterを使用してファイルシステムのバックアップをリストアすることができます。ファイルシステムのリストアは、指定したバックアップのすべてのデータをファイルシステムの元の場所にコピーする複数の段階からなるプロセスです。 
---
= Windowsファイルシステムのバックアップのリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してファイルシステムのバックアップをリストアすることができます。ファイルシステムのリストアは、指定したバックアップのすべてのデータをファイルシステムの元の場所にコピーする複数の段階からなるプロセスです。

.開始する前に
* ファイルシステムをバックアップしておく必要があります。
* ファイルシステムに対してバックアップ処理などのスケジュールが設定された処理が現在進行している場合は、リストア処理を開始する前にキャンセルしておく必要があります。
* ファイルシステムのバックアップは元の場所にのみリストアできます。別のパスを指定することはできません。
+
ファイルシステムのリストアでは、ファイルシステムの元の場所にあるデータがすべて上書きされ、バックアップからファイル単位でリストアすることはできません。ファイルシステムのバックアップに含まれる単一のファイルをリストアするには、バックアップをクローニングし、クローン内のファイルを使用する必要があります。

* システム ボリュームやブート ボリュームはリストアできません。
* SnapCenterでは、クラスタ グループをオフラインにすることなく、Windowsクラスタのファイルシステムをリストアできます。


.タスク概要
* SCRIPTS_PATHは、プラグイン ホストのSMCoreServiceHost.exe.ConfigファイルにあるPredefinedWindowsScriptsDirectoryキーを使用して定義します。
+
必要に応じて、このパスを変更してSMcoreサービスを再起動できます。セキュリティを確保するために、デフォルトのパスを使用することを推奨します。

+
キーの値は、API を介して Swagger から表示できます: API /4.7/configsettings

+
GET APIを使用すると、キーの値を表示できます。SET APIはサポートされません。

* SnapMirrorアクティブ同期でリストア処理を実行するには、プライマリの場所からバックアップを選択する必要があります。
* ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。


[role="tabbed-block"]
====
.SnapCenter UI
--
.手順
. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. リソースのリストをフィルタリングするには、[File System]および[Resource Group]のオプションを選択します。
. リストからリソース グループを選択し、[*復元*] をクリックします。
. [Backups]ページで、プライマリとセカンダリのどちらのストレージ システムからリストアするかを選択し、リストアするバックアップを選択します。
. [Restore]ウィザードで目的のオプションを選択します。
. リストア処理の実行前や実行後にSnapCenterで実行するプリスクリプトやポストスクリプトのパスと引数を入力できます。
+
たとえば、SNMPトラップの更新、アラートの自動化、ログの送信などをスクリプトで実行できます。

+

NOTE: プリスクリプトやポストスクリプトのパスに、ドライブや共有を含めることはできません。パスは、SCRIPTS_PATHの相対パスである必要があります。

. [Notification]ページで、次のいずれかのオプションを選択します。
+
|===
| フィールド | 操作 


 a| 
Log SnapCenter server events to storage system syslog
 a| 
SnapCenter Serverのイベントをストレージ システムのsyslogに記録する場合は、このオプションを選択します。



 a| 
Send AutoSupport notification for failed operations to storage system
 a| 
失敗した処理に関する情報をAutoSupportを使用してNetAppに送信する場合は、このオプションを選択します。



 a| 
メール設定
 a| 
バックアップの復元後に受信者に電子メールメッセージを送信するには、「*常時*」、「*失敗時*」、または「*失敗または警告時*」を選択します。SMTPサーバ、Eメールのデフォルトの件名、および送信先と送信元のEメール アドレスを入力します。

|===
. 概要を確認し、[完了] をクリックします。
. *モニター* > *ジョブ* をクリックして、操作の進行状況を監視します。



IMPORTANT: リストアしたファイルシステムにデータベースが含まれている場合は、データベースもリストアする必要があります。データベースをリストアしないと、データベースが無効な状態になることがあります。データベースのリストアの詳細については、そのデータベースのデータ保護ガイドを参照してください。

--
.PowerShellコマンドレット
--
.手順
. Open-SmConnectionコマンドレットを使用して、指定のユーザでSnapCenter Serverとの接続セッションを開始します。
+
[listing]
----
PS C:\> Open-Smconnection
----
. Get-SmBackupコマンドレットおよびGet-SmBackupReportコマンドレットを使用して、リストアする1つまたは複数のバックアップに関する情報を取得します。
+
この例では、使用可能なすべてのバックアップに関する情報を表示しています。

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
この例では、2015年1月29日から2015年2月3日までのバックアップに関する詳細な情報を示しています。

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Restore-SmBackupコマンドレットを使用して、バックアップからデータをリストアします。
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。

--
====