---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords: backup strategy 
summary: バックアップを作成する前にバックアップ戦略を定義しておくと、ファイルシステムの正常なリストアやクローニングに必要なバックアップを作成できます。バックアップ戦略の大部分は、サービス レベル アグリーメント（SLA）、目標復旧時間（RTO）、および目標復旧時点（RPO）によって決まります。 
---
= Windowsファイルシステムのバックアップ戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップを作成する前にバックアップ戦略を定義しておくと、ファイルシステムの正常なリストアやクローニングに必要なバックアップを作成できます。バックアップ戦略の大部分は、サービス レベル アグリーメント（SLA）、目標復旧時間（RTO）、および目標復旧時点（RPO）によって決まります。

SLAとは、求められるサービス レベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対応を定義したものです。RTOは、サービスの停止からビジネス プロセスの復旧までに必要となる時間です。RPOは、障害発生後に通常処理を再開するためにバックアップ ストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA、RTO、およびRPOは、データ保護戦略に関与します。



== Windowsファイルシステムのバックアップ スケジュール

バックアップ頻度はポリシーで指定され、バックアップ スケジュールはリソース グループの設定で指定されます。バックアップの頻度またはスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率とデータの重要性です。使用頻度の高いリソースは1時間ごとにバックアップする必要がありますが、ほとんど使用されないリソースは1日に1回バックアップすれば十分です。その他の要因としては、組織におけるリソースの重要性、サービス レベル アグリーメント（SLA）、目標復旧時点（RPO）などがあります。

SLAは、求められるサービス レベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対応を定義したものです。RPOは、障害発生後に通常処理を再開するためにバックアップ ストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLAとRPOはデータ保護戦略に関わる要件です。

使用頻度の高いリソースであっても、フル バックアップは1日に1～2回で十分です。

バックアップ スケジュールには、次の2つの要素があります。

* バックアップ頻度
+
バックアップ頻度 (バックアップを実行する頻度) は、一部のプラグインでは _スケジュール タイプ_ と呼ばれ、ポリシー構成の一部です。たとえば、バックアップ頻度を時間ごと、日ごと、週ごと、または月ごとに設定することも、ポリシーをオンデマンドのみのポリシーにする「*なし*」を指定することもできます。  *設定* > *ポリシー* をクリックすると、ポリシーにアクセスできます。

* バックアップ スケジュール
+
バックアップ スケジュール（バックアップが実行される日時）は、リソース グループ設定の一部です。たとえば、週次バックアップのポリシーが構成されたリソース グループがある場合は、毎週木曜日の午後 10 時にバックアップするようにスケジュールを構成できます。  *リソース* > *リソース グループ* をクリックすると、リソース グループのスケジュールにアクセスできます。





== Windowsファイルシステムで必要なバックアップの数

必要なバックアップの数を左右する要因としては、Windowsファイルシステムのサイズ、使用中のボリュームの数、ファイルシステムの変更率、サービス レベル アグリーメント（SLA）などがあります。



== Windowsファイルシステムのバックアップ命名規則

Windowsファイルシステムのバックアップでは、Snapshotのデフォルトの命名規則が使用されます。デフォルトのバックアップ命名規則ではSnapshot名にタイムスタンプが追加されるので、コピーが作成されたタイミングを特定できます。

Snapshotでは、次のデフォルトの命名規則が使用されます。resourcegroupname_hostname_timestamp

バックアップ リソース グループには、次の例のように論理的な名前を付ける必要があります。

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
この例では、各構文要素に次の意味があります。

* `dts1`リソース グループ名です。
* `mach1x88`ホスト名です。
* `03-12-2016_23.17.26`日付とタイムスタンプです。


バックアップの作成時に、バックアップを識別するためのタグを追加することもできます。一方、カスタマイズしたバックアップ命名規則を使用する場合は、バックアップ処理の完了後にバックアップの名前を変更する必要があります。



== バックアップ保持オプション

バックアップ コピーを保持する日数を選択するか、または保持するバックアップ コピーの数（ONTAPでは最大255個のコピー）を指定することができます。たとえば、組織の必要に応じて、10日分のバックアップ コピーや130個のバックアップ コピーを保持できます。

ポリシーを作成する際に、バックアップ タイプおよびスケジュール タイプの保持オプションを指定できます。

SnapMirrorレプリケーションを設定すると、デスティネーション ボリュームに保持ポリシーがミラーリングされます。

SnapCenter は、スケジュール タイプに一致する保持ラベルを持つ保持されたバックアップを削除します。リソースまたはリソース グループに対してスケジュール タイプが変更されると、古いスケジュール タイプ ラベルのバックアップがシステムに残ることがあります。


NOTE: バックアップ コピーを長期にわたって保持する場合は、SnapVaultバックアップを使用する必要があります。
