---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: 'SnapCenterの[Add Host]ページを使用して、Windowsホストを追加できます。SnapCenter Plug-in for Microsoft Windowsは、指定したホストに自動的にインストールされます。これは推奨されるプラグインのインストール方法です。ホストの追加とプラグインのインストールは、ホストごとまたはクラスタごとに実行できます。' 
---
= ホストの追加とSnapCenter Plug-in for Microsoft Windowsのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの[Add Host]ページを使用して、Windowsホストを追加できます。SnapCenter Plug-in for Microsoft Windowsは、指定したホストに自動的にインストールされます。これは推奨されるプラグインのインストール方法です。ホストの追加とプラグインのインストールは、ホストごとまたはクラスタごとに実行できます。

.開始する前に
* SnapCenter Serverホストのオペレーティング システムがWindows 2019で、プラグイン ホストのオペレーティング システムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* この処理は、SnapCenter Adminロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが実行する必要があります。
* Windowsホストにプラグインをインストールする際、組み込みでないクレデンシャルを指定する場合や、ユーザがローカル ワークグループに属している場合は、ホストのUACを無効にする必要があります。
* SnapCenterユーザーを、Windows Server の「サービスとしてログオン」ロールに追加する必要があります。
* メッセージ キュー サービスが実行中であることを確認する必要があります。
* グループ管理サービス アカウント（gMSA）を使用する場合は、管理者権限でgMSAを設定する必要があります。
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016以降でWindowsファイルシステム用にグループ管理サービス アカウントを設定する"]



.タスク概要
* SnapCenter Serverをプラグイン ホストとして別のSnapCenter Serverに追加することはできません。
* Windowsプラグイン
+
** Microsoft Windows
** Microsoft Exchange Server
** Microsoft SQL Server
** SAP HANA


* クラスタへのプラグインのインストール
+
クラスタ（WSFC、Oracle RAC、またはExchange DAG）にプラグインをインストールする場合、プラグインはクラスタのすべてのノードにインストールされます。

* Eシリーズ ストレージ
+
Eシリーズ ストレージに接続されたWindowsホストにPlug-in for Windowsをインストールすることはできません。




NOTE: SnapCenterでは、同じホスト（プラグイン ホスト）をSnapCenterに追加することはできません。そのホストがすでにワークグループに属していて、ドメインを別のものに変更しても（またはその逆をしても）、追加することはできません。同じホストを追加する場合は、SnapCenterからホストを削除して再度追加する必要があります。

.手順
. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. 上部で*管理対象ホスト*が選択されていることを確認します。
. *[追加]*をクリックします。
. [Hosts]ページで次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
ホストタイプ
 a| 
*Windows* タイプのホストを選択します。

SnapCenter Serverがホストを追加し、Plug-in for Windowsをホストにインストールします（プラグインがまだインストールされていない場合）。



 a| 
ホスト名
 a| 
ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。

SnapCenterが機能するためには、DNSが適切に設定されている必要があります。したがって、ベストプラクティスはFQDNを入力することです。

次のいずれかのIPアドレスまたはFQDNを入力できます。

** スタンドアロン ホスト
** Windows Serverフェイルオーバー クラスタリング（WSFC）
+
SnapCenterを使用してホストを追加する際、ホストがサブドメインの一部である場合は、FQDNを指定する必要があります。





 a| 
Credentials
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。

このクレデンシャルには、リモート ホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

ユーザ名、ドメイン、およびホスト タイプを含むクレデンシャルの詳細は、指定したクレデンシャルの名前にカーソルを合わせると表示されます。


NOTE: 認証モードは、[Add Host]ウィザードで指定するホスト タイプによって決まります。

|===
. [Select Plug-ins to Install]セクションで、インストールするプラグインを選択します。
+
新規導入の場合、プラグイン パッケージは表示されません。

. (オプション) [*その他のオプション*] をクリックします。
+
|===
| フィールド | 操作 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。

デフォルトのポート番号は8145です。SnapCenter Serverがカスタム ポートにインストールされている場合は、そのポート番号がデフォルト ポートとして表示されます。


NOTE: プラグインを手動でインストールしてカスタム ポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理が失敗します。



 a| 
Installation Path
 a| 
デフォルトのパスはC:\Program Files\NetApp\SnapCenterです。

必要に応じて変更できます。SnapCenter Plug-ins Package for Windowsの場合、デフォルト パスはC:\Program Files\NetApp\SnapCenterです。ただし、必要に応じて、デフォルト パスはカスタマイズできます。



 a| 
クラスター内のすべてのホストを追加する
 a| 
WSFC内のすべてのクラスタ ノードを追加するには、このチェック ボックスをオンにします。



 a| 
Skip preinstall checks
 a| 
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェック ボックスをオンにします。



 a| 
Use group Managed Service Account (gMSA) to run the plug-in services
 a| 
グループ管理サービス アカウント（gMSA）を使用してプラグイン サービスを実行する場合は、このチェック ボックスをオンにします。

gMSA 名を次の形式で指定します: _domainName\accountName$_。


NOTE: gMSAは、SnapCenter Plug-in for Windowsサービスのログオン サービス アカウントとしてのみ使用されます。

|===
. *送信*をクリックします。
+
「事前チェックをスキップ」チェックボックスを選択していない場合、ホストがプラグインのインストール要件を満たしているかどうかが検証されます。ディスク容量、RAM、PowerShellのバージョン、.NETのバージョン、および場所が最小要件に照らして検証されます。最小要件を満たしていない場合、対応するエラーまたは警告メッセージが表示されます。

+
エラーがディスク容量またはRAMに関連している場合は、次の場所にあるweb.configファイルを更新できます。 `C:\Program Files\NetApp\SnapCenter`デフォルト値を変更する WebApp。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HAのセットアップでweb.configファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. インストールの進捗状況を監視します。

