---
permalink: protect-hana/concept_snapcenter_plug_in_for_sap_hana_database_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenter Plug-in for SAP HANA Databaseは、SAP HANAデータベースに対応したデータ保護管理を提供する、NetApp SnapCenterソフトウェアのホスト側コンポーネントです。Plug-in for SAP HANA Databaseは、SnapCenter環境でのSAP HANAデータベースのバックアップ、リストア、およびクローニングを自動化します。 
---
= SnapCenter Plug-in for SAP HANA Databaseの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for SAP HANA Databaseは、SAP HANAデータベースに対応したデータ保護管理を提供する、NetApp SnapCenterソフトウェアのホスト側コンポーネントです。Plug-in for SAP HANA Databaseは、SnapCenter環境でのSAP HANAデータベースのバックアップ、リストア、およびクローニングを自動化します。

SnapCenterは、単一コンテナとマルチテナント データベース コンテナ（MDC）をサポートします。Plug-in for SAP HANA Databaseは、WindowsとLinuxのどちらの環境でも使用できます。HANAデータベース ホストにインストールされていないプラグインは、一元化されたホスト プラグインと呼ばれます。一元化されたホスト プラグインでは、異なるホストにまたがる複数のHANAデータベースを管理できます。

Plug-in for SAP HANA Databaseがインストールされている場合は、SnapCenterとNetApp SnapMirrorテクノロジを使用して、バックアップ セットのミラー コピーを別のボリュームに作成できます。また、このプラグインをNetApp SnapVaultテクノロジとともに使用して、標準への準拠を目的としたディスクツーディスク バックアップ レプリケーションを実行することもできます。

SAP HANA データベース用プラグインは、サイト全体の障害時でもビジネス サービスの運用を継続できるようにするSnapMirrorアクティブ シンク (当初はSnapMirror Business Continuity [SM-BC] としてリリース) をサポートし、セカンダリ コピーを使用してアプリケーションを透過的にフェイルオーバーできるようにします。SnapMirrorアクティブ同期でフェイルオーバーをトリガーするために、手動操作や追加のスクリプト作成は必要ありません。
