---
permalink: protect-hana/reference_types_of_restore_performed_for_auto_discovered_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Databases 
summary: 'SnapCenter は、自動的に検出された SAP HANA データベースに対して、ボリュームベースのSnapRestore (VBSR)、単一ファイルSnapRestore、および接続とコピーの復元タイプをサポートしています。' 
---
= 自動検出されたSAP HANAデータベースのリストア処理のタイプ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterでは、自動検出されたSAP HANAデータベースに対して、ボリュームベースのSnapRestore（VBSR）、Single File SnapRestore、およびConnect and Copyリストアのリストア タイプがサポートされます。



== NFS環境でボリュームベースのSnapRestore（VBSR）を実行するシナリオは、次のとおりです。

* 復元対象として選択されたバックアップがSnapCenter 4.3より前のリリースで作成され、**Complete Resource**オプションが選択されている場合のみ
* 復元対象として選択されたバックアップがSnapCenter 4.3で作成され、*ボリュームの復元*オプションが選択されている場合




== NFS環境でSingle File SnapRestoreを実行するシナリオは、次のとおりです。

* 復元対象として選択されたバックアップがSnapCenter 4.3で作成され、*完全なリソース*オプションのみが選択された場合
* マルチテナント データベース コンテナ (MDC) の場合、復元用に選択されたバックアップがSnapCenter 4.3 で取得され、*テナント データベース* オプションが選択されている場合
* 選択したバックアップがSnapMirrorまたはSnapVaultのセカンダリロケーションからのものであり、*完全なリソース*オプションが選択されている場合




== SAN環境でSingle File SnapRestoreを実行するシナリオは、次のとおりです。

* SnapCenter 4.3より前のリリースでバックアップが取られ、*完全なリソース*オプションが選択されている場合のみ
* SnapCenter 4.3でバックアップが取られ、*完全なリソース*オプションが選択されている場合のみ
* バックアップがSnapMirrorまたはSnapVaultのセカンダリロケーションから選択され、*完全なリソース*オプションが選択されている場合




== SAN環境でConnect and Copyリストアを実行するシナリオは、次のとおりです。

* MDCの場合、復元対象として選択されたバックアップがSnapCenter 4.3で取得され、*テナントデータベース*オプションが選択されている場合



NOTE: 復元スコープ ページで、*完全なリソース*、*ボリュームの復元*、および *テナント データベース* オプションを使用できます。
