---
permalink: protect-hana/task_create_a_storage_system_connection_and_a_run_as_account_using_powershell_cmdlets_for_sap_hana_database.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: PowerShellコマンドレットを使用してSAP HANAデータベースのバックアップ、リストア、クローニングを行う前に、Storage Virtual Machine（SVM）接続とクレデンシャルを作成する必要があります。 
---
= SAP HANAデータベース用のPowerShellコマンドレットを使用したストレージ システムへの接続とクレデンシャルの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShellコマンドレットを使用してSAP HANAデータベースのバックアップ、リストア、クローニングを行う前に、Storage Virtual Machine（SVM）接続とクレデンシャルを作成する必要があります。

.開始する前に
* PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。
* ストレージ接続を作成するには、Infrastructure Adminロールの権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ストレージ システム接続の追加中は、ホスト プラグインのインストールが進行中であってはなりません。ホスト キャッシュが更新されず、 SnapCenter GUI にデータベースのステータスが「バックアップに使用できません」または「 NetAppストレージ上にありません」と表示される可能性があるためです。

* ストレージ システムの名前は一意である必要があります。
+
SnapCenterでは、別々のクラスタに属している場合でも、複数のストレージ システムに同じ名前を付けることはサポートされません。SnapCenterでサポートする各ストレージ システムには、一意な名前とデータLIFの一意なIPアドレスが必要です。



.手順
. Open-SmConnectionコマンドレットを使用して、PowerShell接続セッションを開始します。
+
[listing]
----
PS C:\> Open-SmStorageConnection
----
. Add-SmStorageConnectionコマンドレットを使用して、ストレージ システムへの新しい接続を作成します。
+
[listing]
----
PS C:\> Add-SmStorageConnection -StorageType DataOntap -Type DataOntap -OntapStorage ‘scsnfssvm’ -Protocol Https -Timeout 60
----
. Add-SmCredentialコマンドレットを使用して、新しいクレデンシャルを作成します。
+
この例は、Windowsクレデンシャルを使用してFinanceAdminという名前の新しいクレデンシャルを作成する方法を示しています。

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. SnapCenter ServerにSAP HANA通信ホストを追加します。
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode hana
----
. パッケージとSnapCenter Plug-in for SAP HANA Databaseをホストにインストールします。
+
Linux：

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode hana
----
+
Windows：

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode hana -FilesystemCode scw -RunAsName FinanceAdmin
----
. HDBSQLクライアントのパスを設定します。
+
Windows：

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode hana -configSettings @{"HANA_HDBSQL_CMD" = "C:\Program Files\sap\hdbclient\hdbsql.exe"}
----
+
Linux：

+
[listing]
----
Set-SmConfigSettings -Plugin -HostName scs-hana.gdl.englab.netapp.com -PluginCode hana -configSettings @{"HANA_HDBSQL_CMD"="/usr/sap/hdbclient/hdbsql"}
----


コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。
