---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: SnapCenterを使用してSAP HANAデータベースのリソースをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。バックアップ ポリシーとは、バックアップをどのように管理し、スケジューリングし、保持するかを定める一連のルールです。 
---
= SAP HANAデータベースのバックアップ ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してSAP HANAデータベースのリソースをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。バックアップ ポリシーとは、バックアップをどのように管理し、スケジューリングし、保持するかを定める一連のルールです。

.開始する前に
* バックアップ戦略を定義しておく必要があります。
+
詳細については、SAP HANAデータベースのデータ保護戦略の定義に関する情報を参照してください。

* SnapCenterのインストール、ホストの追加、ストレージ システム接続の作成、リソースの追加などのタスクを実行して、データ保護の準備をしておく必要があります。
* ユーザがSnapshotをミラーまたはバックアップにレプリケートする場合は、ソース ボリュームとデスティネーション ボリューム両方のSVMをSnapCenter管理者がユーザに割り当てる必要があります。
+
ポリシーで、レプリケーション、スクリプト、アプリケーション設定を指定することもできます。それらのオプションを指定しておくことで、別のリソース グループにポリシーを再利用して時間を節約することができます。

* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"] 。


.タスク概要
* SAP HANAシステム レプリケーション
+
** プライマリSAP HANAシステムの保護では、すべてのデータ保護処理を実行できます。
** セカンダリSAP HANAシステムの保護では、バックアップを作成することはできません。
+
フェイルオーバー後は、セカンダリSAP HANAシステムがプライマリSAP HANAシステムになるため、すべてのデータ保護処理を実行できます。

+
SAP HANAデータ ボリュームのバックアップを作成することはできませんが、SnapCenterはデータ以外のボリューム（NDV）の保護を継続します。



* SnapLock
+
** [Retain the backup copies for a specific number of days]オプションを選択した場合は、SnapLockの保持期間をここで指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、ポリシーで指定した数よりも多くのSnapshotが保持される可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。




.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. *新規*をクリックします。
. 「名前」ページで、ポリシー名と詳細を入力します。
. ポリシー タイプ ページで、次の手順を実行します。
+
** ストレージタイプを選択
** バックアップ タイプを選択します。
+
|===
| 状況 | 操作 


 a| 
Snapshotテクノロジを使用してバックアップを作成する
 a| 
*スナップショットベース*を選択します。



 a| 
データベースの整合性チェックを実行する
 a| 
*ファイルベースのバックアップ*を選択します。アクティブなテナントのみがバックアップされます。

|===


. スナップショットとレプリケーション ページで、次の手順を実行します。
+
** *オンデマンド*、*時間別*、*日次*、*週次*、または*月次*を選択してスケジュール タイプを指定します。
+

NOTE: リソース グループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、頻度）を指定することができます。これにより、ポリシーとバックアップ間隔が同じである複数のリソース グループを作成できますが、各ポリシーに異なるバックアップ スケジュールを割り当てることもできます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間 (DST) 中はスケジュールは実行されません。



. [スナップショットとレプリケーション] ページで、[バックアップ タイプ] ページで選択したバックアップ タイプとスケジュール タイプの保持設定を指定します。
+
|===
| 状況 | 操作 


 a| 
特定の数のSnapshotを保持
 a| 
*保持するコピー*を選択し、保持するスナップショットの数を指定します。

スナップショットの数が指定数を超えると、最も古いスナップショットが最初に削除されます。


NOTE: 最大保持値は 1018 です。保持期間がONTAPバージョンでサポートされている値よりも高い値に設定されている場合、バックアップは失敗します。


IMPORTANT: SnapshotコピーベースのバックアップでSnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗することがあります。


NOTE: SAP HANAシステム レプリケーションでは、SAP HANAシステムのすべてのリソースを1つのリソース グループに追加することを推奨します。これにより、適切な数のバックアップが保持されます。


NOTE: SAP HANAシステム レプリケーションでは、作成されるSnapshotの総数はリソース グループに設定された保持数と同じになります。最も古いSnapshotが削除されるかどうかは、最も古いSnapshotが配置されているノードに基づいて決まります。たとえば、SAP HANAシステム レプリケーション プライマリとSAP HANAシステム レプリケーション セカンダリが含まれているリソース グループの保持数が7に設定されているとします。一度に作成できるSnapshotの数は、SAP HANAシステム レプリケーション プライマリとSAP HANAシステム レプリケーション セカンダリの両方を合わせて最大で7つです。



 a| 
Snapshotを特定の日数だけ保持
 a| 
*コピーの保持期間*を選択し、スナップショットを削除する前に保持する日数を指定します。



 a| 
スナップショットコピーのロック期間
 a| 
*スナップショット コピーのロック期間* を選択し、日、月、または年を指定します。

SnapLock保持期間は100年未満にする必要があります。

|===
. Snapshotラベルを選択します。
+

NOTE: リモート レプリケーションのプライマリ スナップショットにSnapMirrorラベルを割り当てることで、プライマリ スナップショットによってスナップショット レプリケーション操作をSnapCenterからONTAPセカンダリ システムにオフロードできるようになります。これは、ポリシー ページでSnapMirrorまたはSnapVaultオプションを有効にしなくても実行できます。

. スナップショット コピー ベースのバックアップの場合、[セカンダリ レプリケーション オプションの選択] セクションで、次のセカンダリ レプリケーション オプションの 1 つまたは両方を選択します。
+
|===
| フィールド | 操作 


 a| 
*ローカル スナップショット コピーを作成した後、 SnapMirror を更新します*
 a| 
別のボリュームにバックアップ セットのミラー コピーを作成する場合（SnapMirrorレプリケーション）は、このフィールドを選択します。

このオプションは、SnapMirrorアクティブ同期に対して有効にする必要があります。

ONTAPの保護関係のタイプがミラーとバックアップの場合、このオプションのみを選択すると、プライマリで作成されたSnapshotがデスティネーションに転送されませんが、デスティネーションのリストに表示されます。このSnapshotがリストア処理の対象としてデスティネーションで選択されると、「Secondary Location is not available for the selected vaulted/mirrored backup」というエラー メッセージが表示されます。

セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。

トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

見るlink:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["[Topology]ページでのSAP HANAデータベースのバックアップとクローンの表示"] 。



 a| 
*ローカルスナップショットコピーを作成した後、 SnapVault を更新します*
 a| 
ディスクツーディスクのバックアップ レプリケーション（SnapVaultバックアップ）を実行する場合は、このオプションを選択します。

セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

SnapLock がSnapLock Vault と呼ばれるONTAPのセカンダリにのみ設定されている場合、[トポロジ] ページの [更新] ボタンをクリックすると、 ONTAPから取得されたセカンダリのロック期間が更新されます。

SnapLock Vaultの詳細については、 https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["バックアップ デスティネーションのSnapshotコピーのWORM状態へのコミット"]

見るlink:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["[Topology]ページでのSAP HANAデータベースのバックアップとクローンの表示"] 。



 a| 
*エラー再試行回数*
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
+

NOTE: セカンダリ ストレージでSnapshotの上限に達しないように、ONTAPでセカンダリ ストレージのSnapMirror保持ポリシーを設定する必要があります。

. 概要を確認し、[完了] をクリックします。

