---
sidebar: sidebar 
permalink: sc-automation/concept_rest_web_services_foundation.html 
keywords: uri endpoints, http messages, json format 
summary: REST は分散 Web アプリケーションを作成するためのスタイルです。WebサービスAPIの設計においては、これによってサーバベースのリソースの公開とその状態の管理に関する一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準が使用されており、SnapCenterを管理するための柔軟な基盤が提供されます。 
---
= 基盤としてのREST Webサービス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Representational State Transfer（REST）は、分散Webアプリケーションの作成に使用される形式です。WebサービスAPIの設計においては、これによってサーバベースのリソースの公開とその状態の管理に関する一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準が使用されており、SnapCenterを管理するための柔軟な基盤が提供されます。



== リソースと状態の表示

リソースはWebベース システムの基本コンポーネントです。REST Webサービス アプリケーションを作成する場合、設計の早い段階で次の作業を行います。



=== システムまたはサーバベースのリソースの識別

すべてのシステムは、リソースを使用し、管理します。リソースには、ファイル、ビジネス トランザクション、プロセス、管理エンティティなどがあります。REST Webサービスに基づいてアプリケーションを設計する際に行う最初の作業の1つは、リソースを識別することです。



=== リソースの状態の定義および関連する状態処理

リソースは必ず複数ある状態のいずれかに該当します。状態は明確に定義する必要があり、状態の変化に作用する操作も明確に定義する必要があります。



== URIエンドポイント

すべてのRESTリソースは、明確に定義されたアドレス指定方式を使用して定義、提供される必要があります。リソースが置かれているエンドポイントは、Uniform Resource Identifier（URI）で識別されます。

URIは、ネットワークの各リソースに一意の名前を作成するための一般的なフレームワークです。Uniform Resource Locator（URL）は、リソースを識別してアクセスするためにWebサービスで使用されるURIの一種です。リソースは、通常、ファイル ディレクトリに似た階層構造で公開されます。



== HTTPメッセージ

Hypertext Transfer Protocol（HTTP）は、Webサービスのクライアントとサーバがリソースに関する要求と応答のメッセージを交換する際に使用するプロトコルです。

Webサービス アプリケーションの設計の一環として、リソースおよび対応する状態管理アクションにHTTPメソッドがマッピングされます。HTTPはステートレスです。したがって、関連する一連の要求と応答を1つのトランザクションの一部として関連付けるには、要求と応答のデータ フローで伝送されるHTTPヘッダーに追加情報を含める必要があります。



== JSONの形式

Webサービスのクライアントとサーバの間で情報を構造化したり転送したりする方法は複数ありますが、最も広く使用されているのはJavaScript Object Notation（JSON）です。

JSONは、単純なデータ構造をプレーン テキストで表現するための業界標準であり、リソースについての状態情報の転送に使用されます。SnapCenter REST APIでは、JSONを使用して、各HTTP要求と応答の本文で伝送されるデータをフォーマットします。
