---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html 
sidebar: sidebar 
keywords: REST API, Swagger 
summary: REST APIはSwagger Webページから利用できます。Swagger Webページにアクセスして、SnapCenter Server REST APIを表示したり、APIを手動で呼び出したりすることができます。REST APIを使用して、SnapCenter Serverの管理やデータ保護処理を行うことができます。 
---
= Swagger API WebページからREST APIにアクセスする方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST APIはSwagger Webページから利用できます。Swagger Webページにアクセスして、SnapCenter Server REST APIを表示したり、APIを手動で呼び出したりすることができます。REST APIを使用して、SnapCenter Serverの管理やデータ保護処理を行うことができます。

REST APIを実行するSnapCenter Serverの管理IPアドレスまたはドメイン名を確認しておく必要があります。

REST APIクライアントを実行するために特別な権限は必要ありません。すべてのユーザがSwagger Webページにアクセスできます。REST APIでアクセスするオブジェクトに対する権限は、REST APIへのログインに使用するトークンを生成したユーザに基づきます。

.手順
. ブラウザから、_\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/swagger/_ の形式で Swagger Web ページにアクセスするための URL を入力します。
+

NOTE: REST API URL に +、.、%、& の文字が含まれていないことを確認します。

. *Swagger Explore* フィールドに、Swagger API ドキュメントが自動的に表示されない場合は、次のように入力します: _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/Content/swagger/ SnapCenter.yaml_
. *探索*をクリックします。
+
APIリソース タイプ（カテゴリ）の一覧が表示されます。

. APIリソース タイプをクリックすると、そのリソース タイプのAPIが表示されます。


SnapCenter REST APIの実行時に予期しない動作が発生した場合は、ログ ファイルで原因を特定して問題を解決することができます。*モニター* > *ログ* > *ダウンロード* をクリックすると、 SnapCenterユーザー インターフェイスからログ ファイルをダウンロードできます。
