= プラグインキーストアのパスワードと使用中のCA署名キーペアのエイリアスを管理する
:allow-uri-read: 


インストールされたデジタル証明書をアクティブ化するには、 SnapCenterプラグイン サービスを使用して、プラグイン キーストアとその証明書のパスワードを管理し、CA 証明書を構成し、プラグイン トラストストアにルート証明書または中間証明書を構成し、プラグイン トラストストアに CA 署名キー ペアを構成する必要があります。

プラグインは、信頼ストアとキーストアの両方として、_/opt/ NetApp/snapcenter/scc/etc_ にあるファイル「keystore.jks」を使用します。



== プラグインキーストアのパスワードと使用中のCA署名キーペアのエイリアスを管理する

.手順
. プラグイン エージェント プロパティ ファイルからプラグイン キーストアのデフォルト パスワードを取得できます。
+
キー「KEYSTORE_PASS」に対応する値です。

. キーストアのパスワードを変更します。
+
 keytool -storepasswd -keystore keystore.jks
. キーストア内の秘密キー エントリのすべてのエイリアスのパスワードを、キーストアと同じパスワードに変更します。
+
 keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.jks
+
_agent.properties_ ファイルのキー KEYSTORE_PASS も同様に更新します。

. パスワードを変更したら、サービスを再起動します。



NOTE: プラグイン キーストアのパスワードと、秘密キーに関連付けられたすべてのエイリアス パスワードは同じである必要があります。



== ルート証明書または中間証明書をプラグイン信頼ストアに設定する

信頼ストアをプラグインするには、秘密キーなしでルート証明書または中間証明書を構成する必要があります。

.手順
. プラグイン キーストアが含まれるフォルダーに移動します: /opt/ NetApp/snapcenter/scc/etc。
. 「keystore.jks」ファイルを探します。
. キーストアに追加された証明書の一覧を表示します。
+
`keytool -list -v -keystore keystore.jks`

. ルート証明書か中間証明書を追加します。
+
 keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks
. ルート証明書または中間証明書をプラグイン信頼ストアに設定した後、サービスを再起動します。



NOTE: ルートCA証明書を追加してから、中間CA証明書を追加する必要があります。



== プラグイン信頼ストアにCA署名キーペアを構成する

CA 署名キー ペアをプラグイン信頼ストアに設定する必要があります。

.手順
. プラグイン キーストア /opt/ NetApp/snapcenter/scc/etc が含まれるフォルダーに移動します。
. 「keystore.jks」ファイルを探します。
. キーストアに追加された証明書の一覧を表示します。
+
`keytool -list -v -keystore keystore.jks`

. 秘密キーと公開キーの両方が設定されたCA証明書を追加します。
+
`keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS`

. キーストアに追加された証明書の一覧を表示します。
+
`keytool -list -v -keystore keystore.jks`

. キーストアに追加された新しいCA証明書に対応するエイリアスが、キーストアに含まれていることを確認します。
. CA証明書に追加した秘密キーのパスワードを、キーストアのパスワードに変更します。
+
デフォルトのプラグイン キーストア パスワードは、agent.properties ファイルのキー KEYSTORE_PASS の値です。

+
 keytool -keypasswd -alias "alias_name_in_CA_cert" -keystore keystore.jks
. CA 証明書のエイリアス名が長く、スペースや特殊文字 (「*」、「」) が含まれている場合は、エイリアス名を単純な名前に変更します。
+
 keytool -changealias -alias "long_alias_name" -destalias "simple_alias" -keystore keystore.jks
. agent.propertiesファイルのCA証明書からエイリアス名を設定します。
+
この値を、キーSCC_CERTIFICATE_ALIASに対して更新します。

. CA 署名キー ペアをプラグイン トラスト ストアに設定した後、サービスを再起動します。




== プラグインの証明書失効リスト（CRL）を構成する

.タスク概要
* SnapCenterプラグインは、事前に構成されたディレクトリ内の CRL ファイルを検索します。
* SnapCenterプラグインの CRL ファイルのデフォルト ディレクトリは、「opt/ NetApp/snapcenter/scc/etc/crl」です。


.手順
. キーCRL_PATHに対して、agent.propertiesファイルのデフォルト ディレクトリを変更、更新できます。
+
このディレクトリには、複数のCRLファイルを格納できます。受信する証明書については、それぞれのCRLに対して検証が行われます。


