= 
:allow-uri-read: 


PowerShellコマンドレットを使用してデータ保護処理を実行するには、Storage Virtual Machine（SVM）接続とクレデンシャルを作成しておく必要があります。

.開始する前に
* PowerShellコマンドレットを実行できるようにPowerShell環境を準備しておく必要があります。
* ストレージ接続を作成するには、Infrastructure Adminロールの権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ストレージ システム接続の追加中は、ホスト プラグインのインストールが進行中であってはなりません。ホスト キャッシュが更新されず、 SnapCenter GUI にデータベースのステータスが「バックアップに使用できません」または「 NetAppストレージ上にありません」と表示される可能性があるためです。

* ストレージ システムの名前は一意である必要があります。
+
SnapCenterでは、別々のクラスタに属している場合でも、複数のストレージ システムに同じ名前を付けることはサポートされません。SnapCenterでサポートする各ストレージ システムには、一意な名前と管理LIFの一意なIPアドレスが必要です。



.手順
. Open-SmConnectionコマンドレットを使用して、PowerShell Core接続セッションを開始します。
+
PowerShellセッションを開く例を次に示します。

+
[listing]
----
PS C:\> Open-SmConnection
----
. Add-SmStorageConnectionコマンドレットを使用して、ストレージ システムへの新しい接続を作成します。
+
新しいストレージ システム接続を作成する例を次に示します。

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Add-SmCredentialコマンドレットを使用して、新しいクレデンシャルを作成します。
+
Windowsクレデンシャルを使用してFinanceAdminという名前の新しいクレデンシャルを作成する例を次に示します。

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。
