---
permalink: protect-azure/add-hosts-install-plugin-for-sap-hana.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SAP HANA 
summary: ホストを追加し、プラグイン パッケージをインストールします。 
---
= ホストの追加とSnapCenter Plug-in for SAP HANA Databaseのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの[Add Host]ページを使用してホストを追加し、プラグイン パッケージをインストールする必要があります。プラグインは、自動的にリモート ホストにインストールされます。

.開始する前に
* この処理は、SnapCenter Adminロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが実行する必要があります。
* Windowsホストにプラグインをインストールする際、組み込みでないクレデンシャルを指定する場合や、ユーザがローカル ワークグループに属している場合は、ホストのUACを無効にする必要があります。
* 一元化されたホストにインストールする場合は、SAP HANAクライアント ソフトウェアがそのホストにインストールされていることを確認し、HDB SQLクエリをリモートで実行できるようにSAP HANAデータベース ホストで必要なポートを開きます。


.手順
. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. *管理対象ホスト*タブが選択されていることを確認します。
. *[追加]*をクリックします。
. [Hosts]ページで、次の操作を実行します。
+
.. [Host Type]フィールドで、ホスト タイプを選択します。
.. [Host name]フィールドに、ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。
.. [Credentials]フィールドに、作成したクレデンシャルを入力します。


. [Select Plug-ins to Install]セクションで、インストールするプラグインを選択します。
. (オプション) [*その他のオプション*] をクリックして詳細を指定します。
. *送信*をクリックします。
. ホスト タイプが Linux の場合は、フィンガープリントを確認し、[確認して送信] をクリックします。
+
クラスタ セットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

. インストールの進捗状況を監視します。

