---
permalink: protect-azure/add-hosts-install-plugin-for-sql.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SQL 
summary: ホストを追加し、プラグイン パッケージをインストールします。 
---
= ホストの追加とSnapCenter Plug-in for SQL Server Databaseのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterは、Azure NetApp Files上のSMB共有にあるSQLインスタンスのデータ保護をサポートしています。スタンドアロン構成と可用性グループ（AG）構成がサポートされています。

SnapCenterの[Add Host]ページを使用してホストを追加し、プラグイン パッケージをインストールする必要があります。プラグインは、自動的にリモート ホストにインストールされます。

.開始する前に
* この処理は、SnapCenter Adminロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが実行する必要があります。
* Windowsホストにプラグインをインストールする際、組み込みでないクレデンシャルを指定する場合や、ユーザがローカル ワークグループに属している場合は、ホストのUACを無効にする必要があります。


.手順
. 左側のナビゲーション ペインで、[*ホスト*] を選択します。
. 上部の*管理対象ホスト*タブが選択されていることを確認します。
. *追加*を選択します。
. [Hosts]ページで次の操作を実行します。
+
.. [Host Type]フィールドで、ホスト タイプを選択します。
.. [Host name]フィールドに、ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。
.. [Credentials]フィールドに、作成したクレデンシャルを入力します。


. *インストールするプラグインの選択*セクションで、インストールするプラグインを選択します。
. (オプション) [*その他のオプション*] をクリックして詳細を指定します。
. *送信*を選択します。
. *ログ ディレクトリの構成* を選択し、ホスト ログ ディレクトリの構成ページで、ホスト ログ ディレクトリの SMB パスを入力して、*保存* をクリックします。
. [送信] をクリックして、インストールの進行状況を監視します。

