---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Azure NetAppアカウントにアクセスするために、 SnapCenterで Azure 資格情報を作成します。 
---
= SnapCenterでのAzureクレデンシャルの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetAppアカウントにアクセスするには、SnapCenterでAzureクレデンシャルを作成する必要があります。

.開始する前に
* Azure でサービス プリンシパルを作成したことを確認します。
* 使用可能なサービス プリンシパルに関連付けられたテナント ID、クライアント ID、および秘密キーがあることを確認します。
+
** テナント ID は、Azure Portal の Entra ID の概要ページで確認できます。
** クライアント ID は、エンタープライズ アプリ/サービス プリンシパルのアプリケーション ID とも呼ばれます。これは、 SnapCenterのサービス プリンシパルとして機能するように作成したエンタープライズ アプリケーションの概要ページの Azure Portal にあります。
** クライアント秘密キーは秘密値とも呼ばれます。このクライアント シークレットは、Azure Portal の Entra ID の下の *アプリ登録* に移動することで作成できます。作成したエンタープライズ アプリを選択した後、*証明書とシークレット*、*新しいクライアント シークレット* に移動します。
+

NOTE: 秘密値にアクセスできるのは作成時のみです。後からアクセスすることはできません。

** サービス プリンシパルに権限を付与する必要があります。共同作成者の役割により、サービス プリンシパルは Azure で必要なアクションを実行できるようになります。これは、サブスクリプション ページ内のアクセス制御 (IAM) ページから付与できます。




.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*資格情報*]をクリックします。
. *新規*をクリックします。
. [Credential]ページで、クレデンシャルの作成に必要な次の情報を指定します。
+
|===
| フィールド | 操作 


 a| 
資格情報名
 a| 
クレデンシャルの名前を入力します。



 a| 
Authentication Mode
 a| 
ドロップダウン リストから *Azure 資格情報* を選択します。



 a| 
テナントID
 a| 
テナントIDを入力します。



 a| 
クライアントID
 a| 
クライアントIDを入力します。



 a| 
Client Secret Key
 a| 
クライアント シークレット キーを入力します。

|===
. [OK]をクリックします。

