---
permalink: protect-azure/create-backup-policies-oracle.html 
sidebar: sidebar 
keywords: create policies, Oracle, backup policies 
summary: バックアップするリソースまたはリソース グループのバックアップ ポリシーを作成します。 
---
= Oracleデータベースのバックアップ ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してOracleデータベース リソースをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。

.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. ドロップダウン リストから[Oracle Database]を選択します。
. *新規*をクリックします。
. [Name]ページで、ポリシーの名前と説明を入力します。
. ポリシー タイプ ページで、次の手順を実行します。
+
.. ストレージの種類として * Azure NetApp Files* を選択します。
.. バックアップ タイプとして、オンライン バックアップまたはオフライン バックアップを選択します。
.. Oracle Recovery Manager (RMAN) を使用してバックアップをカタログ化する場合は、「*Oracle Recovery Manager (RMAN) を使用したバックアップのカタログ化*」を選択します。
.. バックアップ後にアーカイブ ログを削除する場合は、[*バックアップ後にアーカイブ ログを削除する*] を選択します。
.. アーカイブ ログの削除設定を指定します。


. スナップショットとバックアップ ページで、次の手順を実行します。
+
.. スケジュールされたバックアップの頻度を選択します。
.. 保持設定を指定します。
.. Azure NetApp Filesバックアップを有効にする場合は、[バックアップを有効にする] を選択し、保持設定を指定します。


. [Script]ページで、バックアップ処理の前またはあとに実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
. [Verification]ページで、検証処理を実行するバックアップ スケジュールを選択し、検証処理の前後に実行するプリスクリプトまたはポストスクリプトのパスと引数をそれぞれ入力します。
. 概要を確認し、[完了] をクリックします。

