---
permalink: tech-refresh/task_tech_refresh_plugin_host.html 
sidebar: sidebar 
keywords: tech refresh, plug-in host, supported plug-ins, prerequisites to refresh plug-in hosts, application hosts, limitations for tech refresh of plug-in hosts 
summary: プラグイン ホストの技術更新を実行するには、リソースを古いホストから新しいホストに移動します。 
---
= SnapCenterプラグイン ホストの機器更改
:allow-uri-read: 


[role="lead"]
SnapCenterプラグイン ホストの機器更改が必要な場合は、古いホストから新しいホストにリソースを移動する必要があります。新しいホストをSnapCenterに追加すると、すべてのリソースが検出されますが、それらは新しいリソースとして扱われます。

.タスク概要
古いホスト名と新しいホスト名を入力として受け取るAPIまたはコマンドレットを実行し、リソースを名前で比較して、一致するリソースのオブジェクトを古いホストから新しいホストに再リンクする必要があります。一致するリソースは保護対象としてマークされます。

* _IsDryRun_ パラメータはデフォルトで True に設定されており、これにより古いホストと新しいホストの一致するリソースが識別されます。
+
一致するリソースを確認した後、_IsDryRun_ パラメータを False に設定して、一致するリソースのオブジェクトを古いホストから新しいホストに再リンクする必要があります。

* _AutoMigrateManuallyAddedResources_ パラメータはデフォルトで True に設定されており、手動で追加されたリソースが古いホストから新しいホストに自動的にコピーされます。
+
_AutoMigrateManuallyAddedResources_ パラメータは、Oracle および SAP HANA リソースにのみ適用されます。

* 古いホストと新しいホストのインスタンス名が異なる場合は、_SQLInstanceMapping_ パラメータを使用する必要があります。デフォルトのインスタンスの場合は、インスタンス名として _default_instance_ を使用します。


機器更改は次のSnapCenterプラグインでサポートされています。

* SnapCenter Plug-in for Microsoft SQL Server
+
** SQLデータベースがインスタンス レベルで保護されていて、ホストの機器更改の一環として一部のリソースのみが新しいホストに移動されると、既存のインスタンス レベルの保護がリソース グループ保護に変換され、両方のホストのインスタンスがリソース グループに追加されます。
** SQLホスト（仮にhost1とする）が別のホスト（仮にhost2とする）のリソースのスケジューラまたは検証サーバとして使用されている場合は、host1で機器更改を実行している間、スケジュールまたは検証の詳細は移行されず、host1で引き続き実行されます。変更が必要な場合は、対応するホストで手動で変更する必要があります。
** SQLフェイルオーバー クラスタ インスタンス（FCI）セットアップを使用している場合は、FCIクラスタに新しいノードを追加し、SnapCenterでプラグイン ホストを更新することで、機器更改を実行できます。
** SQL可用性グループ（AG）セットアップを使用している場合は、機器更改は必要ありません。新しいノードをAGに追加し、SnapCenterでホストを更新できます。


* SnapCenter Plug-in for Windows
* SnapCenter Plug-in for Oracle Database
+
Oracle Real Application Cluster（RAC）セットアップを使用している場合は、RACクラスタに新しいノードを追加し、SnapCenterでプラグイン ホストを更新することで、機器更改を実行できます。

* SnapCenter Plug-in for SAP HANA Database


サポートされているユースケースは次のとおりです。

* あるホストから別のホストへのリソースの移行。
* 複数のホストからそれよりも少ない数（1つ以上）のホストへのリソースの移行。
* 1つのホストから複数のホストへのリソースの移行。


サポートされているシナリオは次のとおりです。

* 新しいホストの名前が古いホストと異なる
* 既存のホストの名前が変更された


.開始する前に
このワークフローではSnapCenterリポジトリのデータが変更されるため、SnapCenterリポジトリをバックアップすることを推奨します。データに問題が発生した場合は、バックアップを使用してSnapCenterリポジトリを以前の状態に戻すことができます。

 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenterリポジトリのバックアップ"] 。

.手順
. 新しいホストを導入し、アプリケーションをインストールします。
. 古いホストのスケジュールを一時停止します。
. 必要なリソースを古いホストから新しいホストに移動します。
+
.. 新しいホストで同じストレージから必要なデータベースを起動します。
+
*** ストレージが古いホストと同じドライブまたは同じマウント パスにマッピングされていることを確認します。ストレージが正しくマッピングされていないと、古いホストで作成されたバックアップをリストアに使用できません。
+

NOTE: Windowsではデフォルトで、次に使用可能なドライブが自動的に割り当てられます。

*** ストレージDRが有効になっている場合は、それぞれのストレージを新しいホストにマウントする必要があります。


.. アプリケーションのバージョンに変更がある場合は、互換性を確認します。
.. Oracleプラグイン ホストの場合のみ、Oracleおよびそのグループ ユーザのUIDとGIDが古いホストのUIDとGIDと同じであることを確認します。
+
詳細については、以下を参照してください。

+
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_SQL_host_tech_refresh["How to migrate SQL database from old host to new host"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Oracle_host_tech_refresh["How to migrate Oracle database from old host to new host"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Hana_host_tech_refresh["How to bring up SAP HANA database onto new host"]




. 新しいホストをSnapCenterに追加します。
. すべてのリソースが検出されたかどうかを確認します。
. ホスト更新 API を実行します。 `/<snapcenter_version>/techrefresh/host`またはコマンドレット: _Invoke-SmTechRefreshHost_。
+

NOTE: ドライランはデフォルトで有効になっており、再リンクが必要な一致するリソースが特定されます。リソースを確認するには、API: '/jobs/{jobid}' またはコマンドレット _Get-SmJobSummaryReport_ を実行します。

+
複数のホストからリソースを移行した場合は、すべてのホストに対してAPIまたはコマンドレットを実行する必要があります。新しいホストのドライブまたはマウント パスが古いホストと同じでない場合、次のリストア処理が失敗します。

+
** SQL In Placeリストアが失敗します。ただし、RTAL機能は利用できます。
** OracleデータベースとSAP HANAデータベースのリストアが失敗します。
+
複数のホストに移行する場合は、すべてのホストで手順1からの手順をすべて実行する必要があります。

+

NOTE: 同じホストでAPIまたはコマンドレットを複数回実行できます。再リンクは、新しいリソースが特定された場合にのみ実行されます。



. （オプション）古いホストをSnapCenterから削除します。


.関連情報
APIに関する情報については、Swaggerページにアクセスする必要があります。link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["Swagger API Webページを使用してREST APIにアクセスする方法"] 。

コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。
