---
permalink: tech-refresh/task_tech_refresh_storage_system.html 
sidebar: sidebar 
keywords: tech refresh, storage system, 
summary: 古いストレージから新しいストレージにデータを移動し、新しいストレージをそれぞれのホストにマウントして、データベースを起動することで、ストレージ システムの技術更新を実行します。 
---
= ストレージ システムの機器更改
:allow-uri-read: 


[role="lead"]
ストレージの機器更改が行われると、データが新しいストレージに移行され、アプリケーション ホストが新しいストレージにマウントされます。SnapCenterのバックアップ ワークフローで新しいストレージが特定され、新しいストレージがSnapCenterに登録されている場合はSnapshotが作成されます。

ストレージ更改後に作成された新しいバックアップでは、リストア、マウント、およびクローニングを実行できます。ただし、バックアップには古いストレージの詳細が含まれているため、ストレージ更改前に作成されたバックアップに対してこれらの処理を実行すると失敗します。ストレージ機器更改のAPIまたはコマンドレットを実行して、SnapCenterの古いバックアップを新しいストレージの詳細で更新する必要があります。

機器更改は次のSnapCenterプラグインでサポートされています。

* SnapCenter Plug-in for Microsoft SQL Server
* SnapCenter Plug-in for Windows
* SnapCenter Plug-in for Oracle Database
* SnapCenter Plug-in for SAP HANA Database
* SnapCenter Plug-in for Microsoft Exchange Server


サポートされているユースケースは次のとおりです。

* プライマリ ストレージの更改
+
ストレージ機器更改では、プライマリ ストレージを新しいストレージに置き換えることができます。既存のセカンダリ ストレージをプライマリ ストレージに変換することはできません。

* セカンダリ ストレージの更改




== プライマリ ストレージのバックアップの更新

ストレージの機器更改が完了したら、ストレージ機器更改のAPIまたはコマンドレットを実行して、SnapCenterの古いバックアップを新しいストレージの詳細で更新する必要があります。

.開始する前に
このワークフローではSnapCenterリポジトリのデータが変更されるため、SnapCenterリポジトリをバックアップすることを推奨します。データに問題が発生した場合は、バックアップを使用してSnapCenterリポジトリを以前の状態に戻すことができます。

 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenterリポジトリのバックアップ"] 。

.手順
. 古いストレージから新しいストレージにデータを移行します。
+
移行方法については、以下を参照してください。

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["How to migrate the data to new storage"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["ボリュームをコピーしてすべてのSnapshotコピーを保持するにはどうすればよいですか？"]


. ホストをメンテナンス モードにします。
. 新しいストレージをそれぞれのホストでマウントし、データベースを起動します。
+
新しいストレージは、以前と同じ方法でホストに接続する必要があります。たとえば、SANとして接続されていた場合は、SANとして接続する必要があります。

+
新しいストレージは、古いストレージと同じドライブまたはパスにマウントする必要があります。

. すべてのリソースが動作していることを確認します。
. SnapCenterで新しいストレージを追加します。
+
SnapCenterのクラスタ間でSVM名が一意であることを確認します。新しいストレージで同じSVM名を使用していて、ストレージ更改の実行前にSVMのすべてのボリュームを移行できる場合は、古いクラスタのSVMを削除したあとSnapCenterで古いクラスタを再検出してSVMをキャッシュから削除することを推奨します。

. ホストを本番モードにします。
. SnapCenterで、ストレージを移行するリソースのバックアップを作成します。SnapCenterで最新のストレージ フットプリントを特定するには、新しいバックアップが必要です。このバックアップは、既存の古いバックアップのメタデータを更新するために使用されます。
+

NOTE: ホストに新しいLUNを接続すると、新しいシリアル番号が割り当てられます。Windowsファイルシステムの検出中、SnapCenterは一意のシリアル番号すべてを新しいリソースとして扱います。ストレージ機器更改時に、新しいストレージのLUNが同じドライブレターまたはパスでホストに接続される場合、SnapCenterでWindowsファイルシステムを検出すると、同じドライブレターまたはパスでマウントされていても、既存のリソースが削除済みとしてマークされ、新しいLUNが新しいリソースとして表示されます。リソースが削除済みとマークされていると、そのリソースはSnapCenterでストレージ機器更改の対象とはみなされません。そのため、古いリソースのバックアップはすべて失われます。Windowsファイルシステム リソースの場合、ストレージ更改を行う際は、ストレージの更改APIまたはコマンドレットを実行する前にリソースの検出を実行しないでください。

. 次のいずれかのストレージ更新 API を実行します。 `/<snapcenter_version>/techrefresh/primarystorage`またはコマンドレット: _Invoke-SmTechRefreshPrimaryStorage_。
+

NOTE: レプリケーションが有効なポリシーがリソースに設定されている場合は、ストレージ更改後の最新のバックアップにセカンダリ ストレージの詳細が含まれます。

+
.. SQLフェイルオーバー クラスタ インスタンス（FCI）セットアップを使用している場合、バックアップはクラスタ レベルで保持されます。ストレージ機器更改のために、クラスタ名を入力として指定する必要があります。
.. SQL可用性グループ（AG）セットアップを使用している場合、バックアップはノード レベルで保持されます。ストレージ機器更改のために、ノード名を入力として指定する必要があります。
.. Oracle Real Application Cluster（RAC）セットアップを使用している場合は、任意のノードでストレージ機器更改を実行できます。
+
_IsDryRun_ 属性はデフォルトで True に設定されています。これで、ストレージが更改されているリソースが特定されます。  API: '<snapcenter_version>/jobs/{jobid}' またはコマンドレット _Get-SmJobSummaryReport_ を実行すると、リソースと変更されたストレージの詳細を表示できます。



. ストレージの詳細を確認した後、_IsDryRun_ 属性を False に設定し、ストレージ更新 API を実行します。 `/<snapcenter_version>/techrefresh/primarystorage`またはコマンドレット: _Invoke-SmTechRefreshPrimaryStorage_。
+
これで、古いバックアップのストレージの詳細が更新されます。

+
同じホストでAPIまたはコマンドレットを複数回実行できます。古いバックアップのストレージの詳細はストレージが更改された場合にのみ更新されます。

+

NOTE: ONTAPでクローン階層を移行することはできません。移行対象のストレージのクローン メタデータがSnapCenter内にある場合、クローニングされたリソースは独立したリソースとしてマークされます。クローン メタデータのクローンは再帰的に削除されます。

. (オプション) すべてのスナップショットが古いプライマリ ストレージから新しいプライマリ ストレージに移動されていない場合は、次の API を実行します。 `/<snapcenter_version>/hosts/primarybackupsexistencecheck`またはコマンドレット _Invoke-SmPrimaryBackupsExistenceCheck_。
+
これにより、新しいプライマリ ストレージでSnapshotの有無のチェックが行われ、対応するバックアップがSnapCenterでの処理に使用できないとマークされます。





== セカンダリ ストレージのバックアップの更新

ストレージの機器更改が完了したら、ストレージ機器更改のAPIまたはコマンドレットを実行して、SnapCenterの古いバックアップを新しいストレージの詳細で更新する必要があります。

.開始する前に
このワークフローではSnapCenterリポジトリのデータが変更されるため、SnapCenterリポジトリをバックアップすることを推奨します。データに問題が発生した場合は、バックアップを使用してSnapCenterリポジトリを以前の状態に戻すことができます。

 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenterリポジトリのバックアップ"] 。

.手順
. 古いストレージから新しいストレージにデータを移行します。
+
移行方法については、以下を参照してください。

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["How to migrate the data to new storage"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["ボリュームをコピーしてすべてのSnapshotコピーを保持するにはどうすればよいですか？"]


. プライマリ ストレージと新しいセカンダリ ストレージの間にSnapMirror関係を確立し、関係が正常な状態であることを確認します。
. SnapCenterで、ストレージを移行するリソースのバックアップを作成します。
+
SnapCenterで最新のストレージ フットプリントを特定するには、新しいバックアップが必要です。このバックアップは、既存の古いバックアップのメタデータを更新するために使用されます。

+

IMPORTANT: この処理が完了するまで待つ必要があります。完了前に次の手順に進むと、SnapCenterで古いセカンダリSnapshotメタデータが完全に失われます。

. ホスト内のすべてのリソースのバックアップを正常に作成したら、次のいずれかのセカンダリ ストレージ更新 API を実行します。 `/<snapcenter_version>/techrefresh/secondarystorage`またはコマンドレット: _Invoke-SmTechRefreshSecondaryStorage_。
+
これで、指定したホスト内の古いバックアップのセカンダリ ストレージの詳細が更新されます。

+
これをリソース レベルで実行する場合は、各リソースの *更新* をクリックして、セカンダリ ストレージのメタデータを更新します。

. 古いバックアップが正常に更新されたら、プライマリとの古いセカンダリ ストレージ関係を解除できます。

