---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords: Manage policies 
summary: リソースまたはリソース グループからポリシーを適用解除し、変更、削除、表示、コピーを行うことができます。 
---
= ポリシーの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソースまたはリソース グループからポリシーを適用解除し、変更、削除、表示、コピーを行うことができます。



== ポリシーの変更

リソースまたはリソース グループにポリシーが適用されている場合は、レプリケーションのオプション、Snapshotの保持の設定、エラーの再試行回数、またはスクリプトの情報を変更できます。スケジュール タイプ（頻度）は、ポリシーを適用解除しないと変更できません。

*このタスクについて*

SnapCenter Serverでは、リソースまたはリソース グループにポリシーが適用されるときにのみスケジュール タイプが登録されるため、ポリシーのスケジュール タイプを変更するには追加の手順が必要です。

|===
| 状況 | 操作 


 a| 
新しいスケジュール タイプを追加
 a| 
新しいポリシーを作成し、必要なリソースまたはリソース グループに適用します。

たとえば、リソース グループ ポリシーで毎時バックアップのみが指定されている場合に、日次バックアップの追加が必要となったときは、日次スケジュール タイプを設定したポリシーを作成してリソース グループに追加します。これで、リソース グループに毎時と日次の2つのポリシーが適用されます。



 a| 
スケジュール タイプを削除または変更します。
 a| 
次の手順を実行します。

. 対象のポリシーを、そのポリシーを使用するすべてのリソースとリソース グループから適用解除します。
. スケジュール タイプを変更
. すべてのリソースとリソース グループにポリシーを適用し直します。


たとえば、ポリシーで毎時バックアップが指定されている場合に、これを日次バックアップに変更したいときは、まずポリシーを適用解除する必要があります。

|===
*手順*

. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. ポリシーを選択し、[*変更*]をクリックします。
. 情報を変更し、[完了] をクリックします。




== ポリシーの適用解除

リソースのデータ保護を管理するポリシーが不要となった場合は、リソースまたはリソース グループからいつでもポリシーを適用解除できます。ポリシーを削除する場合やスケジュール タイプを変更する場合は、事前にポリシーを適用解除する必要があります。

*手順*

. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. [リソース] ページで、[表示] リストから [リソース グループ] を選択します。
. リソース グループを選択し、[*リソース グループの変更*] をクリックします。
. [Modify Resource Group]ウィザードの[Policies]ページに表示されるドロップダウン リストで、適用解除するポリシーの横のチェック マークをオフにします。
. ウィザードの残りの部分でリソース グループに追加の変更を加え、[完了] をクリックします。




== ポリシーの削除

不要になったポリシーは削除することができます。

.開始する前に
ポリシーがリソースまたはリソース グループに関連付けられている場合は、リソースまたはリソース グループからポリシーを適用解除する必要があります。

*手順*

. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. ポリシーを選択し、[*削除*] をクリックします。
. *はい*をクリックします。

