---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords: Manage storage system 
summary: ストレージ システムを追加したあと、ストレージ システムの設定や接続を変更したり、ストレージ システムを削除したりできます。 
---
= ストレージ システムの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ システムを追加したあと、ストレージ システムの設定や接続を変更したり、ストレージ システムを削除したりできます。



== ストレージ システムの設定の変更

SnapCenterを使用してストレージ システムの設定を変更し、ユーザ名、パスワード、プラットフォーム、ポート、プロトコル、タイムアウト時間、優先IPアドレス、メッセージングの各オプションを変更することができます。

*このタスクについて*

個々のユーザまたはグループのストレージ接続を変更できます。あるユーザが同じストレージ システムへの権限が付与された複数のグループに所属している場合、ストレージ接続リストにはそのストレージ接続の名前が重複して（権限が割り当てられているグループごとに）表示されます。

*手順*

. 左側のナビゲーション ペインで、[*ストレージ システム*] をクリックします。
. [ストレージ システム] ページの [*タイプ*] ドロップダウンから、次のいずれかのアクションを実行します。
+
|===
| 選択するオプション | 手順 


 a| 
ONTAP SVM
 a| 
追加されたすべてのStorage Virtual Machine（SVM）を表示し、目的のSVM設定を変更するには、次の手順を実行します。

.. [Storage Connections]ページで、該当するSVMの名前をクリックします。
.. 次のいずれかを実行します。
+
*** SVM がどのクラスタにも属していない場合は、[ストレージ システムの変更] ページで、ユーザー名、パスワード、EMS およびAutoSupport設定、プラットフォーム、プロトコル、ポート、タイムアウト、優先 IP などの構成を変更します。
*** SVM がクラスタの一部である場合は、[ストレージ システムの変更] ページで [*SVM を個別に管理*] を選択し、ユーザー名、パスワード、EMS およびAutoSupport設定、プラットフォーム、プロトコル、ポート、タイムアウト、優先 IP などの構成を変更します。
+
SVM を独立して管理できるように変更した後、クラスター経由で管理することにした場合は、SVM を削除して [再検出] をクリックする必要があります。SVMがONTAPクラスタに追加されます。

+

NOTE: SnapCenter GUIでストレージ システムのパスワードを更新した場合、該当するプラグインまたはサーバ ホストのSMCoreサービスを再起動する必要があります。再起動しないと、更新したパスワードがSMCoreに反映されないため、クレデンシャル エラーでバックアップ ジョブが失敗します。







 a| 
ONTAPクラスタ
 a| 
追加されたすべてのクラスタを表示し、目的のクラスタ設定を変更するには、次の手順を実行します。

.. [Storage Connections]ページで、クラスタの名前をクリックします。
.. [Modify Storage System]ページで、[Username]の横の編集アイコンをクリックし、ユーザ名とパスワードを変更します。
.. EMSおよびAutoSupportの設定を選択または選択解除します。
.. *その他のオプション*をクリックし、プラットフォーム、プロトコル、ポート、タイムアウト、優先 IP などのその他の構成を変更します。


|===
. *送信*をクリックします。




== ストレージ システムの削除

SnapCenterを使用して、使用していないストレージ システムを削除できます。

*このタスクについて*

個々のユーザまたはグループのストレージ接続を削除できます。あるユーザが同じストレージ システムへの権限が付与された複数のグループに所属している場合、ストレージ接続リストにはそのストレージ システムの名前が重複して（権限が割り当てられているグループごとに）表示されます。


IMPORTANT: ストレージ システムを削除すると、そのストレージ システムで実行中の処理はすべて失敗します。

*手順*

. 左側のナビゲーション ペインで、[*ストレージ システム*] をクリックします。
. [ストレージ システム] ページの [タイプ] ドロップダウンから、[ONTAP SVM] または [ONTAPクラスタ] を選択します。
. [Storage Connections]ページで、削除するSVMまたはクラスタの横にあるチェック ボックスを選択します。
+

NOTE: クラスタに含まれるSVMは選択できません。

. *削除*をクリックします。
. ストレージ システム接続設定の削除ページで、[*OK*] をクリックします。
+

NOTE: ONTAP GUI を使用してONTAPクラスタから SVM が削除された場合は、 SnapCenter GUI で [*再検出*] をクリックして SVM リストを更新します。





== REST APIサポート

ONTAPへのすべてのASA、 AFF、またはFASシステム接続は、デフォルトで ZAPI を経由します。  REST API は特定のONTAPバージョンに対して有効にできます。

SnapCenter は、ZAPI をサポートしていないASA r2 システム上のすべての操作を REST API を利用して実行します。

次の構成ファイル内の構成キーを変更できます。

* ストレージ接続のRestEnabled
+
デフォルト値は false です。

* 使用する最小オンタップバージョンREST
+
デフォルト値は 9.13.1 です。



.REST API 経由で接続を有効にする
. IsRestEnabledForStorageConnection を true に設定します。
. サーバーおよび Windows プラグイン ホストの両方で、SMCoreServiceHost.dll.config および SnapDriveService.dll.config にキーを追加します。
+
_<キーを追加="IsRestEnabledForStorageConnection" 値="true" />_



.REST API 経由の接続を特定バージョンのONTAPに制限する
. 構成パラメータ MinOntapVersionToUseREST を true に設定します。
. サーバーおよび Windows プラグイン ホストの両方で、SMCoreServiceHost.dll.config および SnapDriveService.dll.config にキーを追加します。
+
_<キーを追加="MinOntapVersionToUseREST" 値="9.13.1" />_

. サーバー上の SmCore サービスと、プラグイン マシン上のプラグインおよびSnapDriveサービスを再起動します。

