---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords: SnapCenter reports 
summary: SnapCenterには、システムの健全性や処理の状況を監視および管理するためのさまざまなレポート オプションが用意されています。 
---
= SnapCenterのレポート機能の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterには、システムの健全性や処理の状況を監視および管理するためのさまざまなレポート オプションが用意されています。

|===
| レポートの種類 | 説明 


 a| 
Backup Report
 a| 
バックアップ レポートには、SnapCenter環境のバックアップ状況に関する全体的なデータ、バックアップの成功率、および指定した期間に実行された各バックアップに関する情報が表示されます。バックアップが削除された場合、そのバックアップのステータス情報はレポートに表示されません。バックアップ詳細レポートには、指定したバックアップ ジョブに関する詳細情報に加え、バックアップに成功したリソースと失敗したリソースの一覧が表示されます。



 a| 
クローン レポート
 a| 
クローン レポートには、SnapCenter環境のクローニング状況に関する全体的なデータ、クローニングの成功率、および指定した期間に実行された各クローニング ジョブに関する情報が表示されます。クローンが削除された場合、そのクローンのステータス情報はレポートに表示されません。クローン詳細レポートには、指定したクローン、クローン ホスト、クローニング ジョブ タスクのステータスについての詳細情報が表示されます。タスクが失敗した場合は、クローン詳細レポートにその情報が表示されます。



 a| 
Restore Report
 a| 
リストア レポートには、リストア ジョブに関する全体的な情報が表示されます。リストア詳細レポートには、指定したリストア ジョブについて、ホスト名、バックアップ名、ジョブの開始日時と期間、個々のジョブ タスクのステータスなどの詳細情報が表示されます。タスクが失敗した場合は、リストア詳細レポートにその情報が表示されます。



 a| 
保護レポート
 a| 
このレポートには、すべてのSnapCenterプラグイン インスタンスで管理されているリソースについて、保護の詳細が表示されます。このレポートには、すべてのプラグイン インスタンスで管理されているリソースについて、保護の詳細が表示されます。概要に加え、保護されていないリソース、レポートの生成時にバックアップされていなかったリソース、バックアップ処理に失敗したリソース グループのリソース、およびSnapVaultステータスの詳細を確認できます。



 a| 
スケジュール済みレポート
 a| 
毎日、毎週、または毎月のように定期的に実行されるレポートです。指定した日時に自動的に生成され、電子メールで該当するユーザに送信されます。スケジュールは有効化、無効化、変更、または削除できます。有効にしたスケジュールは、[今すぐ実行] ボタンをクリックするとオンデマンドで実行できます。管理者はすべてのスケジュールを実行できますが、生成されるレポートに含まれるデータは、スケジュールを作成したユーザが割り当てた権限によって異なります。

管理者以外のユーザは、自分の権限に基づいてスケジュールを表示または変更できます。[Add Role]ページで[All members of this role can see other members' objects]オプションが選択されている場合、そのロールの他のメンバーは表示および変更できます。

|===


== レポートへのアクセス

SnapCenterダッシュボードを使用して、システムの健全性に関する概要を確認できます。ダッシュボードから詳細にドリルダウンできます。また、詳細レポートに直接アクセスすることもできます。

次のいずれかの方法でレポートにアクセスできます。

* 左側のナビゲーション ペインで、*ダッシュボード* をクリックし、*最新の保護の概要* 円グラフをクリックして、レポート ページで詳細を表示します。
* 左側のナビゲーション ペインで、[*レポート*] をクリックします。




== レポートのフィルタ

必要な情報や期間に応じてパラメータを指定し、レポート データをフィルタリングできます。

*手順*

. 左側のナビゲーション ペインで、[*レポート*] をクリックします。
. パラメータ ビューが表示されない場合は、レポート ツールバーの [*パラメータ領域の切り替え*] アイコンをクリックします。
. レポートを実行する期間を指定します。+ 終了日を省略すると、利用可能なすべての情報が取得されます。
. 次のいずれかの条件に基づいて、レポート情報を絞り込みます。
+
** リソース グループ
** ホスト
** ポリシー
** リソース
** ステータス
** プラグイン名


. *適用*をクリックします。




== レポートのエクスポートまたは印刷

SnapCenterのレポートをエクスポートして、さまざまな形式で参照することができます。レポートは印刷することもできます。

*手順*

. 左側のナビゲーション ペインで、[*レポート*] をクリックします。
. レポートのツールバーから、次のいずれかを実行します。
+
** 印刷可能なレポートをプレビューするには、[*印刷プレビューの切り替え*] アイコンをクリックします。
** レポートを別の形式でエクスポートするには、[*エクスポート*] アイコンのドロップダウン リストから形式を選択します。


. レポートを印刷するには、[印刷] アイコンをクリックします。
. 特定のレポートの概要を確認するには、レポートの該当するセクションまでスクロールします。




== Eメール通知用のSMTPサーバの設定

データ保護ジョブのレポートを自分または他のユーザに送信する際に使用するSMTPサーバを指定できます。テスト メールを送信して設定の確認することもできます。この設定は、Eメール通知を設定したSnapCenterのすべてのジョブにグローバルに適用されます。

このオプションは、すべてのデータ保護ジョブ レポートの送信に使用するSMTPサーバを設定します。ただし、特定のリソースに対するSnapCenterのデータ保護ジョブの更新情報を定期的に自分または他のユーザに送信し、更新ステータスを監視できるようするには、リソース グループの作成時にSnapCenterのレポートをEメールで送信するオプションを設定できます。

*手順*

. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*グローバル設定*]をクリックします。
. SMTP サーバーを入力し、[保存] をクリックします。
. テストメールを送信するには、メールの送信元と送信先のメールアドレスを入力し、件名を入力して、[送信] をクリックします。




== レポートのEメール送信オプションの設定

SnapCenterのデータ保護ジョブの更新情報を定期的に自分または他のユーザに送信し、更新ステータスを監視できるようするには、リソース グループの作成時にSnapCenterのレポートをEメールで送信するオプションを設定します。

.開始する前に
[Settings]の[Global Settings]ページでSMTPサーバを設定しておく必要があります。

*手順*

. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. 表示するリソースの種類を選択し、[*新しいリソース グループ*] をクリックするか、既存のリソース グループを選択して [*変更*] をクリックし、既存のリソース グループの電子メール レポートを構成します。
. [New Resource Group]ウィザードの[Notification]パネルで、レポートを常に受け取るか、障害の発生時に受け取るか、障害または警告の発生時に受け取るかをプルダウン メニューから選択します。
. Eメールの送信元アドレス、Eメールの送信先アドレス、およびEメールの件名を入力します。

