---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords: Monitor jobs, schedules, events, logs 
summary: '[Monitor]ページから、ジョブの進捗状況の監視、スケジュールされたジョブに関する情報の取得、イベントやログの確認が可能です。' 
---
= ジョブ、スケジュール、イベント、およびログの監視
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[Monitor]ページから、ジョブの進捗状況の監視、スケジュールされたジョブに関する情報の取得、イベントやログの確認が可能です。



== ジョブの監視

SnapCenterのバックアップ、クローニング、リストア、検証の各ジョブに関する情報を表示できます。このビューは、開始日と終了日、ジョブのタイプ、リソース グループ、ポリシー、またはSnapCenterプラグインでフィルタできます。また、指定したジョブの詳細情報やログ ファイルを取得することもできます。

SnapMirrorやSnapVaultの処理に関連するジョブも監視できます。


NOTE: SnapCenter Adminロールまたはその他のスーパーユーザ ロールが割り当てられている場合を除き、監視できるのは自分で作成したジョブと自分に関係があるジョブだけです。

ジョブの監視に関連して次のタスクを実行できます。

* バックアップ、クローニング、リストア、検証の各処理を監視する。
* ジョブの詳細とレポートを表示する。
* スケジュールされたジョブを停止する。




=== スケジュールされたバックアップジョブを管理する

SnapCenter 6.0.1 リリース以降では、特定の時点で実行できるスケジュールされたジョブの数にしきい値を設定する新しいパラメーター *JobConcurrencyThreshold* が導入されました。これにより、システムのハードウェア構成に基づいて、実行するバックアップの数を制御できます。

*JobConcurrencyThreshold* に割り当てられているデフォルト値は 0 で、無効になっています。スケジュールされたバックアップ ウィンドウ中にパフォーマンスの低下が見られる場合、値を割り当てることで有効にすることができます。


NOTE: *JobConcurrencyThreshold* を有効にして同時ジョブを管理すると、 SnapCenterバックアップの順序を制御できなくなり、スケジュールで指定された時刻にバックアップがトリガーされない可能性があります。

.手順
. _C:\Program Files\ NetApp\ SnapCenter WebApp\ SnapManager.Web.UI.dll.config_ にある _JobConcurrencyThreshold_ パラメータの値を設定します。
. IIS > アプリケーション プール > SnapCenter > 再起動をクリックして、 SnapCenterアプリケーション プールをリサイクルします。
. IIS > サイト > SnapCenter > 再起動をクリックして、 SnapCenter Web サービスを再起動します。




=== 古いジョブを管理する

古いジョブは、 SnapCenterでの中断や不適切なジョブ更新によって作成されます。 SnapCenter 6.0.1 リリース以降では、72 時間以上停止している古いジョブをクリーンアップするための定義済みスケジュールが導入されています。設定可能なパラメータ *CleanUpStaleJobsIntervalHours* を編集することで、スケジュールの頻度を変更できます。

*モニター* > *スケジュール* > *SnapCenter_StaleJobCleanUp* からスケジュールを実行することで、オンデマンドでクリーンアップをトリガーできます。

.手順
. _C:\Program Files\ NetApp\ SnapCenter WebApp\ SnapManager.Web.UI.dll.config_ にある _CleanUpStaleJobsIntervalHours_ パラメータの値を設定します。
. IIS > アプリケーション プール > SnapCenter > 再起動をクリックして、 SnapCenterアプリケーション プールをリサイクルします。
. IIS > サイト > SnapCenter > 再起動をクリックして、 SnapCenter Web サービスを再起動します。




== スケジュールの監視

現在のスケジュールを表示して、処理の開始日時、前回の実行日時、および次回の実行日時を確認できます。また、処理が実行されるホストのほか、処理のリソース グループやポリシーに関する情報も確認できます。

*手順*

. 左側のナビゲーション ペインで、[*モニター*] をクリックします。
. モニターページで、*スケジュール*をクリックします。
. リソース グループとスケジュール タイプを選択します。
. スケジュールされた処理の一覧を確認します。




== イベントを監視する

ユーザによるリソース グループの作成、システムによるアクティビティの開始、スケジュールされたバックアップの作成など、システム内のSnapCenterイベントの一覧を表示できます。イベントを監視することで、バックアップやリストアなどの処理が実行中であるかどうかを確認することができます。

*このタスクについて*

[Events]ページには、すべてのジョブの情報が表示されます。たとえば、バックアップ ジョブが開始されると、「`backup start`」イベントが表示されます。バックアップが完了すると、「`バックアップ完了`」イベントが表示されます。

*手順*

. 左側のナビゲーション ペインで、[*モニター*] をクリックします。
. モニターページで、*イベント*をクリックします。
. (オプション) [フィルター] ボックスに、開始日または終了日、イベントのカテゴリ (バックアップ、リソース グループ、ポリシーなど)、および重大度レベルを入力し、[適用] をクリックします。または、検索ボックスに文字を入力します。
. イベントの一覧を確認します。




== ログの監視

SnapCenter Serverログ、SnapCenterホスト エージェント ログ、およびプラグイン ログを表示およびダウンロードできます。これらのログはトラブルシューティングに役立ちます。

*このタスクについて*

フィルタを使用して、特定の重大度レベルのログだけを表示するように絞り込むことができます。

* デバッグ
* 情報
* 警告
* エラー
* 致命的


バックアップ ジョブが失敗した理由を特定する目的で、ジョブ レベルのログを表示することもできます。ジョブ レベルのログの場合は、[モニター] > [ジョブ] オプションを使用します。

*手順*

. 左側のナビゲーション ペインで、[*モニター*] をクリックします。
. 「ジョブ」ページでジョブを選択し、「ログのダウンロード」をクリックします。
+
ダウンロードされたzipフォルダには、ジョブのログと一般的なログが含まれています。zipされたフォルダの名前は、選択したジョブのIDとタイプで構成されています。

. モニターページで、*ログ*をクリックします。
. ログ タイプ、ホスト、およびインスタンスを選択します。
+
ログタイプを*プラグイン*として選択すると、ホストまたはSnapCenterプラグインを選択できます。ログタイプが*サーバー*の場合、これは選択できません。

. 特定のソース、メッセージ、またはログ レベルでログの内容を絞り込むには、列見出しにあるフィルタ アイコンをクリックします。
+
すべてのログを表示するには、「*以上*」を選択します。 `Debug`レベル。

. *更新*をクリックします。
. ログの一覧を確認します。
. ログをダウンロードするには、[ダウンロード] をクリックします。
+
ダウンロードされたzipフォルダには、ジョブのログと一般的なログが含まれています。zipされたフォルダの名前は、選択したジョブのIDとタイプで構成されています。



大規模な構成でパフォーマンスを最適化するには、PowerShellコマンドレットを使用して、SnapCenterのログ設定を最小レベルに設定します。

`Set-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`


NOTE: フェイルオーバージョブの終了後に正常性または構成情報にアクセスするには、次のコマンドレットを実行します。 `Get-SmRepositoryConfig` 。



== SnapCenterからのジョブとログの削除

バックアップ、リストア、クローニング、および検証の各ジョブとそのログをSnapCenterから削除することができます。SnapCenterでは、ジョブの成否にかかわらず、削除しないかぎりログは永久に保存されます。ジョブのログを削除することで、ストレージの空きを増やすことができます。

*このタスクについて*

実行中のジョブがないことを確認してください。ジョブIDを指定して特定のジョブを削除するか、期間を指定してその間に実行されたジョブを削除することができます。

ジョブを削除する際、ホストをメンテナンス モードに切り替える必要はありません。

*手順*

. PowerShellを起動します。
. コマンドプロンプトから次のように入力します。 `Open-SMConnection`
. コマンドプロンプトから次のように入力します。 `Remove-SmJobs`
. 左側のナビゲーション ペインで、[*モニター*] をクリックします。
. モニターページで、*ジョブ*をクリックします。
. [Jobs]ページで、ジョブのステータスを確認します。


.関連情報
コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。
