---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: 'SnapCenter の左側のナビゲーション ペインにあるダッシュボードでは、最近のジョブ アクティビティ、アラート、保護の概要、ストレージの効率と使用状況、 SnapCenterジョブのステータス (バックアップ、クローン、復元)、スタンドアロンおよび Windows クラスタ ホストの構成ステータス、 SnapCenterによって管理されるストレージ仮想マシン (SVM) の数、ライセンス容量など、システムの健全性を一目で確認できます。' 
---
= ダッシュボードの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの左側のナビゲーション ペインから、ダッシュボードを使用してシステムの健全性を確認できます。ダッシュボードには、最近のジョブ アクティビティ、アラート、保護の概要、ストレージの効率化と使用状況、SnapCenterのジョブ（バックアップ、クローニング、リストア）のステータス、スタンドアロン / Windowsクラスタ ホストの構成ステータス、SnapCenterで管理しているStorage Virtual Machine（SVM）の数、ライセンス容量などの情報が表示されます。

ダッシュボード ビューに表示される情報は、SnapCenterに現在ログインしているユーザに割り当てられたロールによって異なります。ユーザに表示権限がない情報は表示されないことがあります。

多くの場合、*i* にマウスを合わせると、ディスプレイに関する詳細情報を表示できます。場合によっては、ダッシュボードに表示される情報は、リソース、モニター、レポートなどのSnapCenter GUI ページの詳細なソース情報にリンクされます。



== 最近のジョブ アクティビティ

[Recent Job Activities]タイルには、アクセス可能なバックアップ、リストア、およびクローニング ジョブの最新のジョブ アクティビティが表示されます。この表示内のジョブの状態は、完了、警告、失敗、実行中、キューに登録済み、キャンセル済みのいずれかです。

ジョブにカーソルを合わせると、詳細が表示されます。ジョブ番号をクリックすると[Monitor]ページにリダイレクトされ、その他のジョブ情報を確認できます。そこからジョブの詳細またはログ情報を取得し、そのジョブに固有のレポートを生成できます。

すべてのSnapCenterジョブの履歴を表示するには、[すべて表示] をクリックします。



== アラート

[Alerts]タイルには、ホストおよびSnapCenter Serverに関する未解決の重大アラートと警告アラートについての最新情報が表示されます。

重大アラートと警告アラートの総数がタイル上部に表示されます。重大または警告の合計をクリックすると[Alerts]ページにリダイレクトされ、[Alerts]ページに対応するフィルタが適用されます。

特定のアラートをクリックすると、そのアラートの詳細が表示された[Alerts]ページにリダイレクトされます。画面下部の「すべて表示」をクリックすると、「アラート」ページにリダイレクトされ、すべてのアラートのリストが表示されます。



== 最新の保護サマリ

[Latest Protection Summary]タイルには、アクセス可能なすべてのエンティティの保護ステータスが表示されます。デフォルトでは、すべてのプラグインのステータスが表示されます。Snapshotとしてプライマリ ストレージにバックアップされたリソース、およびSnapMirrorテクノロジとSnapVaultテクノロジを使用してセカンダリ ストレージにバックアップされたリソースのステータス情報が提供されます。セカンダリ ストレージの保護ステータス情報が表示されるかどうかは、選択したプラグインのタイプに基づきます。


NOTE: mirror-vault保護ポリシーを使用している場合、保護サマリのカウンタはSnapMirrorではなくSnapVaultの概要チャートに表示されます。

ドロップダウン メニューからプラグインを選択すると、個々のプラグインの保護ステータスを確認できます。ドーナツグラフは、選択したプラグインの保護対象リソースの割合を示します。ドーナツグラフのスライスをクリックすると、「*レポート* > *プラグイン*」ページにリダイレクトされ、指定したプラグインのすべてのプライマリストレージおよびセカンダリストレージアクティビティの詳細なレポートが表示されます。


IMPORTANT: セカンダリ ストレージに関するレポートはSnapVaultのみに適用されます。SnapMirrorレポートはサポートされません。


NOTE: SAP HANAの場合、Snapshotについては、プライマリ ストレージとセカンダリ ストレージの保護ステータス情報が提供されます。ファイルベースのバックアップについては、プライマリ ストレージの保護ステータスのみが提供されます。

|===
| 保護ステータス | プライマリ ストレージ | セカンダリ ストレージ 


 a| 
失敗
 a| 
バックアップに失敗したリソース グループに属しているエンティティの数
 a| 
セカンダリ デスティネーションへのバックアップの転送に失敗したエンティティの数



 a| 
成功
 a| 
バックアップに成功したリソース グループに属しているエンティティの数
 a| 
セカンダリ デスティネーションへのバックアップの転送に成功したエンティティの数



 a| 
未設定
 a| 
どのリソース グループにも属しておらず、バックアップされていないエンティティの数
 a| 
バックアップをセカンダリ デスティネーションに転送するように設定されていないリソース グループに属しているエンティティの数



 a| 
未開始
 a| 
リソース グループに属しているが、バックアップが実行されていないエンティティの数
 a| 
該当なし。

|===

NOTE: SnapCenter Server 4.2 と以前のバージョンのプラグイン (4.2 より前) を使用してバックアップを作成している場合、「最新の保護の概要」タイルにこれらのバックアップのSnapMirror保護ステータスは表示されません。



== ジョブ

[Jobs]タイルには、アクセス可能なバックアップ、リストア、およびクローニング ジョブの概要が表示されます。ドロップダウン メニューを使用して、レポートの期間をカスタマイズできます。オプションは、過去24時間、過去7日間、および過去30日間です。デフォルトでは、過去7日間に実行されたデータ保護ジョブの情報がレポートされます。

バックアップ、リストア、およびクローニング ジョブの情報がドーナツ チャートに表示されます。ドーナツ チャートのスライスをクリックすると、選択したジョブにフィルタされた[Monitor]ページにリダイレクトされます。

|===
| ジョブ ステータス | 説明 


 a| 
失敗
 a| 
失敗したジョブ数。



 a| 
警告
 a| 
エラーが発生したジョブ数。



 a| 
成功
 a| 
成功したジョブ数。



 a| 
実行中
 a| 
実行中のジョブ数。

|===


== ストレージ

[Storage]タイルには、過去90日間に保護ジョブで使用されたプライマリ ストレージとセカンダリ ストレージ容量が表示されます。傾向を表すグラフとプライマリ ストレージの削減量も表示されます。ストレージ情報は毎日深夜0時に更新されます。

その日の使用容量の合計として、SnapCenterで使用可能なバックアップの総数とそれらのバックアップが占有するサイズがタイル上部に表示されます。1つのバックアップに複数のSnapshotが関連付けられている場合、それらも同じようにカウントされます。これは、プライマリとセカンダリの両方のSnapshotに当てはまります。たとえばバックアップを10個作成し、そのうちの2個はポリシーに基づいて削除され、1個はユーザが削除したとします。この場合、バックアップ数は7個と表示され、それらの7個のバックアップが占有するサイズが表示されます。

プライマリ ストレージのストレージ削減率は、プライマリ ストレージの物理容量に対する論理容量（クローンおよびSnapshotによる削減量とストレージ使用量の合計）の比率です。棒グラフはストレージ削減量を表しています。

線グラフには、過去90日間について、プライマリとセカンダリそれぞれの1日のストレージ使用量が表示されます。グラフにカーソルを合わせると、その日の詳細なデータが表示されます。


NOTE: SnapCenter Server 4.2 と以前のバージョンのプラグイン (4.2 より前) を使用してバックアップを作成する場合、[*ストレージ*] タイルに、バックアップの数、これらのバックアップによって消費されるストレージ、スナップショットの節約、クローンの節約、およびスナップショットのサイズが表示されません。



== 構成

[Configuration]タイルには、SnapCenterで管理しているスタンドアロンとWindowsクラスタのホストについて、アクセス可能なすべてのアクティブなホストのステータス情報がまとめて表示されます。これには、ホストに関連付けられているプラグインのステータス情報も含まれます。

[Hosts]の横にある数字をクリックすると、[ホスト]ページの[管理対象ホスト]セクションにリダイレクトされます。そのページから、選択したホストの詳細情報を取得できます。

さらにこのタイルには、SnapCenterで管理しているアクセス可能なスタンドアロンのONTAP SVMとクラスタのONTAP SVMの合計数が表示されます。[SVM]の横にある数字をクリックすると、[Storage Systems]ページにリダイレクトされます。そのページから、選択したSVMの詳細情報を取得できます。

ホストの設定状態は赤（重大）、黄（警告）、緑（アクティブ）で、それぞれの状態のホストの数が表示されます。ステータス メッセージも表示されます。

|===
| 設定ステータス | 説明 


 a| 
アップグレードが必要
 a| 
サポートされていないプラグインを実行していてアップグレードが必要なホストの数。サポートされていないプラグインは、このバージョンのSnapCenterでは使用できません。



 a| 
移行が必要
 a| 
サポートされていないプラグインを実行していて移行が必要なホストの数。サポートされていないプラグインは、このバージョンのSnapCenterでは使用できません。



 a| 
インストール済みプラグインなし
 a| 
正常に追加されたがプラグインのインストールが必要であるホスト、またはプラグインのインストールに失敗したホストの数。



 a| 
中断
 a| 
スケジュールが中断されてメンテナンス中のホストの数。



 a| 
停止
 a| 
稼働しているがプラグイン サービスが実行されていないホストの数。



 a| 
ホスト停止
 a| 
停止しているか到達できないホストの数。



 a| 
アップグレード可能（オプション）
 a| 
新しいバージョンのプラグイン パッケージにアップグレード可能なホストの数。



 a| 
移行可能（オプション）
 a| 
新しいバージョンのプラグインに移行可能なホストの数。



 a| 
ログ ディレクトリを設定
 a| 
SCSQLでトランザクション ログ バックアップを作成するためにログ ディレクトリの設定が必要なホストの数。



 a| 
VMware プラグインを設定
 a| 
SnapCenter Plug-in for VMware vSphereの追加が必要なホストの数。



 a| 
不明
 a| 
登録は完了しているがインストールが開始されていないホストの数。



 a| 
実行中
 a| 
稼働していてプラグインが実行されているホストの数。SCSQLプラグインの場合は、ログ ディレクトリとハイパーバイザーも設定されている。



 a| 
プラグインをインストール中 / アンインストール中
 a| 
プラグインのインストールまたはアンインストールを実行中のホストの数。

|===