---
permalink: admin/task_manage_rbac.html 
sidebar: sidebar 
keywords: modify RBAC, role, users, groups 
summary: SnapCenterでは、ロール、ユーザ、およびグループを変更できます。 
---
= RBACの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterでは、ロール、ユーザ、およびグループを変更できます。



== ロールの変更

SnapCenterロールを変更して、ユーザやグループを削除したり、関連付けられている権限を変更したりできます。ロールの変更は、ロール全体で使用されている権限を変更または削除する場合に特に便利です。

.開始する前に
「SnapCenterAdmin」ロールでログインする必要があります。


NOTE: SnapCenter Adminロールの権限を変更または削除することはできません。

*手順*

. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. 設定ページで、「*ロール*」をクリックします。
. 「ロール名」フィールドから、変更するロールをクリックします。
. *このロールのすべてのメンバーが他のメンバーのオブジェクトを表示できる* を選択すると、ロールの他のメンバーは、リソース リストを更新した後にボリュームやホストなどのリソースを表示できるようになります。
+
このロールのメンバーに他のメンバーが割り当てられているオブジェクトを表示しない場合は、このオプションを選択解除します。

+

NOTE: このオプションを有効にすると、オブジェクトまたはリソースを作成したユーザと同じロールに属しているユーザにオブジェクトまたはリソースへのアクセスを割り当てる必要がなくなります。

. [Role Details]ページで、必要に応じて権限を変更するかメンバーの割り当てを解除します。
. *送信*をクリックします。




== ユーザとグループの変更

SnapCenterのユーザまたはグループを変更して、ロールやアセットを変更できます。

.開始する前に
SnapCenter管理者としてログインする必要があります。

*手順*

. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ユーザーとアクセス*]をクリックします。
. ユーザー名またはグループ名リストから、変更するユーザーまたはグループをクリックします。
. ユーザまたはグループの詳細ページで、ロールとアセットを変更します。
. *送信*をクリックします。

