---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords: Manage resource groups 
summary: リソース グループに対してさまざまな処理を実行できます。 
---
= リソース グループの管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
リソース グループに対してさまざまな処理を実行できます。

リソース グループに関連して次のタスクを実行できます。

* リソース グループを変更するには、リソース グループを選択し、[*リソース グループの変更*] をクリックして、リソース グループの作成時に指定した情報を編集します。
+

NOTE: リソース グループを変更する際にスケジュールを変更することができます。ただし、スケジュール タイプを変更するには、ポリシーを変更する必要があります。

+

NOTE: リソース グループからリソースを削除した場合は、リソース グループに現在適用されているポリシーに定義されたバックアップ保持の設定が、削除したリソースに引き続き適用されます。

* リソース グループのバックアップを作成する。
* バックアップのクローンを作成する。
+
クローニングは、SQL、Oracle、Windowsの各ファイルシステムのバックアップ、カスタム アプリケーションのバックアップ、およびSAP HANAデータベースのリソースまたはリソース グループのバックアップから実行できます。

* リソース グループのクローンを作成する。
+
この処理がサポートされるのは、SQLリソース グループ（データベースのみを含むもの）だけです。リソース グループのクローニングのスケジュール（クローニング ライフサイクル）を設定することができます。

* リソース グループでスケジュールされている処理が開始されないようにする。
* リソース グループを削除する。




== リソース グループに対する処理の停止および再開

スケジュールされた処理を一時的に無効にして、リソース グループで開始されないように設定できます。無効にした処理は、必要に応じてあとから有効にすることができます。

*手順*

. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. [リソース] ページで、[表示] リストから [リソース グループ] を選択します。
. リソース グループを選択し、[メンテナンス] をクリックします。
. [OK]をクリックします。


メンテナンス モードにしたリソース グループの操作を再開する場合は、リソース グループを選択し、[*実稼働*] をクリックします。



== リソース グループの削除

リソース グループ内のリソースを保護する必要がなくなった場合は、リソース グループを削除することができます。SnapCenterからプラグインを削除する場合は、事前にリソース グループを削除する必要があります。

*このタスクについて*

リソース グループ内のすべてのリソースに対して作成されたすべてのクローンを手動で削除する必要があります。必要に応じて、リソース グループに関連するすべてのバックアップ、メタデータ ポリシー、およびSnapshotを強制的に削除できます。

*手順*

. 左側のナビゲーション ペインで [*リソース*] をクリックし、リストから適切なプラグインを選択します。
. [リソース] ページで、[表示] リストから [リソース グループ] を選択します。
. リソース グループを選択し、[*削除*] をクリックします。
. オプション: リソース グループに関連付けられているすべてのバックアップ、メタデータ、ポリシー、およびスナップショットを削除するには、[*このリソース グループに関連付けられているバックアップを削除し、ポリシーをデタッチする*] チェック ボックスをオンにします。
. [OK]をクリックします。

