---
permalink: protect-postgresql/add-hosts-and-install-plug-in-packages-on-remote-hosts-postgresql.html 
sidebar: sidebar 
keywords: credentials 
summary: 'SnapCenterの[Add Host]ページを使用してホストを追加し、プラグイン パッケージをインストールする必要があります。プラグインは、自動的にリモート ホストにインストールされます。ホストの追加とプラグイン パッケージのインストールは、ホストごとまたはクラスタごとに実行できます。' 
---
= ホストの追加とリモート ホストへのプラグイン パッケージのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterの[Add Host]ページを使用してホストを追加し、プラグイン パッケージをインストールする必要があります。プラグインは、自動的にリモート ホストにインストールされます。ホストの追加とプラグイン パッケージのインストールは、ホストごとに実行できます。

.開始する前に
* SnapCenter Serverホストのオペレーティング システムがWindows 2019で、プラグイン ホストのオペレーティング システムがWindows 2022の場合は、次の手順を実行する必要があります。
+
** Windows Server 2019（OSビルド17763.5936）以降にアップグレードする
** Windows Server 2022（OSビルド20348.2402）以降にアップグレードする


* この処理は、SnapCenter Adminロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが実行する必要があります。
* Windowsホストにプラグインをインストールする際、組み込みでないクレデンシャルを指定する場合や、ユーザがローカル ワークグループに属している場合は、ホストのUACを無効にする必要があります。
* メッセージ キュー サービスが実行中であることを確認する必要があります。
* ホストの管理については、管理に関するドキュメントを参照してください。
* グループ管理サービス アカウント（gMSA）を使用する場合は、管理者権限でgMSAを設定する必要があります。
+
link:../protect-postgresql/configure-gMSA-on-windows-server-2012-or-later.html["Windows Server 2016 以降で PostgreSQL 用のグループ管理サービス アカウントを構成する"]



.タスク概要
* SnapCenter Serverをプラグイン ホストとして別のSnapCenter Serverに追加することはできません。


.手順
. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. 上部の*管理対象ホスト*タブが選択されていることを確認します。
. *[追加]*をクリックします。
. [Hosts]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
ホストタイプ
 a| 
ホストのタイプを選択します。

** Windows
** Linux
+

NOTE: Plug-in for PostgreSQLは、PostgreSQLクライアント ホストにインストールされます。このホストは、WindowsシステムでもLinuxシステムでもかまいません。





 a| 
ホスト名
 a| 
通信ホスト名を入力します。ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。SnapCenterが機能するためには、DNSが適切に設定されている必要があります。そのため、FQDNを入力することを推奨します。



 a| 
Credentials
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。このクレデンシャルには、リモート ホストに対する管理者権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

指定したクレデンシャルの名前にカーソルを合わせると、クレデンシャルの詳細を確認できます。


NOTE: クレデンシャルの認証モードは、[Add Host]ウィザードで指定するホスト タイプによって決まります。

|===
. [Select Plug-ins to Install]セクションで、インストールするプラグインを選択します。
+
REST APIを使用してPlug-in for PostgreSQLをインストールする場合は、バージョンを3.0として渡す必要があります。例：PostgreSQL:3.0

. (オプション) [*その他のオプション*] をクリックします。
+
|===
| フィールド | 操作 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。デフォルトのポート番号は8145です。SnapCenter Serverがカスタム ポートにインストールされている場合は、そのポート番号がデフォルト ポートとして表示されます。


NOTE: プラグインを手動でインストールしてカスタム ポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理が失敗します。



 a| 
Installation Path
 a| 
Plug-in for PostgreSQLは、PostgreSQLクライアント ホストにインストールされます。このホストは、WindowsシステムでもLinuxシステムでもかまいません。

** Windows 用のSnapCenterプラグイン パッケージの場合、デフォルトのパスは C:\Program Files\ NetApp\ SnapCenterです。必要に応じて、パスをカスタマイズできます。
** Linux 用のSnapCenterプラグイン パッケージの場合、デフォルトのパスは /opt/ NetApp/snapcenter です。必要に応じて、パスをカスタマイズできます。




 a| 
Skip preinstall checks
 a| 
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェック ボックスをオンにします。



 a| 
クラスター内のすべてのホストを追加する
 a| 
すべてのクラスタ ノードを追加するには、このチェック ボックスをオンにします。



 a| 
Use group Managed Service Account (gMSA) to run the plug-in services
 a| 
Windowsホストで、グループ管理サービス アカウント（gMSA）を使用してプラグイン サービスを実行する場合は、このチェック ボックスをオンにします。


NOTE: gMSA名をdomainName\accountName$の形式で指定します。


NOTE: gMSAは、SnapCenter Plug-in for Windowsサービスのログオン サービス アカウントとしてのみ使用されます。

|===
. *送信*をクリックします。
+
[Skip prechecks]チェック ボックスを選択していない場合、プラグインをインストールするための要件をホストが満たしているかどうかを検証するためにホストが検証されます。ディスク スペース、RAM、PowerShellのバージョン、.NETのバージョン、場所（Windowsプラグインの場合）、Javaのバージョン（Linuxプラグインの場合）が最小要件に照らして検証されます。最小要件を満たしていない場合、対応するエラーまたは警告メッセージが表示されます。

+
エラーがディスク スペースまたはRAMに関連している場合は、C:\Program Files\NetApp\SnapCenter WebAppにあるweb.configファイルを更新してデフォルト値を変更できます。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HAのセットアップでweb.configファイルを更新する場合は、両方のノードでファイルを更新する必要があります。

. ホスト タイプが Linux の場合は、フィンガープリントを確認し、[確認して送信] をクリックします。
+
クラスタ セットアップでは、クラスタ内の各ノードのフィンガープリントを検証する必要があります。

+

NOTE: 前述の手順で同じホストがSnapCenterに追加され、フィンガープリントが確認された場合でも、フィンガープリントの検証は必須です。

. インストールの進捗状況を監視します。
+
** Windows プラグインの場合、インストールおよびアップグレード ログは次の場所にあります: _C:\Windows\ SnapCenter plugin\Install_<JOBID>\_
** Linux プラグインの場合、インストール ログは次の場所にあります: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Install_<JOBID>.log_、アップグレード ログは次の場所にあります: _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Upgrade_<JOBID>.log_



