---
permalink: protect-postgresql/define-a-backup-strategy-for-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: 'バックアップ ジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを作成するのに役立ちます。サービス レベル アグリーメント (SLA)、復旧時間目標 (RTO)、復旧ポイント目標 (RPO) によって、バックアップ戦略が大きく決まります。' 
---
= PostgreSQLのバックアップ戦略の定義
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップ ジョブを作成する前にバックアップ戦略を定義しておくと、リソースの正常なリストアやクローニングに必要なバックアップを作成するのに役立ちます。バックアップ戦略の大部分は、サービス レベル アグリーメント（SLA）、目標復旧時間（RTO）、および目標復旧時点（RPO）によって決まります。

.タスク概要
SLAとは、求められるサービス レベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対応を定義したものです。RTOは、サービスの停止からビジネス プロセスの復旧までに必要となる時間です。RPOは、障害発生後に通常処理を再開するためにバックアップ ストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLA、RTO、およびRPOは、データ保護戦略に関与します。

.手順
. リソースをバックアップするタイミングを決定します。
. 必要なバックアップ ジョブの数を決定します。
. バックアップの命名方法を決定します。
. Snapshotコピーベースのポリシーを作成してアプリケーションと整合性のあるクラスタのSnapshotをバックアップするかどうかを決定します。
. レプリケーションのためにNetApp SnapMirrorテクノロジを使用するか、または長期保持のためにNetApp SnapVaultテクノロジを使用するかを決定します。
. ソース ストレージ システムおよびSnapMirrorデスティネーションでのSnapshotの保持期間を確認します。
. バックアップ処理の前後にコマンドを実行するかどうかを決定し、実行する場合はプリスクリプトまたはポストスクリプトを用意します。

