---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: Storage Virtual Machine（SVM）上にSMB3共有を設定するには、SnapCenterユーザ インターフェイスまたはPowerShellコマンドレットを使用できます。 
---
= SMB共有の作成と管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Virtual Machine（SVM）上にSMB3共有を設定するには、SnapCenterユーザ インターフェイスまたはPowerShellコマンドレットを使用できます。

|===


| *ベスト プラクティス:* コマンドレットを使用すると、 SnapCenterに用意されているテンプレートを利用して共有構成を自動化できるため、コマンドレットの使用をお勧めします。 
|===
テンプレートには、ボリュームおよび共有の設定に関するベストプラクティスが組み込まれています。テンプレートは、SnapCenter Plug-ins Package for Windowsのインストール フォルダのTemplatesフォルダにあります。


TIP: 必要に応じて、提供されるモデルに従って独自のテンプレートを作成することもできます。カスタム テンプレートを作成する場合は、コマンドレットのドキュメントでパラメータを確認してください。



== SMB共有を作成する

SnapCenterの[Shares]ページを使用して、Storage Virtual Machine（SVM）にSMB3共有を作成できます。

SnapCenterを使用して SMB 共有上のデータベースをバックアップすることはできません。SMBでサポートされるのはプロビジョニングのみです。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[共有] をクリックします。
. *ストレージ仮想マシン*ドロップダウンリストから SVM を選択します。
. *新規*をクリックします。
+
[新しい共有] ダイアログが開きます。

. [新しい共有] ダイアログで、共有を定義します。
+
|===
| フィールド | 操作 


 a| 
説明
 a| 
共有の説明を入力します。



 a| 
シェア名
 a| 
共有の名前を入力します（例：test_share）。

ここで入力した共有の名前はボリューム名としても使用されます。

共有名には次のルールが適用されます。

** UTF-8文字列である必要があります。
** 以下の文字を含めることはできません: 0x00から0x1Fまでの制御文字(両端を含む)、0x22(二重引用符)、および特殊文字 `\ / [ ] : (vertical bar) < > + = ; , ?`




 a| 
パスを共有
 a| 
** フィールドをクリックして、新しいファイル システム パス (例: /) を入力します。
** フィールドをダブルクリックし、既存のファイル システム パスのリストから選択します。


|===
. 入力内容に満足したら、「*OK*」をクリックします。
+
SnapCenter はSVM 上に SMB 共有を作成します。





== SMB共有を削除する

不要になったSMB共有は削除できます。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[共有] をクリックします。
. [共有] ページで、[*ストレージ仮想マシン*] フィールドをクリックして、使用可能なストレージ仮想マシン (SVM) のリストを含むドロップダウンを表示し、削除する共有の SVM を選択します。
. SVM 上の共有リストから、削除する共有を選択し、[削除] をクリックします。
. [共有の削除] ダイアログボックスで、[*OK*] をクリックします。
+
SnapCenter はSVM から SMB 共有を削除します。


