---
permalink: install/concept_create_and_manage_igroups.html 
sidebar: sidebar 
keywords: igroup 
summary: イニシエータ グループ（igroup）を作成して、ストレージ システム上の特定のLUNにアクセスできるホストを指定することができます。SnapCenterを使用して、Windows ホスト上の igroup を作成、名前変更、変更、または削除できます。 
---
= igroupの作成と管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
イニシエータ グループ（igroup）を作成して、ストレージ システム上の特定のLUNにアクセスできるホストを指定することができます。SnapCenterを使用して、Windows ホスト上の igroup を作成、名前変更、変更、または削除できます。



== igroupの作成

SnapCenterを使用して、Windows ホスト上に igroup を作成できます。  igroup を LUN にマップすると、ディスクの作成ウィザードまたはディスクの接続ウィザードで igroup が使用できるようになります。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、*Igroup* をクリックします。
. イニシエーター グループ ページで、[*新規*] をクリックします。
. [igroup の作成] ダイアログ ボックスで、igroup を定義します。
+
|===
| フィールド | 操作 


 a| 
Storage System
 a| 
igroup にマップする LUN の SVM を選択します。



 a| 
ホスト
 a| 
igroupを作成するホストを選択します。



 a| 
グループ名
 a| 
igroupの名前を入力します。



 a| 
イニシエーター
 a| 
イニシエータを選択します。



 a| 
タイプ
 a| 
イニシエータ タイプとして、iSCSI、FCP、または混在（FCPとiSCSI）のいずれかを選択します。

|===
. 入力内容に満足したら、「*OK*」をクリックします。
+
SnapCenter はストレージ システム上に igroup を作成します。





== igroupの名前の変更

SnapCenterを使用して、既存の igroup の名前を変更できます。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、*Igroup* をクリックします。
. [イニシエータ グループ] ページで、[*ストレージ仮想マシン*] フィールドをクリックして使用可能な SVM のリストを表示し、名前を変更する igroup の SVM を選択します。
. SVM の igroup のリストで、名前を変更する igroup を選択し、「名前の変更」をクリックします。
. 「igroup の名前変更」ダイアログ ボックスで、igroup の新しい名前を入力し、「名前の変更」をクリックします。




== igroupの変更

SnapCenter を使用して、既存の igroup に igroup イニシエーターを追加できます。igroupの作成時に追加できるホストは1つだけです。クラスタに対してigroupを作成するには、既存のigroupを変更して他のノードを追加します。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、*Igroup* をクリックします。
. [イニシエータ グループ] ページで、[*ストレージ仮想マシン*] フィールドをクリックして使用可能な SVM のドロップダウン リストを表示し、変更する igroup の SVM を選択します。
. igroup のリストで igroup を選択し、「*igroup にイニシエータを追加*」をクリックします。
. ホストを選択します。
. イニシエーターを選択し、[*OK*] をクリックします。




== igroupを削除する

不要になった igroup は、 SnapCenterを使用して削除できます。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、*Igroup* をクリックします。
. [イニシエータ グループ] ページで、[*ストレージ仮想マシン*] フィールドをクリックして使用可能な SVM のドロップダウン リストを表示し、削除する igroup の SVM を選択します。
. SVM の igroup のリストで、削除する igroup を選択し、[削除] をクリックします。
. 「igroup の削除」ダイアログボックスで、「*OK*」をクリックします。
+
SnapCenter はigroup を削除します。


