---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: データ保護処理を実行する前に、ストレージ接続をセットアップし、SnapCenter ServerとSnapCenterプラグインで使用するクレデンシャルを追加する必要があります。 
---
= ストレージ接続とクレデンシャル
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護処理を実行する前に、ストレージ接続をセットアップし、SnapCenter ServerとSnapCenterプラグインで使用するクレデンシャルを追加する必要があります。



== ストレージ接続

SnapCenter ServerとSnapCenterプラグインは、ストレージ接続を通じてONTAPストレージにアクセスします。SVM接続を設定するには、AutoSupport機能およびイベント管理システム（EMS）機能も設定する必要があります。



== Credentials

* ドメイン管理者または管理者グループの任意のメンバー
+
ドメイン管理者またはSnapCenterプラグインをインストールするシステムの管理者グループの任意のメンバーを指定します。ユーザ名フィールドの有効な形式は次のとおりです。

+
** _NetBIOS\ユーザー名_
** _ドメインFQDN\ユーザー名_
** _ユーザー名@upn_


* ローカル管理者（ワークグループの場合のみ）
+
ワークグループに属するシステムの場合は、SnapCenterプラグインをインストールするシステムに組み込みのローカル管理者を指定します。ユーザ アカウントに昇格された権限がある場合、またはホスト システムでユーザ アクセス制御機能が無効になっている場合は、ローカル管理者グループに属するローカル ユーザ アカウントを指定できます。

+
ユーザー名フィールドの有効な形式は次のとおりです: _UserName_

* 個々のリソース グループのクレデンシャル
+
個々のリソース グループのクレデンシャルを設定する場合で、ユーザ名に完全なadmin権限が割り当てられていない場合は、少なくともリソース グループとバックアップの権限を割り当てる必要があります。


