---
permalink: install/configure_two_way_ssl_linux.html 
sidebar: sidebar 
keywords: security,two-way ssl,configure two-way ssl, linux host 
summary: Linuxホスト上のSnapCenter Serverとプラグインの間の相互通信を保護するために、双方向SSL通信を設定する必要があります。 
---
= Linuxホストでの双方向SSL通信の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linuxホスト上のSnapCenter Serverとプラグインの間の相互通信を保護するために、双方向SSL通信を設定する必要があります。

.開始する前に
* LinuxホストのCA証明書を設定しておく必要があります。
* すべてのプラグイン ホストとSnapCenter Serverで双方向SSL通信を有効にしておく必要があります。


.手順
. *certificate.pem* を _/etc/pki/ca-trust/source/anchors/_ にコピーします。
. Linuxホストの信頼リストに証明書を追加します。
+
** `cp root-ca.pem /etc/pki/ca-trust/source/anchors/`
** `cp certificate.pem /etc/pki/ca-trust/source/anchors/`
** `update-ca-trust extract`


. 証明書が信頼リストに追加されたかどうかを確認します。
`trust list | grep "<CN of your certificate>"`
. SnapCenter *nginx* ファイル内の *ssl_certificate* と *ssl_certificate_key* を更新して再起動します。
+
** `vim /etc/nginx/conf.d/snapcenter.conf`
** `systemctl restart nginx`


. SnapCenter Server GUIリンクを更新します。
. _/<インストール パス>/ NetApp /snapcenter/SnapManagerWeb_ にある * SnapManager .Web.UI.dll.config* と _/<インストール パス>/ NetApp/snapcenter/SMCore_ にある *SMCoreServiceHost.dll.config* の次のキーの値を更新します。
+
** <add key="SERVICE_CERTIFICATE_PATH" value="<certificate.pfx のパス>" />
** <キーを追加="SERVICE_CERTIFICATE_PASSWORD" 値="<パスワード>"/>


. 次のサービスを再起動します。
+
** `systemctl restart smcore.service`
** `systemctl restart snapmanagerweb.service`


. 証明書がSnapManager Web ポートに接続されていることを確認します。
`openssl s_client -connect localhost:8146 -brief`
. 証明書が smcore ポートに接続されていることを確認します。
`openssl s_client -connect localhost:8145 -brief`
. SPLキーストアとエイリアスのパスワードを管理します。
+
.. SPL プロパティ ファイルの *SPL_KEYSTORE_PASS* キーに割り当てられた SPL キーストアのデフォルト パスワードを取得します。
.. キーストアのパスワードを変更します。
`keytool -storepasswd -keystore keystore.jks`
.. すべての秘密鍵エントリのエイリアスのパスワードを変更します。
`keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
.. _spl.properties_ のキー *SPL_KEYSTORE_PASS* の同じパスワードを更新します。
.. サービスを再起動します。


. プラグインのLinuxホストで、SPLプラグインのキーストアにルート証明書と中間証明書を追加します。
+
** `keytool -import -trustcacerts -alias <any preferred alias name> -file <path of root-ca.pem> -keystore <path of keystore.jks mentioned in spl.properties file>`
** `keytool -importkeystore -srckeystore <path of certificate.pfx> -srcstoretype pkcs12 -destkeystore <path of keystore.jks mentioned in spl.properties file> -deststoretype JKS`
+
... keystore.jks 内のエントリを確認します。
`keytool -list -v -keystore <path to keystore.jks>`
... 必要に応じてエイリアスの名前を変更します。
`keytool -changealias -alias "old-alias" -destalias "new-alias" -keypass keypass -keystore </path/to/keystore> -storepass storepas`




. _spl.properties_ ファイルの *SPL_CERTIFICATE_ALIAS* の値を、_keystore.jks_ に保存されている *certificate.pfx* のエイリアスで更新し、SPL サービスを再起動します。 `systemctl restart spl`
. 証明書が smcore ポートに接続されていることを確認します。
`openssl s_client -connect localhost:8145 -brief`

