---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: Windowsホスト上のSnapCenterサイトでCA証明書を設定する必要があります。 
---
= SnapCenterサイトでのCA証明書の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windowsホスト上のSnapCenterサイトでCA証明書を設定する必要があります。

*手順*

. SnapCenterがインストールされているWindows Serverで、IISマネージャを開きます。
. 左側のナビゲーション ペインで、[*接続*] をクリックします。
. サーバーの名前と*サイト*を展開します。
. SSL証明書をインストールするSnapCenterのWebサイトを選択します。
. *アクション* > *サイトの編集* に移動し、*バインド* をクリックします。
. [バインディング] ページで、*https のバインディング*を選択します。
. *編集*をクリックします。
. [SSL certificate]ドロップダウン リストから、最近インポートしたSSL証明書を選択します。
. [OK]をクリックします。
+

NOTE: SnapCenter Scheduler サイト (デフォルト ポート: 8154、HTTPS) は、自己署名証明書で構成されています。このポートはSnapCenter Serverホスト内で通信しており、CA証明書を使用した設定は必須ではありません。ただし、CA証明書の使用が必要な環境の場合は、SnapCenterスケジューラ サイトを使用して手順5から9を繰り返します。




NOTE: 最近導入したCA証明書がドロップダウン メニューに表示されない場合は、CA証明書が秘密鍵に関連付けられているかどうかを確認します。


IMPORTANT: 次のパスを使用して証明書が追加されていることを確認します: *コンソール ルート > 証明書 - ローカル コンピューター > 信頼されたルート証明機関 > 証明書*。
