---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windowsホストは、ストレージ システム上のLUNを仮想ディスクとして認識します。SnapCenterを使用して、FC接続LUNまたはiSCSI接続LUNを作成および設定できます。 
---
= ディスクの作成と管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windowsホストは、ストレージ システム上のLUNを仮想ディスクとして認識します。SnapCenterを使用して、FC接続LUNまたはiSCSI接続LUNを作成および設定できます。

* SnapCenterでサポートされるのは、ベーシック ディスクのみです。ダイナミック ディスクはサポートされていません。
* GPTでは1つのデータ パーティションのみ、MBRではNTFSまたはCSVFSでフォーマットされた1つのボリュームと1つのマウント パスを持つ1つのプライマリ パーティションのみを含めることができます。
* サポートされているパーティション スタイル: GPT、MBR。VMware UEFI VM では、iSCSI ディスクのみがサポートされます。



NOTE: SnapCenterでは、ディスクの名前を変更することはできません。SnapCenterで管理しているディスクの名前が変更された場合、SnapCenterの処理は正常に実行されません。



== ホスト上のディスクの表示

SnapCenterで管理している各Windowsホスト上のディスクを表示できます。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. *ホスト*ドロップダウンリストからホストを選択します。
+
ディスクのリストが表示されます。





== クラスタ ディスクの表示

SnapCenterで管理しているクラスタ上のクラスタ ディスクを表示できます。クラスタ ディスクは、[Hosts]ドロップダウンからクラスタを選択した場合にのみ表示されます。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. *ホスト* ドロップダウン リストからクラスターを選択します。
+
ディスクのリストが表示されます。





== iSCSIセッションの確立

iSCSIを使用してLUNに接続する場合は、LUNを作成して通信を有効にする前に、iSCSIセッションを確立する必要があります。

*始める前に*

* ストレージ システムのノードをiSCSIターゲットとして定義しておく必要があります。
* ストレージ システムで iSCSI サービスを開始する必要があります。 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html["詳細情報"^]


*このタスクについて*

iSCSIセッションは、同じバージョンのIP間（IPv6とIPv6またはIPv4とIPv4）でのみ確立できます。

リンクローカルIPv6アドレスは、iSCSIセッションの管理や、ホストとターゲットの間の通信（ホストとターゲットが両方とも同じサブネット内に存在する場合）に使用できます。

iSCSIイニシエータの名前を変更すると、iSCSIターゲットへのアクセスに影響します。名前を変更した場合、新しい名前が認識されるように、イニシエータがアクセスするターゲットの再設定が必要になることがあります。iSCSIイニシエータの名前を変更した場合、ホストを必ず再起動してください。

ホストに複数の iSCSI インターフェイスがある場合、最初のインターフェイスの IP アドレスを使用してSnapCenterへの iSCSI セッションを確立すると、別の IP アドレスを持つ別のインターフェイスから iSCSI セッションを確立することはできません。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[iSCSI セッション] をクリックします。
. *ストレージ仮想マシン* ドロップダウン リストから、iSCSI ターゲットのストレージ仮想マシン (SVM) を選択します。
. *ホスト*ドロップダウンリストから、セッションのホストを選択します。
. *セッションの確立*をクリックします。
+
セッションの確立ウィザードが表示されます。

. セッションの確立ウィザードで、ターゲットを特定します。
+
|===
| フィールド | 入力する内容 


 a| 
ターゲットノード名
 a| 
iSCSIターゲットのノード名

既存のターゲット ノードがある場合、表示されるノード名は変更できません。



 a| 
ターゲットポータルアドレス
 a| 
ターゲット ネットワーク ポータルのIPアドレス



 a| 
ターゲットポータルポート
 a| 
ターゲット ネットワーク ポータルのTCPポート



 a| 
イニシエーターポータルアドレス
 a| 
イニシエータ ネットワーク ポータルのIPアドレス

|===
. 入力内容に満足したら、「*接続*」をクリックします。
+
SnapCenter はiSCSI セッションを確立します。

. 同じ手順を繰り返して各ターゲットのセッションを確立します。




== FC接続またはiSCSI接続のLUNまたはディスクの作成

Windowsホストは、ストレージ システム上のLUNを仮想ディスクとして認識します。SnapCenterを使用して、FC接続LUNまたはiSCSI接続LUNを作成および設定できます。

SnapCenterの外部でディスクを作成してフォーマットする場合は、NTFSファイルシステムとCSVFSファイルシステムのみがサポートされます。

.開始する前に
* ストレージ システム上にLUN用のボリュームを作成しておく必要があります。
+
このボリュームには、SnapCenterで作成したLUNのみを格納します。

+

NOTE: SnapCenterで作成したクローン ボリュームには、クローンがすでにスプリットされている場合を除き、LUNを作成することはできません。

* ストレージ システムでFCサービスまたはiSCSIサービスを開始しておく必要があります。
* iSCSIを使用している場合は、ストレージ システムとのiSCSIセッションを確立しておく必要があります。
* SnapCenter Plug-ins Package for Windowsをインストールする必要があるのは、ディスクを作成するホストだけです。


*このタスクについて*

* Windows Serverフェイルオーバー クラスタ内のホストで共有する場合を除き、LUNを複数のホストに接続することはできません。
* Cluster Shared Volume（CSV;クラスタ共有ボリューム）を使用したWindows Serverフェイルオーバー クラスタ内のホストでLUNを共有する場合、クラスタ グループを所有するホストにディスクを作成する必要があります。


*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. *ホスト*ドロップダウンリストからホストを選択します。
. *新規*をクリックします。
+
[Create Disk]ウィザードが開きます。

. [LUN Name]ページで、LUNの情報を指定します。
+
|===
| フィールド | 操作 


 a| 
Storage System
 a| 
LUNのSVMを選択します。



 a| 
LUN path
 a| 
*参照* をクリックして、LUN を含むフォルダーの完全なパスを選択します。



 a| 
LUN名
 a| 
LUNの名前を入力します。



 a| 
Cluster size
 a| 
クラスタのLUNのブロック割り当てサイズを選択します。

クラスタのサイズは、オペレーティング システムおよびアプリケーションによって異なります。



 a| 
LUN label
 a| 
必要に応じて、LUNの説明を入力します。

|===
. [Disk Type]ページで、ディスク タイプを選択します。
+
|===
| 選択するオプション | 状況 


 a| 
Dedicated disk
 a| 
LUNにアクセスできるホストは1つだけです。

*リソース グループ* フィールドは無視します。



 a| 
共有ディスク
 a| 
Windows Serverフェイルオーバー クラスタ内のホストでLUNを共有します。

*リソース グループ* フィールドにクラスター リソース グループの名前を入力します。ディスクはフェイルオーバー クラスタ内の1つのホストだけに作成します。



 a| 
Cluster Shared Volume (CSV)
 a| 
CSVを使用するWindows Serverフェイルオーバー クラスタ内のホストでLUNを共有します。

*リソース グループ* フィールドにクラスター リソース グループの名前を入力します。ディスクはクラスタ グループを所有するホストに作成する必要があります。

|===
. [Drive Properties]ページで、ドライブのプロパティを指定します。
+
|===
| プロパティ | 説明 


 a| 
マウントポイントの自動割り当て
 a| 
システム ドライブに基づいて、SnapCenterで自動的にボリューム マウント ポイントを割り当てます。

たとえば、システム ドライブがC:であれば、C:ドライブにボリューム マウント ポイント（C:\scmnpt\）が作成されます。自動割り当ては共有ディスクではサポートされません。



 a| 
Assign drive letter
 a| 
ドロップダウン リストで選択したドライブにディスクをマウントします。



 a| 
Use volume mount point
 a| 
フィールドで指定したドライブ パスにディスクをマウントします。

ボリューム マウント ポイントのルートは、ディスクを作成するホストが所有している必要があります。



 a| 
Do not assign drive letter or volume mount point
 a| 
ディスクをWindowsで手動でマウントする場合に選択します。



 a| 
LUN size
 a| 
LUNサイズ（150MB以上）を指定します。

ドロップダウン リストで単位（MB、GB、またはTB）を選択します。



 a| 
Use thin provisioning for the volume hosting this LUN
 a| 
LUNをシンプロビジョニングします。

シンプロビジョニングでは、ストレージ スペースが必要なときに必要な分だけ割り当てられるため、LUNは使用可能な最大容量まで効率的に拡張されます。

必要になるすべてのLUNストレージに対応できるだけの十分なスペースがボリュームにあることを確認してください。



 a| 
Choose partition type
 a| 
GUIDパーティション テーブルの場合はGPTパーティション、マスター ブート レコードの場合はMBRパーティションを選択します。

MBRパーティションをWindows Serverフェイルオーバー クラスタで使用した場合、ミスアライメントが発生することがあります。


NOTE: Unified Extensible Firmware Interface（UEFI）パーティション ディスクはサポートされていません。

|===
. [Map LUN]ページで、ホストのiSCSIイニシエータまたはFCイニシエータを選択します。
+
|===
| フィールド | 操作 


 a| 
ホスト
 a| 
クラスタ グループ名をダブルクリックし、ドロップダウン リストに表示されたクラスタに属するホストの中から、イニシエータに指定するホストを選択します。

このフィールドは、Windows Serverフェイルオーバー クラスタ内のホストでLUNを共有する場合にのみ表示されます。



 a| 
Choose host initiator
 a| 
*ファイバー チャネル* または *iSCSI* を選択し、ホスト上のイニシエーターを選択します。

FCでマルチパスI/O（MPIO）を使用する場合は、FCイニシエータを複数選択できます。

|===
. [Group Type]ページで、既存のigroupをLUNにマッピングするか新しいigroupを作成するかを指定します。
+
|===
| 選択するオプション | 状況 


 a| 
選択したイニシエータの新しい igroup を作成する
 a| 
選択したイニシエータ用に新しいigroupを作成します。



 a| 
Choose an existing igroup or specify a new igroup for selected initiators
 a| 
選択したイニシエータ用に既存のigroupを指定するか、指定した名前で新しいigroupを作成します。

*igroup 名* フィールドに igroup 名を入力します。既存のigroup名の最初の数文字を入力すると、残りの文字が自動的に入力されます。

|===
. 概要ページで選択内容を確認し、「完了」をクリックします。
+
SnapCenterにより、LUNが作成され、ホスト上の指定したドライブまたはドライブ パスに接続されます。





== ディスクのサイズ変更

ストレージ システムのニーズの変化に応じて、ディスクのサイズを拡張または縮小することができます。

*このタスクについて*

* シンプロビジョニングLUNの場合、ONTAP LUNのジオメトリのサイズが最大サイズとして表示されます。
* シックプロビジョニングLUNの場合、拡張可能なサイズ（ボリューム内の使用可能なサイズ）が最大サイズとして表示されます。
* MBRパーティション方式を使用したLUNの場合、最大サイズは2TBです。
* GPTパーティション方式を使用したLUNの場合、ストレージ システムの最大サイズは16TBです。
* LUNのサイズを変更する前にSnapshotを作成しておくことを推奨します。
* LUNのサイズの変更前に作成されたSnapshotからLUNをリストアすると、SnapCenterによってLUNのサイズがSnapshotのサイズに自動的に変更されます。
+
リストア処理のあと、サイズ変更後にLUNに追加されたデータを、サイズ変更後に作成されたSnapshotからリストアする必要があります。



*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. [Host]ドロップダウン リストからホストを選択します。
+
ディスクのリストが表示されます。

. サイズを変更するディスクを選択し、「サイズ変更」をクリックします。
. [Resize Disk]ダイアログ ボックスで、スライダ ツールを使用してディスクの新しいサイズを指定するか、[Size]フィールドに新しいサイズを入力します。
+

NOTE: サイズを手動で入力した場合は、入力後に[Size]フィールド以外の部分をクリックすると、[Shrink]ボタンまたは[Expand]ボタンが有効になります。また、[MB]、[GB]、または[TB]のいずれかをクリックして単位を指定する必要があります。

. 入力内容に問題がなければ、必要に応じて *縮小* または *拡大* をクリックします。
+
SnapCenterによって、ディスクのサイズが変更されます。





== ディスクの接続

[Connect Disk]ウィザードを使用して、既存のLUNをホストに接続したり、切断されたLUNを再接続したりできます。

.開始する前に
* ストレージ システムでFCサービスまたはiSCSIサービスを開始しておく必要があります。
* iSCSIを使用している場合は、ストレージ システムとのiSCSIセッションを確立しておく必要があります。
* Windows Serverフェイルオーバー クラスタ内のホストで共有する場合を除き、LUNを複数のホストに接続することはできません。
* クラスタ共有ボリューム（CSV）を使用するWindows Serverフェイルオーバー クラスタ内のホスト間でLUNを共有する場合、クラスタ グループを所有するホストにディスクを接続する必要があります。
* Plug-in for Windowsをインストールする必要があるのは、ディスクを接続するホストだけです。


*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. *ホスト*ドロップダウンリストからホストを選択します。
. *接続*をクリックします。
+
[Connect Disk]ウィザードが開きます。

. [LUN Name]ページで、接続するLUNの情報を指定します。
+
|===
| フィールド | 操作 


 a| 
Storage System
 a| 
LUNのSVMを選択します。



 a| 
LUN path
 a| 
*参照* をクリックして、LUN を含むボリュームの完全なパスを選択します。



 a| 
LUN名
 a| 
LUNの名前を入力します。



 a| 
Cluster size
 a| 
クラスタのLUNのブロック割り当てサイズを選択します。

クラスタのサイズは、オペレーティング システムおよびアプリケーションによって異なります。



 a| 
LUN label
 a| 
必要に応じて、LUNの説明を入力します。

|===
. [Disk Type]ページで、ディスク タイプを選択します。
+
|===
| 選択するオプション | 状況 


 a| 
Dedicated disk
 a| 
LUNにアクセスできるホストは1つだけです。



 a| 
共有ディスク
 a| 
Windows Serverフェイルオーバー クラスタ内のホストでLUNを共有します。

ディスクはフェイルオーバー クラスタ内の1つのホストだけに接続します。



 a| 
Cluster Shared Volume (CSV)
 a| 
CSVを使用するWindows Serverフェイルオーバー クラスタ内のホストでLUNを共有します。

ディスクはクラスタ グループを所有するホストに接続する必要があります。

|===
. [Drive Properties]ページで、ドライブのプロパティを指定します。
+
|===
| プロパティ | 説明 


 a| 
自動割り当て
 a| 
システム ドライブに基づいて、SnapCenterで自動的にボリューム マウント ポイントを割り当てます。

たとえば、システム ドライブがC:であれば、C:ドライブにボリューム マウント ポイント（C:\scmnpt\）が作成されます。自動割り当ては共有ディスクではサポートされません。



 a| 
Assign drive letter
 a| 
ドロップダウン リストで選択したドライブにディスクをマウントします。



 a| 
Use volume mount point
 a| 
フィールドで指定したドライブ パスにディスクをマウントします。

ボリューム マウント ポイントのルートは、ディスクを作成するホストが所有している必要があります。



 a| 
Do not assign drive letter or volume mount point
 a| 
ディスクをWindowsで手動でマウントする場合に選択します。

|===
. [Map LUN]ページで、ホストのiSCSIイニシエータまたはFCイニシエータを選択します。
+
|===
| フィールド | 操作 


 a| 
ホスト
 a| 
クラスタ グループ名をダブルクリックし、ドロップダウン リストに表示されたクラスタに属するホストの中から、イニシエータに指定するホストを選択します。

このフィールドは、Windows Serverフェイルオーバー クラスタ内のホストでLUNを共有する場合にのみ表示されます。



 a| 
Choose host initiator
 a| 
*ファイバー チャネル* または *iSCSI* を選択し、ホスト上のイニシエーターを選択します。

FCでMPIOを使用している場合は、FCイニシエータを複数選択できます。

|===
. [Group Type]ページで、既存のigroupをLUNにマッピングするか新しいigroupを作成するかを指定します。
+
|===
| 選択するオプション | 状況 


 a| 
選択したイニシエータの新しい igroup を作成する
 a| 
選択したイニシエータ用に新しいigroupを作成します。



 a| 
Choose an existing igroup or specify a new igroup for selected initiators
 a| 
選択したイニシエータ用に既存のigroupを指定するか、指定した名前で新しいigroupを作成します。

*igroup 名* フィールドに igroup 名を入力します。既存のigroup名の最初の数文字を入力すると、残りの文字が自動的に入力されます。

|===
. 概要ページで選択内容を確認し、「完了」をクリックします。
+
SnapCenterにより、ホスト上の指定したドライブまたはドライブ パスにLUNが接続されます。





== ディスクの切断

LUN の内容に影響を与えずにホストから LUN を切断できますが、1 つの例外があります: クローンを分割する前に切断すると、クローンの内容が失われます。

.開始する前に
* LUNを使用しているアプリケーションがないことを確認します。
* LUNが監視ソフトウェアで監視されていないことを確認します。
* LUNが共有されている場合は、LUNからクラスタ リソースの依存関係を解除し、クラスタ内のすべてのノードの電源がオンで正常に動作しており、SnapCenterからアクセスできることを確認します。


*このタスクについて*

SnapCenterで作成したFlexCloneボリュームのLUNを切断した場合、そのボリュームに他のLUNが接続されていなければSnapCenterはボリュームも削除します。この場合、LUNが切断される前に、FlexCloneボリュームが削除される可能性があることを警告するメッセージがSnapCenterに表示されます。

FlexCloneボリュームが自動で削除されないようにするには、最後のLUNを切断する前にボリュームの名前を変更します。ボリュームの名前を変更する際は、最後の1文字だけでなく複数の文字を変更してください。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. *ホスト*ドロップダウンリストからホストを選択します。
+
ディスクのリストが表示されます。

. 切断するディスクを選択し、「切断」をクリックします。
. [ディスクの切断] ダイアログ ボックスで、[*OK*] をクリックします。
+
SnapCenterによってディスクが切断されます。





== ディスクの削除

不要になったディスクは削除できます。削除したディスクは復元できません。

*手順*

. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. [ホスト] ページで、[ディスク] をクリックします。
. *ホスト*ドロップダウンリストからホストを選択します。
+
ディスクのリストが表示されます。

. 削除するディスクを選択し、「削除」をクリックします。
. [ディスクの削除] ダイアログボックスで、[*OK*] をクリックします。
+
SnapCenterによってディスクが削除されます。


