---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: ソフトウェア プラットフォームのセキュリティ イベントと、そのプラットフォーム上で実行されているすべてのソフトウェアをログに記録するように構成できます。 
---
= 監査ログの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監査ログは、SnapCenter Serverのすべてのアクティビティについて生成されます。デフォルトでは、監査ログはデフォルトのインストール場所 _C:\Program Files\ NetApp\ SnapCenter WebApp\audit\_ に保存されます。

監査ログのセキュリティは、すべての監査イベントについて、不正な変更ができないようにデジタル署名が付いたダイジェストを生成することで確保されます。生成されたダイジェストは、独立した監査チェックサム ファイルに保持され、コンテンツの整合性を確認するために定期的な整合性チェックが実行されます。

「SnapCenterAdmin」ロールでログインする必要があります。

.タスク概要
* アラートは、次のシナリオで送信されます。
+
** 監査ログの整合性チェックのスケジュールまたはsyslogサーバが有効化 / 無効化された
** 監査ログの整合性チェック、監査ログ、またはsyslogサーバ ログに問題がある
** ディスク スペースが不足している


* 整合性チェックに失敗した場合のみ、Eメールが送信されます。
* 監査ログのディレクトリと監査チェックサム ログのディレクトリのパスは、両方とも変更する必要があります。片方だけを変更することはできません。
* 監査ログのディレクトリと監査チェックサム ログのディレクトリのパスを変更すると、以前の場所にある監査ログに対して整合性チェックを実行できなくなります。
* 監査ログのディレクトリと監査チェックサム ログのディレクトリのパスは、SnapCenter Serverのローカル ドライブ上である必要があります。
+
共有ドライブやネットワーク マウント ドライブは、サポートされていません。

* syslogサーバの設定でUDPプロトコルを使用している場合、ポートが停止している、または使用できないことによるエラーは、SnapCenterでエラーまたはアラートとして取得できません。
* 監査ログを構成するには、Set-SmAuditSettings コマンドと Get-SmAuditSettings コマンドを使用できます。
+
コマンドレットで使用できるパラメータとその説明は、Get-Help command_nameを実行して確認できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^] 。



.手順
. *設定*ページで、*設定* > *グローバル設定* > *監査ログ設定*に移動します。
. [Audit log]セクションで、詳細を入力します。
. *監査ログディレクトリ*と*監査チェックサムログディレクトリ*を入力します。
+
.. [Maximum file size]を入力します。
.. [Maximum log files]を入力します。
.. アラートが送信されるディスク スペース使用量を割合（%）で入力します。


. (オプション) *UTC 時間のログ* を有効にします。
. (オプション) *監査ログ整合性チェックスケジュール* を有効にし、オンデマンド整合性チェックを実行するために *整合性チェックの開始* をクリックします。
+
*Start-SmAuditIntegrityCheck* コマンドを実行して、オンデマンドの整合性チェックを開始することもできます。

. （オプション）[Forwarded audit logs to remote syslog server]を有効にし、syslogサーバの詳細を入力します。
+
TLS 1.2プロトコルについては、syslogサーバから「信頼されたルート」に証明書をインポートする必要があります。

+
.. syslogサーバのホストを入力します。
.. syslogサーバのポートを入力します。
.. syslogサーバのプロトコルを入力します。
.. RFCの形式を入力します。


. *保存*をクリックします。
. *モニター* > *ジョブ* をクリックすると、監査整合性チェックとディスク容量チェックを確認できます。

