---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space, storage system, reclaim 
summary: ファイルが削除または変更された場合、NTFSはLUN上の使用可能なスペースを追跡しますが、この情報はストレージ システムには報告されません。新たに解放されたブロックがストレージで空きスペースとしてマークされるようにするには、Plug-in for Windowsホストでスペース再生用のPowerShellコマンドレットを実行します。 
---
= ストレージ システムでのスペースの再生
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファイルが削除または変更された場合、NTFSはLUN上の使用可能なスペースを追跡しますが、この情報はストレージ システムには報告されません。新たに解放されたブロックがストレージで空きスペースとしてマークされるようにするには、Plug-in for Windowsホストでスペース再生用のPowerShellコマンドレットを実行します。

リモートのプラグイン ホストでコマンドレットを実行する場合は、SnapCenterOpen-SMConnectionコマンドレットを実行してSnapCenter Serverへの接続を確立する必要があります。

.開始する前に
* リストア処理を実行する前に必ずスペース再生プロセスを完了しておく必要があります。
* Windows Serverフェイルオーバー クラスタ内のホストでLUNを共有している場合は、クラスタ グループを所有するホストでスペース再生を実行する必要があります。
* ストレージのパフォーマンスを最適化するには、できるだけ頻繁にスペース再生を実行します。
+
NTFSファイルシステム全体がスキャンされたことを確認してください。



*このタスクについて*

* スペース再生には時間がかかり、CPUを大量に消費するため、通常はストレージ システムとWindowsホストがあまり使用されていない時間帯に実行することを推奨します。
* 使用可能なほぼすべてのスペースが再生されますが、100%ではありません。
* スペース再生の実行中にディスクのデフラグは実行しないでください。
+
再生プロセスの実行速度が低下する可能性があります。



*ステップ*

アプリケーション サーバのコマンド プロンプトで、次のPowerShellコマンドを入力します。

`Invoke-SdHostVolumeSpaceReclaim -Path drive_path`

drive_pathは、LUNにマッピングされているドライブのパスです。
