---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM, ASA r2 systems 
summary: データ保護およびプロビジョニング操作を実行するには、 SnapCenter がONTAPストレージにアクセスできるようにするストレージ システムをセットアップする必要があります。スタンドアロンの SVM を追加するか、複数の SVM で構成されるクラスターを追加できます。 
---
= ストレージシステムを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護およびプロビジョニング操作を実行するには、 SnapCenter がONTAPストレージ、 ASA r2 システム、またはAmazon FSx for NetApp ONTAPにアクセスできるようにストレージ システムをセットアップする必要があります。

スタンドアロンのSVMを追加するか、複数のSVMで構成されるクラスタを追加できます。Amazon FSx for NetApp ONTAPを使用している場合は、fsxadminアカウントを使用して複数のSVMで構成されるFSx管理LIFを追加したり、SnapCenterでFSx SVMを追加したりできます。

.開始する前に
* ストレージ接続を作成するには、Infrastructure Adminロールの権限が必要です。
* プラグインのインストールが実行中でないことを確認してください。
+
ストレージ システム接続の追加中は、ホスト プラグインのインストールが進行中であってはなりません。ホスト キャッシュが更新されず、 SnapCenter GUI にデータベースのステータスが「バックアップに使用できません」または「 NetAppストレージ上にありません」と表示される可能性があるためです。

* ストレージ システムの名前は一意である必要があります。
+
SnapCenterでは、別々のクラスタに属している場合でも、複数のストレージ システムに同じ名前を付けることはサポートされません。SnapCenterでサポートする各ストレージ システムには、一意な名前とデータLIFの一意なIPアドレスが必要です。



*このタスクについて*

* ストレージ システムの設定時に、イベント管理システム（EMS）とAutoSupportの機能を有効にすることもできます。AutoSupportツールは、システムの健全性に関するデータを収集し、そのデータをシステムのトラブルシューティング用にNetAppテクニカル サポートに自動的に送信します。
+
これらの機能を有効にすると、リソースが保護されたとき、リストアやクローンの処理が完了したとき、または処理が失敗したときに、SnapCenterからストレージ システムにAutoSupport情報が、ストレージ システムのsyslogにEMSメッセージが送信されます。

* SnapMirrorデスティネーションまたはSnapVaultデスティネーションにSnapshotをレプリケートする場合は、デスティネーションSVM / クラスタとソースSVM / クラスタへのストレージ システム接続をセットアップする必要があります。



NOTE: ストレージ システムのパスワードを変更すると、スケジュール済みジョブ、オンデマンド バックアップ、およびリストア処理が失敗する場合があります。ストレージ システムのパスワードを変更した後、[ストレージ] タブで [*変更*] をクリックしてパスワードを更新できます。

*手順*

. 左側のナビゲーション ペインで、[*ストレージ システム*] をクリックします。
. ストレージ システム ページで、[*新規*] をクリックします。
. [Add Storage System]ページで、次の情報を入力します。
+
|===
| フィールド | 操作 


 a| 
Storage System
 a| 
ストレージ システムの名前またはIPアドレスを入力します。


NOTE: ストレージ システム名（ドメイン名は含めない）は15文字以下にする必要があります。解決可能な名前を使用してください。15文字を超える名前のストレージ システム接続を作成する場合は、Add-SmStorageConnectionPowerShellコマンドレットを使用します。


NOTE: MetroCluster 構成（MCC）のストレージ システムでノンストップ オペレーションを実現するには、ローカル クラスタとピア クラスタの両方を登録することを推奨します。

SnapCenterでは、別々のクラスタに属している場合でも、複数のSVMに同じ名前を付けることはサポートされません。SnapCenterでサポートするSVMには、すべて一意の名前を付ける必要があります。


NOTE: SnapCenterにストレージ接続を追加したあとで、ONTAPを使用してSVMまたはクラスタの名前を変更しないでください。


NOTE: SVMに短縮名またはFQDNを追加した場合は、その名前がSnapCenterとプラグイン ホストの両方から解決できる必要があります。



 a| 
ユーザー名/パスワード
 a| 
ストレージ システムへのアクセスに必要な権限を持つストレージ ユーザのクレデンシャルを入力します。



 a| 
Event Management System (EMS) & AutoSupport Settings
 a| 
保護が適用されたとき、リストア処理が完了したとき、または処理が失敗したときにEMSメッセージをストレージ システムのsyslogに送信、またはAutoSupportメッセージをストレージ システムに送信するには、該当するチェックボックスをオンにします。

*失敗した操作に関するAutoSupport通知をストレージ システムに送信する* チェックボックスをオンにすると、 AutoSupport通知を有効にするには EMS メッセージングが必要であるため、* SnapCenter Server イベントを syslog に記録する* チェックボックスもオンになります。

|===
. プラットフォーム、プロトコル、ポート、タイムアウトに割り当てられたデフォルト値を変更する場合は、[*その他のオプション*] をクリックします。
+
.. [Platform]で、ドロップダウン リストから次のいずれかのオプションを選択します。
+
SVM がバックアップ関係におけるセカンダリ ストレージ システムである場合は、[セカンダリ] チェックボックスをオンにします。  *セカンダリ* オプションを選択すると、 SnapCenter はライセンス チェックをすぐに実行しません。

+
SnapCenterでSVMを追加した場合は、ドロップダウンからプラットフォーム タイプを手動で選択する必要があります。

.. [Protocol]で、SVMまたはクラスタのセットアップ時に設定したプロトコル（通常はHTTPS）を選択します。
.. ストレージ システムが受け入れるポートを入力します。
+
通常はデフォルト ポート443を使用します。

.. 接続を試行する時間（秒）を入力します。
+
デフォルト値は60秒です。

.. SVM に複数の管理インターフェイスがある場合は、[*優先 IP*] チェックボックスをオンにし、SVM 接続の優先 IP アドレスを入力します。
.. *保存*をクリックします。


. *送信*をクリックします。


*結果*

[ストレージ システム] ページの [*タイプ*] ドロップダウンから、次のいずれかのアクションを実行します。

* 追加されたすべての SVM を表示する場合は、* ONTAP SVM* を選択します。
+
FSx SVMを追加した場合は、ここにFSx SVMが表示されます。

* 追加されたすべてのクラスタを表示する場合は、* ONTAPクラスタ* を選択します。
+
fsxadminを使用してFSxクラスタを追加した場合は、ここにFSxクラスタが表示されます。

+
クラスタ名をクリックすると、そのクラスタに含まれるすべてのSVMが[Storage Virtual Machine]セクションに表示されます。

+
ONTAP GUI を使用してONTAPクラスタに新しい SVM が追加された場合は、[再検出] をクリックして新しく追加された SVM を表示します。



*終わったら*

SnapCenterがアクセスできるすべてのストレージ システムからEメール通知を送信するには、クラスタ管理者が各ストレージ システム ノードでAutoSupportを有効にする必要があります。ストレージ システムのコマンドラインで次のコマンドを実行してください。

`autosupport trigger modify -node nodename -autosupport-message client.app.info -to enable -noteto enable`


NOTE: Storage Virtual Machine（SVM）管理者にはAutoSupportへのアクセス権はありません。
