---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: バックアップする Unix ファイル システムのバックアップ ポリシーを作成します。 
---
= UNIXファイルシステムのバックアップ ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してUNIXファイルシステムをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。バックアップ ポリシーとは、バックアップをどのように管理し、スケジューリングし、保持するかを定める一連のルールです。レプリケーション、スクリプト、バックアップ タイプの設定を指定することもできます。ポリシーを作成することで、別のリソースやリソース グループでポリシーを再利用したい場合に時間を節約できます。

.開始する前に
* SnapCenterのインストール、ホストの追加、ファイルシステムの検出、ストレージ システム接続の作成などのタスクを実行して、データ保護の準備をしておく必要があります。
* Snapshotをミラー セカンダリ ストレージまたはバックアップ セカンダリ ストレージにレプリケートするユーザには、SnapCenter管理者がソースとデスティネーションの両方のボリューム用にSVMを割り当てる必要があります。
* SnapMirrorアクティブ同期に固有の前提条件と制限事項を確認します。詳細については、 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirrorアクティブ同期のオブジェクト数の制限"] 。


.タスク概要
* SnapLock
+
** [Retain the backup copies for a specific number of days]オプションを選択した場合は、SnapLockの保持期間をここで指定した保持日数以下にする必要があります。
+
Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、ポリシーで指定した数よりも多くのSnapshotが保持される可能性があります。

+
ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。





.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. ドロップダウンリストから*Unix ファイル システム*を選択します。
. *新規*をクリックします。
. 「名前」ページで、ポリシー名と詳細を入力します。
. 「バックアップとレプリケーション」ページで、次のアクションを実行します。
+
.. バックアップ設定を指定します。
.. *オンデマンド*、*時間別*、*日次*、*週次*、または*月次*を選択して、スケジュールの頻度を指定します。
.. [セカンダリ レプリケーション オプションの選択] セクションで、次のセカンダリ レプリケーション オプションの 1 つまたは両方を選択します。


+
|===
| フィールド | 操作 


 a| 
Update SnapMirror after creating a local Snapshot copy
 a| 
別のボリュームにバックアップ セットのミラー コピーを作成する場合（SnapMirrorレプリケーション）は、このフィールドを選択します。

このオプションは、SnapMirrorアクティブ同期に対して有効にする必要があります。



 a| 
Update SnapVault after creating a local Snapshot copy
 a| 
ディスクツーディスクのバックアップ レプリケーション（SnapVaultバックアップ）を実行する場合は、このオプションを選択します。



 a| 
Error retry count
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
. [保持] ページで、[バックアップとレプリケーション] ページで選択したバックアップ タイプとスケジュール タイプの保持設定を指定します。
+
|===


| 状況 | 操作 


 a| 
特定の数のSnapshotを保持
 a| 
*保持するコピー*を選択し、保持するスナップショットの数を指定します。

Snapshotの数が指定した数を超えると、古いものから順にSnapshotが削除されます。


NOTE: 最大保持値は 1018 です。保持数を、使用しているONTAPバージョンがサポートする値よりも大きい値に設定すると、バックアップが失敗します。


IMPORTANT: SnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗することがあります。



 a| 
Snapshotを特定の日数だけ保持
 a| 
*コピーの保持期間*を選択し、スナップショットを削除する前に保持する日数を指定します。



 a| 
スナップショットコピーのロック期間
 a| 
*スナップショット コピーのロック期間* を選択し、期間を日数、月数、または年数で指定します。

SnapLock保持期間は100年未満にする必要があります。

|===
. ポリシーラベルを選択します。
+

NOTE: リモート レプリケーションのプライマリ スナップショットにSnapMirrorラベルを割り当てることで、プライマリ スナップショットによってスナップショット レプリケーション操作をSnapCenterからONTAPセカンダリ システムにオフロードできるようになります。これは、ポリシー ページでSnapMirrorまたはSnapVaultオプションを有効にしなくても実行できます。

. [Script]ページで、バックアップ処理の前またはあとに実行するプリスクリプトまたはポストスクリプトのパスと引数を入力します。
+

NOTE: _ /opt/ NetApp/snapcenter/scc/etc/allowed_commands.config_ パスからプラグイン ホスト上で使用可能なコマンド リストにコマンドが存在するかどうかを確認する必要があります。

+
スクリプトのタイムアウト値を指定することもできます。デフォルト値は60秒です。

. 概要を確認し、[完了] をクリックします。

