---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: SnapCenterを使用して IBM Db2 データベース リソースをバックアップする前に、バックアップするリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。バックアップ ポリシーとは、バックアップをどのように管理し、スケジューリングし、保持するかを定める一連のルールです。 
---
= IBM Db2のバックアップ ポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してIBM Db2のリソースをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。バックアップ ポリシーとは、バックアップをどのように管理し、スケジューリングし、保持するかを定める一連のルールです。

.開始する前に
* バックアップ戦略を定義しておく必要があります。
+
詳細については、IBM Db2データベースのデータ保護戦略の定義に関する情報を参照してください。

* SnapCenterのインストール、ホストの追加、ストレージ システム接続の作成、リソースの追加などのタスクを実行して、データ保護の準備をしておく必要があります。
* ユーザがSnapshotをミラーまたはバックアップにレプリケートする場合は、ソース ボリュームとデスティネーション ボリューム両方のSVMをSnapCenter管理者がユーザに割り当てる必要があります。
+
ポリシーで、レプリケーション、スクリプト、アプリケーション設定を指定することもできます。それらのオプションを指定しておくことで、別のリソース グループにポリシーを再利用して時間を節約することができます。



.タスク概要
* SnapLock
+
** [Retain the backup copies for a specific number of days]オプションを選択した場合は、SnapLockの保持期間をここで指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、ポリシーで指定した数よりも多くのSnapshotが保持される可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。




.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. *新規*をクリックします。
. 「名前」ページで、ポリシー名と詳細を入力します。
. [Policy type]ページで、次の手順を実行します。
+
.. ストレージ タイプを選択します。
.. *カスタム バックアップ設定* セクションで、キーと値の形式でプラグインに渡す必要がある特定のバックアップ設定を指定します。
+
プラグインに渡すキーと値のペアを複数指定することができます。



. スナップショットとレプリケーション ページで、次のアクションを実行します。
+
.. *オンデマンド*、*時間別*、*日次*、*週次*、または*月次*を選択して、スケジュールの頻度を指定します。
+

NOTE: リソース グループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、頻度）を指定することができます。これにより、ポリシーとバックアップ間隔が同じである複数のリソース グループを作成できますが、各ポリシーに異なるバックアップ スケジュールを割り当てることもできます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間 (DST) 中はスケジュールは実行されません。

.. スナップショット設定セクションで、次のアクションを実行します。
+
|===
| 状況 | 操作 


 a| 
特定の数のSnapshotを保持
 a| 
*保持するコピー*を選択し、保持するスナップショットの数を指定します。

Snapshotの数が指定した数を超えると、古いものから順にSnapshotが削除されます。



 a| 
Snapshotを特定の日数だけ保持
 a| 
*コピーの保持期間*を選択し、スナップショットを削除する前に保持する日数を指定します。



 a| 
スナップショットコピーのロック期間
 a| 
*スナップショット コピーのロック期間* を選択し、日、月、または年を指定します。

SnapLock保持期間は100年未満にする必要があります。

|===
+

IMPORTANT: SnapshotコピーベースのバックアップでSnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗することがあります。

.. ポリシーラベルを指定します。
+
リモート レプリケーションのプライマリ スナップショットにSnapMirrorラベルを割り当てることで、プライマリ スナップショットによってスナップショット レプリケーション操作をSnapCenterからONTAPセカンダリ システムにオフロードできるようになります。これは、ポリシー ページでSnapMirrorまたはSnapVaultオプションを有効にしなくても実行できます。



. [セカンダリ レプリケーション オプションの選択] セクションで、次のセカンダリ レプリケーション オプションの 1 つまたは両方を選択します。
+
|===
| フィールド | 操作 


 a| 
Update SnapMirror after creating a local Snapshot copy
 a| 
別のボリュームにバックアップ セットのミラー コピーを作成する場合（SnapMirrorレプリケーション）は、このフィールドを選択します。

このオプションは、SnapMirrorアクティブ同期に対して有効にする必要があります。



 a| 
Update SnapVault after creating a local Snapshot copy
 a| 
ディスクツーディスクのバックアップ レプリケーション（SnapVaultバックアップ）を実行する場合は、このオプションを選択します。



 a| 
Error retry count
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
+

NOTE: セカンダリ ストレージでSnapshotの上限に達しないように、ONTAPでセカンダリ ストレージのSnapMirror保持ポリシーを設定する必要があります。

. 概要を確認し、[完了] をクリックします。

