---
permalink: protect-db2/host-requirements-to-install-snapcenter-plug-in-package-for-linux.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: SnapCenter Plug-ins Package for Linuxをインストールする前に、ホスト システムのスペースとサイジングに関する基本的な要件を理解しておく必要があります。 
---
= SnapCenter Plug-ins Package for Linuxをインストールするホストの要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-ins Package for Linuxをインストールする前に、ホスト システムのスペースとサイジングに関する基本的な要件を理解しておく必要があります。

|===
| 項目 | 要件 


 a| 
オペレーティング システム
 a| 
* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server（SLES）


サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"] 。



 a| 
ホスト上のSnapCenterプラグインに必要な最小RAM
 a| 
1 GB



 a| 
ホスト上のSnapCenterプラグインに必要なインストールおよびログの最小スペース
 a| 
2 GB


NOTE: 十分なディスク スペースを割り当てて、ログ フォルダによるストレージ消費を監視する必要があります。必要なログ スペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスク スペースがない場合は、最近実行した処理のログが作成されません。



 a| 
必要なソフトウェア パッケージ
 a| 
Java 11 Oracle JavaおよびOpenJDK

Javaを最新バージョンにアップグレードした場合は、/var/opt/snapcenter/spl/etc/spl.propertiesにあるJAVA_HOMEオプションが正しいJavaバージョンと正しいパスに設定されていることを確認する必要があります。

サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"] 。

|===