---
permalink: protect-db2/how-resources-resource-groups-and-policies-are-used-for-protecting-ibm-db2.html 
sidebar: sidebar 
keywords: IBM DB2 
summary: SnapCenterを使用する前に、実行するバックアップ、クローニング、リストアの各処理に関連する基本的な概念を理解しておくと役立ちます。ここでは、これらの処理で扱うリソース、リソース グループ、およびポリシーについて説明します。 
---
= IBM Db2の保護におけるリソース、リソース グループ、ポリシーの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用する前に、実行するバックアップ、クローニング、リストアの各処理に関連する基本的な概念を理解しておくと役立ちます。ここでは、これらの処理で扱うリソース、リソース グループ、およびポリシーについて説明します。

* リソースとは、一般にはSnapCenterでバックアップまたはクローニングするIBM Db2データベースのことです。
* SnapCenterリソース グループは、ホスト上のリソースの集まりです。
+
リソース グループに対して処理を実行すると、リソース グループに指定したスケジュールに従って、リソース グループに定義されているリソースに対して処理が実行されます。

+
単一のリソースまたはリソース グループをオンデマンドでバックアップすることができます。また、スケジュールされたバックアップを単一リソースおよびリソース グループに対して実行することもできます。

* ポリシーは、バックアップ頻度、レプリケーション、スクリプトといった、データ保護処理の特性を指定するものです。
+
リソース グループを作成するときに、そのグループに対して1つ以上のポリシーを選択します。単一リソースに対してオンデマンドでバックアップを実行するときにもポリシーを選択できます。



リソース グループでは、保護する対象と保護するタイミング（日時）を定義できます。ポリシーでは、保護する方法を定義できます。たとえば、すべてのデータベースをバックアップする場合は、ホストのすべてのデータベースを含むリソース グループを作成します。このリソース グループに、日次ポリシーと毎時ポリシーの2つのポリシーを適用します。リソース グループを作成してポリシーを適用する際に、フル バックアップを1日1回実行するようにリソース グループを設定できます。
