---
permalink: protect-nsp/add_hosts_and_install_plug_in_packages_on_remote_hosts.html 
sidebar: sidebar 
keywords: add hostsNetApp supported plug-ins, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: 'SnapCenterの[Add Host]ページを使用してホストを追加し、プラグイン パッケージをインストールする必要があります。プラグインは、自動的にリモート ホストにインストールされます。ホストの追加とプラグイン パッケージのインストールは、ホストごとまたはクラスタごとに実行できます。' 
---
= ホストの追加とリモート ホストへのプラグイン パッケージのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加するには、 SnapCenter のホストの追加ページを使用し、プラグイン パッケージをインストールする必要があります。プラグインは、自動的にリモート ホストにインストールされます。ホストの追加とプラグイン パッケージのインストールは、ホストごとまたはクラスタごとに実行できます。

.開始する前に
* この操作は、SnapCenter Adminロールなど、プラグインのインストールとアンインストールの権限のあるロールが割り当てられているユーザが実行する必要があります。
* メッセージ キュー サービスが実行中であることを確認する必要があります。
* グループ管理サービス アカウント（gMSA）を使用する場合は、管理者権限でgMSAを設定する必要があります。
+
link:configure_gMSA_on_windows_server_2012_or_later.html["Windows Server 2016以降でカスタム アプリケーションのグループ管理サービス アカウントを設定する"]

* Windows ホストの場合は、必ず Windows 用SnapCenterプラグインを選択する必要があります。


.タスク概要
* SnapCenter Serverをプラグイン ホストとして別のSnapCenter Serverに追加することはできません。
* クラスタ（WSFC）にプラグインをインストールする場合、プラグインはクラスタのすべてのノードにインストールされます。


.手順
. 左側のナビゲーション ペインで、[*ホスト*] を選択します。
. 上部の*管理対象ホスト*タブが選択されていることを確認します。
. *追加*を選択します。
. [Hosts]ページで、次の操作を実行します。
+
|===
| フィールド | 操作 


 a| 
ホストタイプ
 a| 
ホスト タイプを選択します。

** Windows
** Linux
** AIX



NOTE: NetAppがサポートするプラグインは、Windows、Linux、AIX 環境で使用できます。


NOTE: ストレージおよび Oracle アプリケーションは AIX でサポートされます。



 a| 
ホスト名
 a| 
ホストの完全修飾ドメイン名（FQDN）またはIPアドレスを入力します。

SnapCenterが機能するためには、DNSが適切に設定されている必要があります。そのため、FQDNを入力することを推奨します。

Windows環境の場合、信頼されないドメイン ホストのIPアドレスがサポートされるのは、そのIPアドレスがFQDNに解決される場合のみです。

スタンドアロン ホストのIPアドレスまたはFQDNを入力できます。

SnapCenterを使用してサブドメインの一部であるホストを追加する場合は、FQDNを指定する必要があります。



 a| 
Credentials
 a| 
作成したクレデンシャルの名前を選択するか、新しいクレデンシャルを作成します。

このクレデンシャルには、リモート ホストに対する管理権限が必要です。詳細については、クレデンシャルの作成に関する情報を参照してください。

指定したクレデンシャル名にカーソルを合わせると、クレデンシャルの詳細を確認できます。


NOTE: クレデンシャルの認証モードは、[Add Host]ウィザードで指定するホスト タイプによって決まります。

|===
. *インストールするプラグインの選択*セクションで、インストールするプラグインを選択します。
+
リストから次のプラグインをインストールできます。

+
** MongoDB
** ORASCPM（Oracle Applicationsとして表示）
** SAP ASE
** SAP MaxDB
** ストレージ


. (オプション) 他のプラグインをインストールするには、[その他のオプション] を選択します。
+
|===
| フィールド | 操作 


 a| 
ポート
 a| 
デフォルトのポート番号をそのまま使用するか、ポート番号を指定します。

デフォルトのポート番号は8145です。SnapCenter Serverがカスタム ポートにインストールされている場合は、そのポート番号がデフォルト ポートとして表示されます。


NOTE: プラグインを手動でインストールしてカスタム ポートを指定した場合は、同じポートを指定する必要があります。そうしないと、処理が失敗します。



 a| 
Installation Path
 a| 
NetAppがサポートするプラグインは、Windows システムまたは Linux システムのいずれかにインストールできます。

** Windows 用のSnapCenterプラグイン パッケージの場合、デフォルトのパスは C:\Program Files\ NetApp\ SnapCenterです。
+
必要に応じて、パスをカスタマイズできます。

** Linux用SnapCenterプラグインパッケージおよびAIX用SnapCenterプラグインパッケージの場合、デフォルトのパスは `/opt/NetApp/snapcenter`。
+
必要に応じて、パスをカスタマイズできます。





 a| 
Skip preinstall checks
 a| 
プラグインを手動でインストール済みで、プラグインをインストールするための要件をホストが満たしているかどうかを検証しない場合は、このチェック ボックスをオンにします。



 a| 
Use group Managed Service Account (gMSA) to run the plug-in services
 a| 
Windowsホストで、グループ管理サービス アカウント（gMSA）を使用してプラグイン サービスを実行する場合は、このチェック ボックスをオンにします。


IMPORTANT: gMSA名をdomainName\accountName$の形式で指定します。


NOTE: gMSAは、SnapCenter Plug-in for Windowsサービスのログオン サービス アカウントとしてのみ使用されます。

|===
. *送信*を選択します。
+
「*事前チェックをスキップ*」チェックボックスを選択していない場合、ホストがプラグインのインストール要件を満たしているかどうかを確認するための検証が行われます。ディスク容量、RAM、PowerShellバージョン、.NETバージョン、場所（Windowsプラグインの場合）、Javaバージョン（Linuxプラグインの場合）が最小要件に照らして検証されます。最小要件を満たしていない場合、対応するエラーまたは警告メッセージが表示されます。

+
エラーがディスク容量またはRAMに関連している場合は、次の場所にあるweb.configファイルを更新できます。 `C:\Program Files\NetApp\SnapCenter WebApp`デフォルト値を変更します。エラーが他のパラメータに関連している場合は、問題を修正する必要があります。

+

NOTE: HA セットアップでSnapManager.Web.UI.dll.config を更新する場合は、両方のノードでファイルを更新し、 SnapCenterアプリケーション プールを再起動する必要があります。

+
Windowsのデフォルトパスは `C:\Program Files\NetApp\SnapCenter WebApp\SnapManager.Web.UI.dll.config`

+
Linuxのデフォルトパスは `/opt/NetApp/snapcenter/SnapManagerWeb/SnapManager.Web.UI.dll.config`

. ホスト タイプが Linux の場合は、フィンガープリントを確認し、[確認して送信] を選択します。
+

NOTE: 前述の手順で同じホストがSnapCenterに追加され、フィンガープリントが確認された場合でも、フィンガープリントの検証は必須です。

. インストールの進捗状況を監視します。
+
インストール固有のログファイルは次の場所にあります。 `/custom_location/snapcenter/`ログ。


