---
permalink: protect-nsp/backup_schedules_of_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: NetApp supported plug-in 
summary: バックアップのスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率です。リソースをバックアップする回数が多いほど、リストア時にSnapCenterが使用する必要のあるアーカイブ ログの数が少なくなります。これにより、リストア処理の時間を短縮できます。 
---
= NetAppがサポートしているプラグイン リソースのバックアップ スケジュール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックアップのスケジュールを決定する場合に最も重要な要因となるのは、リソースの変更率です。リソースをバックアップする回数が多いほど、リストア時にSnapCenterが使用する必要のあるアーカイブ ログの数が少なくなります。これにより、リストア処理の時間を短縮できます。

使用頻度の高いリソースは1時間ごとにバックアップする必要がありますが、ほとんど使用されないリソースは1日に1回バックアップすれば十分です。その他の要因としては、組織におけるリソースの重要性、サービス レベル アグリーメント（SLA）、目標復旧時点（RPO）などがあります。

SLAとは、求められるサービス レベル、およびサービスに関連する多くの問題（サービスの可用性やパフォーマンスなど）への対応を定義したものです。RPOは、障害発生後に通常処理を再開するためにバックアップ ストレージからリカバリする必要があるファイルの経過時間に関する戦略を定義したものです。SLAとRPOは、データ保護戦略に関与します。

バックアップ スケジュールには、次の2つの要素があります。

* バックアップ頻度
+
バックアップ頻度（バックアップを実行する間隔）は、ポリシー設定の一部であり、一部のプラグインではスケジュール タイプとも呼ばれます。たとえば、毎時、毎日、毎週、または毎月としてバックアップ頻度を設定できます。SnapCenter GUI で [設定] > [ポリシー] をクリックすると、ポリシーにアクセスできます。

* バックアップ スケジュール
+
バックアップ スケジュール（バックアップが実行される日時）は、リソースまたはリソース グループの設定の一部です。たとえば、週次バックアップのポリシーが設定されているリソース グループがある場合、毎週木曜日の午後 10 時にバックアップするようにスケジュールを設定できます。SnapCenter GUI でリソース グループのスケジュールにアクセスするには、[リソース] をクリックし、適切なプラグインを選択して、[表示] > [リソース グループ] をクリックします。


