---
permalink: protect-nsp/create_policies_for_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: create policies, NetApp supported plug-in 
summary: SnapCenterを使用してNetAppがサポートしているプラグイン固有のリソースをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。 
---
= NetAppがサポートしているプラグイン リソースのポリシーの作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用してNetAppがサポートしているプラグイン固有のリソースをバックアップする前に、バックアップ対象のリソースまたはリソース グループのバックアップ ポリシーを作成する必要があります。

.開始する前に
* バックアップ戦略を定義しておく必要があります。
+
詳細については、NetAppがサポートしているプラグインのデータ保護戦略の定義に関する説明を参照してください。

* データ保護の準備が完了している必要があります。
+
データ保護の準備作業には、SnapCenterのインストール、ホストの追加、ストレージ システム接続の作成、リソースの追加などがあります。

* ミラー処理またはバックアップ処理を実行するには、Storage Virtual Machine（SVM）をユーザに割り当てる必要があります。
+
ユーザがSnapshotをミラーまたはバックアップにレプリケートする場合は、ソース ボリュームとデスティネーション ボリューム両方のSVMをSnapCenter管理者がユーザに割り当てる必要があります。

* 保護するリソースを手動で追加しておく必要があります。


.タスク概要
* バックアップ ポリシーとは、バックアップをどのように管理し、スケジューリングし、保持するかを定める一連のルールです。レプリケーション、スクリプト、アプリケーション設定を指定することもできます。
* ポリシーでオプションを指定しておくことで、別のリソース グループにポリシーを再利用して時間を節約することができます。
* SnapLock
+
** [Retain the backup copies for a specific number of days]オプションを選択した場合は、SnapLockの保持期間をここで指定した保持日数以下にする必要があります。
** Snapshotのロック期間を指定すると、保持期間が終了するまでSnapshotが削除されません。その結果、ポリシーで指定した数よりも多くのSnapshotが保持される可能性があります。
** ONTAP 9.12.1以前のバージョンでは、リストアの一環としてSnapLock Vault Snapshotから作成されたクローンが、SnapLock Vaultの有効期限を継承します。SnapLockの有効期限が過ぎたあと、ストレージ管理者がクローンを手動でクリーンアップする必要があります。





NOTE: プライマリSnapLock設定はSnapCenterバックアップ ポリシーで管理し、セカンダリSnapLock設定はONTAPで管理します。

.手順
. 左側のナビゲーション ペインで、[*設定*] をクリックします。
. [設定]ページで、[*ポリシー*]をクリックします。
. *新規*をクリックします。
. 「名前」ページで、ポリシー名と詳細を入力します。
. [Policy type]ページで、次の手順を実行します。
+
.. ストレージ タイプを選択します。
.. カスタム バックアップ設定セクションでは、キーと値の形式でプラグインに渡す必要がある特定のバックアップ設定を指定します。
+
プラグインに渡すキーと値のペアを複数指定することができます。



. スナップショットとレプリケーション ページで、次の手順を実行します。
+
.. *オンデマンド*、*時間別*、*日次*、*週次*、または*月次*を選択してスケジュール タイプを指定します。
+

NOTE: リソース グループを作成する際に、バックアップ処理のスケジュール（開始日、終了日、頻度）を指定することができます。これにより、ポリシーとバックアップ間隔が同じである複数のリソース グループを作成できますが、各ポリシーに異なるバックアップ スケジュールを割り当てることもできます。

+

NOTE: 午前 2 時にスケジュールを設定した場合、夏時間 (DST) 中はスケジュールは実行されません。

.. スナップショット設定セクションで、*バックアップ タイプ* ページで選択したバックアップ タイプとスケジュール タイプの保持設定を指定します。
+
|===
| 状況 | 操作 


 a| 
特定の数のSnapshotを保持
 a| 
*保持するコピー*を選択し、保持するスナップショットの数を指定します。

Snapshotの数が指定した数を超えると、古いものから順にSnapshotが削除されます。


NOTE: SnapVaultレプリケーションを有効にする場合は、保持数を2以上に設定する必要があります。保持数を1に設定すると、新しいSnapshotがターゲットにレプリケートされるまで最初のSnapshotがSnapVault関係の参照Snapshotになるため、保持処理が失敗することがあります。


NOTE: 最大保持値は 1018 です。保持数を、使用しているONTAPバージョンがサポートする値よりも大きい値に設定すると、バックアップが失敗します。



 a| 
Snapshotを特定の日数だけ保持
 a| 
*コピーの保持期間*を選択し、スナップショットを削除する前に保持する日数を指定します。



 a| 
スナップショットコピーのロック期間
 a| 
*スナップショット コピーのロック期間* を選択し、日、月、または年を指定します。

SnapLock保持期間は100年未満にする必要があります。

|===
.. ポリシーラベルを選択します。
+

NOTE: リモート レプリケーションのプライマリ スナップショットにSnapMirrorラベルを割り当てることで、プライマリ スナップショットによってスナップショット レプリケーション操作をSnapCenterからONTAPセカンダリ システムにオフロードできるようになります。これは、ポリシー ページでSnapMirrorまたはSnapVaultオプションを有効にしなくても実行できます。



. [セカンダリ レプリケーション オプションの選択] セクションで、次のセカンダリ レプリケーション オプションの 1 つまたは両方を選択します。
+
|===
| フィールド | 操作 


 a| 
*ローカル スナップショット コピーを作成した後、 SnapMirror を更新します*
 a| 
別のボリュームにバックアップ セットのミラー コピーを作成する場合（SnapMirrorレプリケーション）は、このフィールドを選択します。

ONTAPの保護関係のタイプがミラーとバックアップの場合、このオプションのみを選択すると、プライマリで作成されたSnapshotがデスティネーションに転送されませんが、デスティネーションのリストに表示されます。このスナップショットを復元操作を実行するために宛先から選択すると、次のエラー メッセージが表示されます: 選択したボールト/ミラー バックアップにはセカンダリ ロケーションは使用できません。

セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。

トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

見るlink:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["[Topology]ページでのNetAppがサポートしているプラグイン リソースに関連するバックアップとクローンの表示"] 。



 a| 
*ローカルスナップショットコピーを作成した後、 SnapVault を更新します*
 a| 
ディスクツーディスクのバックアップ レプリケーション（SnapVaultバックアップ）を実行する場合は、このオプションを選択します。

セカンダリ レプリケーションのSnapLockの有効期限には、プライマリSnapLockの有効期限がロードされます。トポロジ ページの *更新* ボタンをクリックすると、 ONTAPから取得されたセカンダリおよびプライマリSnapLock の有効期限が更新されます。

SnapLock がSnapLock Vault と呼ばれるONTAPのセカンダリにのみ設定されている場合、[トポロジ] ページの [更新] ボタンをクリックすると、 ONTAPから取得されたセカンダリのロック期間が更新されます。

SnapLock Vault の詳細については、「Vault の保存先でスナップショットを WORM にコミットする」を参照してください。

見るlink:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["[Topology]ページでのNetAppがサポートしているプラグイン リソースに関連するバックアップとクローンの表示"] 。



 a| 
*エラー再試行回数*
 a| 
処理が停止されるまでに試行できるレプリケーションの最大回数を入力します。

|===
+

NOTE: セカンダリ ストレージでSnapshotの上限に達しないように、ONTAPでセカンダリ ストレージのSnapMirror保持ポリシーを設定する必要があります。

. 概要を確認し、[完了] をクリックします。

