---
permalink: protect-nsp/how_resources_resource_groups_policies_used_for_protecting_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: NetApp supported plug-in 
summary: SnapCenterを使用する前に、実行するバックアップ、クローニング、リストアの各処理に関連する基本的な概念を理解しておくと役立ちます。ここでは、これらの処理で扱うリソース、リソース グループ、およびポリシーについて説明します。 
---
= NetAppがサポートしているプラグイン リソースの保護におけるリソース、リソース グループ、ポリシーの使用方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用する前に、実行するバックアップ、クローニング、リストアの各処理に関連する基本的な概念を理解しておくと役立ちます。ここでは、これらの処理で扱うリソース、リソース グループ、およびポリシーについて説明します。

* リソースとは、SnapCenterでバックアップやクローンを作成するデータベース、Windowsファイルシステム、VMなどです。
* SnapCenterリソース グループは、ホストまたはクラスタ上のリソースの集まりです。
+
リソース グループに対して処理を実行すると、リソース グループに指定したスケジュールに従って、リソース グループに定義されているリソースに対して処理が実行されます。

+
単一のリソースまたはリソース グループをオンデマンドでバックアップすることができます。また、スケジュールされたバックアップを単一リソースおよびリソース グループに対して実行することもできます。

* ポリシーは、バックアップ頻度、コピーの保持、レプリケーション、スクリプトといった、データ保護処理の特性を指定するものです。
+
リソース グループを作成するときに、そのグループに対して1つ以上のポリシーを選択します。単一リソースに対してオンデマンドでバックアップを実行するときにもポリシーを選択できます。



リソース グループは、保護する対象と、それを日時でいつ保護するかを定義するものと考えてください。ポリシーとは、それをどのように保護したいかを定義するものと考えてください。たとえば、すべてのデータベースまたはホストのすべてのファイルシステムをバックアップする場合、すべてのデータベースまたはホストのすべてのファイルシステムを含むリソース グループを作成します。このリソース グループに、日次ポリシーと毎時ポリシーの2つのポリシーを適用します。リソース グループを作成してポリシーを適用する際に、ファイルベースのバックアップを1日1回実行するようにリソース グループを設定し、別のスケジュールでSnapshotベースのバックアップを1時間おきに実行するように設定します。
