---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: ホストを追加してプラグイン パッケージをインストールする前に、すべての要件を満たしておく必要があります。NetAppがサポートするプラグインは、Windows、Linux、AIX のいずれの環境でも使用できます。 
---
= Windows、Linux、または AIX 用のホストを追加し、プラグイン パッケージをインストールするための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストを追加してプラグイン パッケージをインストールする前に、すべての要件を満たしておく必要があります。NetAppがサポートするプラグインは、Windows、Linux、および AIX 環境でサポートされます。


NOTE: ストレージおよび Oracle アプリケーションは AIX でサポートされます。

* Linux、Windows、または AIX ホストに Java 11 がインストールされている必要があります。
+

NOTE: IBM Java は Windows および Linux ホストではサポートされていません。

* Windowsホストにプラグインをインストールする際、組み込みでないクレデンシャルを指定する場合や、ユーザがローカル ワークグループに属している場合は、ホストのUACを無効にする必要があります。
* MongoDB、ORASCPM、Oracle Applications、SAP ASE、SAP MaxDB、ストレージ プラグインなどのNetAppでサポートされているプラ​​グインは、ホスト追加操作が実行されるクライアント ホストで使用できる必要があります。




== 全般

iSCSIを使用している場合は、iSCSIサービスが実行されている必要があります。



== Windowsホスト

* ローカル管理者権限があり、リモート ホストに対してローカル ログインのアクセス許可があるドメイン ユーザが必要です。
* SnapCenterでクラスタ ノードを管理する場合は、クラスタ内のすべてのノードに対する管理者権限があるユーザが必要です。
* Microsoft Windows 用のSnapCenterプラグインを手動で選択する必要があります。
+
http://www.java.com/en/download/manual.jsp["Windows用JAVAをダウンロード"]





== LinuxおよびAIXホスト


NOTE: ストレージおよび Oracle アプリケーションは AIX でサポートされます。

* rootユーザまたはroot以外のユーザに対してパスワード ベースのSSH接続を有効にしておく必要があります。
* Java 11をLinuxホストにインストールしておく必要があります。
+
SnapCenter ServerホストにWindows Server 2019またはWindows Server 2016を使用している場合は、Java 11をインストールする必要があります。要件に関する最新の情報については、Interoperability Matrix Tool（IMT）を参照してください。

+
http://www.java.com/en/download/manual.jsp["Linux用JAVAをダウンロード"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["AIX用JAVAをダウンロード"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["NetApp Interoperability Matrix Tool"]

* いくつかのパスにアクセスできるようにroot以外のユーザにsudo権限を設定する必要があります。visudo Linuxユーティリティを使用して、/etc/sudoersファイルに次の行を追加します。
+

NOTE: Sudoバージョン1.8.7以降を使用していることを確認します。

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ は、作成した非 root ユーザーの名前です。

+
_checksum_value_ は、次の場所にある *sc_unix_plugins_checksum.txt* ファイルから取得できます。

+
** SnapCenter Server が Windows ホストにインストールされている場合は、_C:\ProgramData\ NetApp\ SnapCenter \Package Repository\sc_unix_plugins_checksum.txt_。
** SnapCenter Server が Linux ホストにインストールされている場合は、_/opt/ NetApp /snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_。
+

IMPORTANT: この例は、独自のデータを作成する際の参照としてのみ使用してください。







== AIXホストの要件

SnapCenter Plug-ins Package for AIXをインストールする前に、ホストが要件を満たしていることを確認する必要があります。


NOTE: ストレージおよび Oracle アプリケーションは AIX でサポートされます。


NOTE: SnapCenter Plug-ins Package for AIXに含まれているSnapCenter Plug-in for UNIXでは、同時ボリューム グループはサポートされません。

|===
| 項目 | 要件 


 a| 
オペレーティング システム
 a| 
AIX 7.1以降



 a| 
ホスト上のSnapCenterプラグインに必要な最小RAM
 a| 
4 GB



 a| 
ホスト上のSnapCenterプラグインに必要なインストールおよびログの最小スペース
 a| 
2 GB


NOTE: 十分なディスク スペースを割り当てて、ログ フォルダによるストレージ消費を監視する必要があります。必要なログ スペースは、保護対象のエンティティの数とデータ保護処理の頻度によって異なります。十分なディスク スペースがない場合は、最近実行した処理のログが作成されません。



 a| 
必要なソフトウェア パッケージ
 a| 
Java 11 IBM Java

Javaを最新バージョンにアップグレードした場合は、/var/opt/snapcenter/spl/etc/spl.propertiesにあるJAVA_HOMEオプションが正しいJavaバージョンと正しいパスに設定されていることを確認する必要があります。

|===
サポートされているバージョンに関する最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^] 。



=== AIXホストのroot以外のユーザへのsudo権限の設定

SnapCenter 4.4以降では、root以外のユーザがSnapCenter Plug-ins Package for AIXをインストールしてプラグイン プロセスを開始できます。プラグイン プロセスは有効なroot以外のユーザとして実行されます。いくつかのパスにアクセスできるようにroot以外のユーザにsudo権限を設定する必要があります。

*必要なもの*

* sudoバージョン1.8.7以降
* _/etc/ssh/sshd_config_ ファイルを編集して、メッセージ認証コード アルゴリズム (MAC hmac-sha2-256 および MAC hmac-sha2-512) を設定します。
+
この構成ファイルを更新したら、sshdサービスを再起動します。

+
例：

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*このタスクについて*

次のパスにアクセスできるようにroot以外のユーザにsudo権限を設定する必要があります。

* /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx
* /custom_location/NetApp/snapcenter/spl/installation/plugins/uninstall
* /custom_location/NetApp/snapcenter/spl/bin/spl


*手順*

. SnapCenter Plug-ins Package for AIXをインストールするAIXホストにログインします。
. visudo Linuxユーティリティを使用して、/etc/sudoersファイルに次の行を追加します。
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: RAC をセットアップしている場合は、他の許可されたコマンドとともに、/etc/sudoers ファイルに次の行を追加する必要があります: '/<crs_home>/bin/olsnodes'



_crs_home_ の値は、_/etc/oracle/olr.loc_ ファイルから取得できます。

_AIX_USER_ は、作成した非 root ユーザーの名前です。

_checksum_value_ は、次の場所にある *sc_unix_plugins_checksum.txt* ファイルから取得できます。

* SnapCenter Server が Windows ホストにインストールされている場合は、_C:\ProgramData\ NetApp\ SnapCenter \Package Repository\sc_unix_plugins_checksum.txt_。
* SnapCenter Server が Linux ホストにインストールされている場合は、_/opt/ NetApp /snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_。



IMPORTANT: この例は、独自のデータを作成する際の参照としてのみ使用してください。
