---
permalink: get-started/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: SnapCenter、データ保護操作を有効にするために複数のライセンスが必要です。インストールするSnapCenterライセンスのタイプは、ストレージ環境および使用する機能によって異なります。 
---
= SnapCenterに必要なライセンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterでは、アプリケーション、データベース、ファイルシステム、仮想マシンのデータ保護を実現するために複数のライセンスが必要です。インストールするSnapCenterライセンスのタイプは、ストレージ環境および使用する機能によって異なります。

|===
| ライセンス | インストール先 


 a| 
SnapCenter Standard（コントローラ ベース）
 a| 
FAS、 AFF、 ASAに必須

SnapCenter Standard ライセンスはコントローラ ベースのライセンスであり、 NetApp ONTAP One の一部として含まれています。SnapManager Suiteライセンスには、SnapCenter Standardライセンスの使用権も付随しています。  FAS、 AFF、またはASAストレージを使用してSnapCenterを試用インストールする場合は、営業担当者に連絡してNetApp ONTAP One 評価ライセンスを入手できます。

NetApp ONTAP Oneに含まれるライセンスの詳細については、 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp ONTAP Oneに含まれるライセンス"] 。


NOTE: SnapCenterは、Data Protection Bundleの一部としても提供されます。A400以降を購入済みの場合は、Data Protection Bundleを購入する必要があります。



 a| 
SnapMirror / SnapVault
 a| 
ONTAP

SnapCenterでレプリケーションを有効にする場合、SnapMirrorまたはSnapVaultどちらかのライセンスが必要です。



 a| 
SnapRestore
 a| 
バックアップのリストアと検証に必要です。

プライマリ ストレージ システム

* SnapVaultデスティネーション システムでリモート検証とバックアップからのリストアを実行するために必要です。
* SnapMirrorデスティネーション システムでリモート検証を実行するために必要です。




 a| 
FlexClone
 a| 
データベースのクローニング処理と検証処理に必要です。

プライマリ ストレージ システムとセカンダリ ストレージ システム

* SnapVaultデスティネーション システムでセカンダリ バックアップからクローンを作成するために必要です。
* SnapMirrorデスティネーション システムでセカンダリSnapMirrorバックアップからクローンを作成するために必要です。




 a| 
プロトコルライセンス
 a| 
* LUN用のiSCSIライセンスまたはFCライセンス
* SMB共有用のCIFSライセンス
* NFSタイプのVMDK用のNFSライセンス
* VMFSタイプのVMDK用のiSCSIライセンスまたはFCライセンス


ソース ボリュームを利用できない場合にSnapMirrorデスティネーション システムからデータを提供するには、SnapMirrorデスティネーション システムに必要です。



 a| 
SnapCenter Standardライセンス（オプション）
 a| 
セカンダリ デスティネーション


NOTE: セカンダリ デスティネーションにSnapCenter Standardライセンスを追加することを推奨しますが、必須ではありません。セカンダリ デスティネーションでSnapCenter Standardライセンスが有効になっていない場合、フェイルオーバー後にSnapCenterを使用してセカンダリ デスティネーションでリソースをバックアップすることができません。ただし、クローン処理と検証処理を実行するためには、セカンダリ デスティネーションにFlexCloneライセンスが必要です。



 a| 
Single Mailbox Recovery（SMBR）ライセンス
 a| 
SnapCenter Plug-in for Exchangeを使用してMicrosoft Exchange ServerのデータベースとSingle Mailbox Recovery（SMBR）を管理する場合は、SMBR用の追加ライセンスが必要です。このライセンスはユーザのメールボックス数に基づいて別途購入する必要があります。

NetApp® Single Mailbox Recoveryは、2023年5月12日に販売終了（EOA）になりました。詳細については、link:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPC-00507"] 。2020年6月24日に導入された販売用パーツ番号を通じてメールボックスの容量、メンテナンス、サポートを購入されたお客様には、サポート対象の期間中は引き続きサポートを提供いたします。

NetApp Single Mailbox Recoveryは、Ontrackが提供するパートナー製品です。Ontrack PowerControlsには、NetApp Single Mailbox Recoveryと同様の機能が用意されています。販売終了となる2023年5月12日以降、お客様は、新しいOntrack PowerControlsソフトウェア ライセンスとOntrack PowerControlsのメンテナンスおよびサポート更新をOntrackから（licensingteam@ontrack.com経由で）購入して、メールボックスをきめ細かくリカバリできます。

|===

NOTE: SnapCenter AdvancedとSnapCenter NAS File Servicesのライセンスは廃止され、現在は提供されていません。Amazon FSx for NetApp ONTAP、 ONTAP Select、 Cloud Volumes ONTAP、およびAzure NetApp Files、標準ライセンスと容量ベースのライセンスは不要になりました。

1つ以上のSnapCenterライセンスをインストールする必要があります。ライセンスの追加方法については、以下を参照してください。link:../install/concept_snapcenter_standard_controller_based_licenses.html["SnapCenter Standardコントローラベース ライセンスの追加"] 。
