---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: クレデンシャルの認証方式は、アプリケーションや環境に応じて異なります。資格情報により、ユーザーは認証され、 SnapCenter の操作を実行できるようになります。プラグインのインストール用とデータ保護処理用にクレデンシャルを1組ずつ作成してください。 
---
= SnapCenter資格情報の認証方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資格情報では、アプリケーションや環境に応じて異なる認証方法が使用されます。資格情報により、ユーザーは認証され、 SnapCenter の操作を実行できるようになります。プラグインのインストール用とデータ保護操作用の資格情報セットをそれぞれ 1 セット作成する必要があります。



== Windows認証

Windows認証方式は、Active Directoryに照らして認証します。Windows 認証の場合、Active Directory はSnapCenterの外部に設定されます。 SnapCenter は追加の構成なしで認証します。ホストを追加したり、プラグイン パッケージをインストールしたり、ジョブをスケジュールしたりするには、Windows 資格情報が必要です。



== 信頼されないドメインの認証

SnapCenterでは、信頼されていないドメインに属するユーザーとグループが Windows 資格情報を作成できます。認証を成功させるには、信頼されていないドメインをSnapCenterに登録する必要があります。



== ローカル ワークグループ認証

SnapCenter を使用すると、ローカル ワークグループのユーザーとグループを使用して Windows 資格情報を作成できます。ローカル ワークグループ ユーザーおよびグループの Windows 認証は、Windows 資格情報の作成中には実行されず、ホストの登録やその他のホスト操作が実行されるまで延期されます。



== SQL Server認証

SQL認証方式は、SQL Serverインスタンスに照らして認証します。したがって、SQL ServerインスタンスがSnapCenterで検出されなければなりません。そのため、SQLクレデンシャルを追加する前に、ホストの追加とプラグイン パッケージのインストールを完了し、リソースをリフレッシュしておく必要があります。SQL Server でのスケジュール設定やリソースの検出などの操作を実行するには、SQL Server 認証が必要です。



== Linux認証

Linux認証方式は、Linuxホストに照らして認証します。Linux認証は、SnapCenter GUIからリモートでLinuxホストを追加してSnapCenter Plug-ins Package for Linuxをインストールする際の最初のステップで必要になります。



== AIX認証

AIX認証方式は、AIXホストに照らして認証します。AIX認証は、SnapCenter GUIからリモートでAIXホストを追加してSnapCenter Plug-ins Package for AIXをインストールする際の最初のステップで必要になります。



== Oracleデータベース認証

Oracleデータベース認証方式は、Oracleデータベースに照らして認証します。Oracleデータベース認証は、Oracleデータベースに対する処理を実行する際、データベース ホストでオペレーティング システム（OS）認証が無効になっている場合に必要になります。したがって、Oracle データベース資格情報を追加する前に、Oracle データベースに sysdba 権限を持つ Oracle ユーザーを作成する必要があります。



== Oracle ASM認証

Oracle ASM認証方式は、Oracle Automatic Storage Management（ASM）インスタンスに照らして認証します。Oracle ASM インスタンスにアクセスする必要があり、データベース ホストで OS 認証が無効になっている場合は、Oracle ASM 認証が必要です。  Oracle ASM 資格情報を追加する前に、ASM インスタンスにシステム権限を持つ Oracle ユーザーを作成します。



== RMANカタログ認証

RMANカタログ認証方式は、Oracle Recovery Manager（RMAN）カタログ データベースに照らして認証します。外部のカタログ メカニズムを設定し、データベースをカタログ データベースに登録している場合は、RMANカタログ認証を追加する必要があります。
