---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: SnapCenterを使用する前に、実行するバックアップ、クローニング、リストアの各処理に関連する基本的な概念を理解しておくと役立ちます。 
---
= データ保護の主要概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenterを使用する前に、バックアップ、クローン、復元の主要な概念を理解してください。



== リソース

リソースには、データベース、Windows ファイル システム、またはSnapCenterでバックアップまたはクローンされたファイル共有が含まれます。環境によっては、リソースはデータベース インスタンス、SQL Server 可用性グループ、Oracle データベース、RAC データベース、またはカスタム アプリケーション グループになることもあります。



== リソース グループ

リソース グループは、ホストまたはクラスター上のリソースのコレクションであり、複数のホストおよびクラスターからのリソースが含まれる場合があります。リソース グループに対して実行された操作は、指定されたスケジュールに基づいてそのすべてのリソースに適用されます。個々のリソースまたはグループに対して、オンデマンドまたはスケジュールされたバックアップを実行できます。


NOTE: 共有リソース グループ内の 1 つのホストがメンテナンス モードに入ると、そのグループのすべてのスケジュールされた操作がすべてのホストで中断されます。

特定のリソースをバックアップするには、データベースの場合はデータベース プラグイン、ファイル システムの場合はファイル システム プラグイン、VM およびデータストアの場合はSnapCenter Plug-in for VMware vSphereなどの関連プラグインを使用します。



== ポリシー

ポリシーは、バックアップの頻度、コピーの保持、レプリケーション、スクリプト、およびデータ保護操作のその他の特性を指定します。

リソース グループを作成するとき、またはオンデマンド バックアップを実行するときに、1 つ以上のポリシーを選択できます。

リソース グループは、保護する必要がある内容と、日時に基づいていつ保護する必要があるかを定義します。ポリシーでは、保護がどのように実行されるかを説明します。たとえば、ホストのすべてのデータベースまたはファイル システムをバックアップする必要がある場合、ホスト内のすべてのデータベースまたはファイル システムを含むリソース グループが作成されることがあります。その後、日次ポリシーと時間別ポリシーの 2 つのポリシーをリソース グループに適用できます。

リソース グループを作成してポリシーをアタッチするときに、毎日完全バックアップを実行し、1 時間ごとにログ バックアップを実行する別のスケジュールを構成することができます。

データ保護操作では、カスタムのプレスクリプトとポストスクリプトを使用できます。これらのスクリプトを使用すると、データ保護ジョブの前または後に自動化を行うことができます。たとえば、スクリプトはデータ保護ジョブの失敗や警告を自動的に通知できます。プレスクリプトとポストスクリプトを設定する前に、これらのスクリプトを作成するための要件を理解することが重要です。



== 序文と後書きの使い方

カスタムのプレスクリプトとポストスクリプトを使用すると、ジョブの前または後にデータ保護タスクを自動化できます。たとえば、ジョブの失敗や警告を通知するスクリプトを追加できます。設定する前に、これらのスクリプトの要件を理解していることを確認してください。



=== サポートされるスクリプト タイプ

Windowsでは、次の種類のスクリプトがサポートされています。

* バッチ ファイル
* PowerShellのスクリプト
* Perlスクリプト


UNIXでは、次の種類のスクリプトがサポートされています。

* Perlスクリプト
* Pythonスクリプト
* シェル スクリプト
+

NOTE: デフォルトのBashシェルに加えて、shシェル、kシェル、cシェルなど他のシェルもサポートされています。





=== スクリプト パス

非仮想化ストレージ システムと仮想化ストレージ システムの両方でSnapCenter操作の一部として実行されるすべての事前スクリプトと事後スクリプトは、プラグイン ホストで実行されます。

* Windowsスクリプトが、プラグイン ホスト上にある必要があります。



NOTE: プリスクリプトやポストスクリプトのパスに、ドライブや共有を含めることはできません。パスは、SCRIPTS_PATHの相対パスである必要があります。

* UNIXスクリプトが、プラグイン ホスト上にある必要があります。



NOTE: スクリプト パスは、実行時に検証されます。



=== スクリプトを指定する場所

スクリプトはバックアップ ポリシーに指定します。バックアップ ジョブが開始されると、ポリシーによってスクリプトがバックアップ対象のリソースに自動的に関連付けられます。バックアップ ポリシーの作成時に、プリスクリプトとポストスクリプトの引数を指定できます。


NOTE: 複数のスクリプトを指定することはできません。



=== スクリプトのタイムアウト

デフォルトでは、タイムアウトは60秒に設定されています。タイムアウト値は変更できます。



=== スクリプト出力

Windowsでは、プリスクリプトとポストスクリプトの出力ファイルが格納されるデフォルト ディレクトリは、Windows\System32です。

UNIXには、プリスクリプトとポストスクリプトが格納されるデフォルトの場所はありません。出力ファイルは、任意の場所にリダイレクトできます。
