---
permalink: uninstall/reference_prerequisites_for_removing_a_host.html 
sidebar: sidebar 
keywords: uninstall, prerequisites, plug-in, plug-in packages 
summary: SnapCenterを使用してデータ保護ジョブを管理する必要がなくなった場合は、ホストを削除できます。たとえば、保護する必要のあるデータがなくなったホストを削除することが考えられます。  SnapCenter Server からホストを削除する前に、前提条件となるタスクを実行する必要があります。 
---
= ホストを削除するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter GUI を使用して、ホストを削除したり、個々のプラグインまたはプラグイン パッケージをアンインストールしたりできます。また、 SnapCenter Server ホストのコマンドライン インターフェイス (CLI) を使用するか、任意のホストでローカルに Windows の [プログラムのアンインストール] オプションを使用して、リモート ホスト上の個々のプラグインまたはプラグイン パッケージをアンインストールすることもできます。

SnapCenter Serverからホストを削除する前に、前提条件を満たしておく必要があります。

* 管理者としてログインする必要があります。
* ホストで検出ジョブが実行されていないことを確認する必要があります。
* ホストに関連付けられているすべてのオブジェクトを削除するためには、必要な権限を含むロールが割り当てられている必要があります。割り当てられていないと削除処理は失敗します。
* ホストをSnapCenterに追加した後に SSH キーが変更された場合は、フィンガープリントを確認する必要があります。
* SnapCenterホストがSnapCenterの新しいバージョンにアップグレードされているが、プラグイン ホストがまだプラグインの以前のバージョンを実行している場合は、フィンガープリントを確認する必要があります。




== ロールベース アクセス制御を使用するホストを削除する場合の前提条件

* ホストの読み取りと削除、プラグインのインストールとアンインストール、およびオブジェクトの削除を行う権限を持つRBACロールを使用してログインしておく必要があります。
+
オブジェクトは、クローン、バックアップ、リソース グループ、ストレージ システムなどです。

* RBACロールにRBACユーザを追加しておく必要があります。
* 削除するホスト、プラグイン、クレデンシャル、リソース グループ、およびストレージ システム（クローンの場合）にRBACユーザを割り当てる必要があります。
* SnapCenterにRBACユーザとしてログインしておく必要があります。




== クローン ライフサイクル処理で作成されたクローンを含むホストを削除する場合の前提条件

* SQLデータベースのクローン ライフサイクル管理を使用してクローニング ジョブを作成しておく必要があります。
* クローンの読み取りと削除、リソースの読み取りと削除、リソース グループの読み取りと削除、ストレージの読み取りと削除、プロビジョニングの読み取りと削除、マウント、アンマウント、プラグインのインストールとアンインストール、およびホストの読み取りと削除を行う権限を持つRBACロールを作成しておく必要があります。
* RBACロールにRBACユーザを割り当てておく必要があります。
* ホスト、SnapCenter Plug-in for Microsoft SQL Server、クレデンシャル、クローン ライフサイクル リソース グループ、およびストレージ システムにRBACユーザを割り当てておく必要があります。
* SnapCenterにRBACユーザとしてログインしておく必要があります。


SnapCenter Plug-in for VMware vSphere のアンインストールについては、以下を参照してください。 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_remove_plugin.html["SnapCenter Plug-in for VMware vSphereの削除"^] 。
