---
permalink: uninstall/task_remove_a_host.html 
sidebar: sidebar 
keywords: uninstall, remove, remove host 
summary: 'SnapCenter Serverでホストを削除すると、まずSnapCenterの[Resources]ページにそのホストに対して表示されているバックアップ、クローン、クローニング ジョブ、リソース グループ、およびリソースが削除され、次にホスト上のプラグイン パッケージがアンインストールされます。' 
---
= ホストを削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Serverでホストを削除すると、まずSnapCenterの[Resources]ページにそのホストに対して表示されているバックアップ、クローン、クローニング ジョブ、リソース グループ、およびリソースが削除され、次にホスト上のプラグイン パッケージがアンインストールされます。

.タスク概要
* ホストを削除すると、そのホストに関連付けられているバックアップ、クローン、およびリソース グループも削除されます。
* リソース グループを削除すると、関連付けられているスケジュールもすべて削除されます。
* リソース グループを他のホストと共有しているホストを削除すると、リソース グループも削除されます。
* 廃止されたプラグイン ホストまたは到達できないプラグイン ホストを削除するには、_Remove-SmHost_ コマンドレットを使用する必要があります。
+
コマンドレットで使用できるパラメータとその説明に関する情報は、_Get-Help command_name_ を実行すると取得できます。あるいは、 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenterソフトウェア コマンドレット リファレンス ガイド"^]

* ホストの削除にかかる時間は、バックアップの数と保持設定によって異なります。これは、各コントローラからSnapshotが削除され、メタデータが消去されるためです。


.手順
. 左側のナビゲーション ペインで、[*ホスト*] をクリックします。
. *ホスト*ページで、*管理対象ホスト*をクリックします。
. 削除するホストを選択し、[*削除*] をクリックします。
. Oracle RAC クラスタの場合、クラスタ内のすべてのホストからSnapCenter softwareを削除するには、[クラスタのすべてのホストを含​​める] を選択します。
+
クラスタのノードを1つずつ削除することもできます。

. [OK]をクリックします。
+

NOTE: クラスタでホスト プラグインをアンインストールして再インストールしても、クラスタ リソースは自動的に検出されません。クラスター ホスト名を選択し、[*リソースの更新*] をクリックして、クラスター リソースを自動的に検出します。


