---
permalink: protect-mysql/snapcenter-plug-in-for-mysql-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: SnapCenter Plug-in for MySQL は、MySQL データベースのアプリケーション対応のデータ保護管理を可能にするNetApp SnapCenter softwareのホスト側コンポーネントです。Plug-in for MySQL Databaseは、SnapCenter環境でのMySQLデータベースのバックアップ、リストア、およびクローニングを自動化します。 
---
= SnapCenter Plug-in for MySQLの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter Plug-in for MySQL Databaseは、MySQLデータベースに対してアプリケーション対応のデータ保護管理を可能にする、NetApp SnapCenterソフトウェアのホスト側コンポーネントです。Plug-in for MySQL Databaseは、SnapCenter環境でのMySQLデータベースのバックアップ、リストア、およびクローニングを自動化します。

SnapCenterは、単一インスタンスのMySQLセットアップをサポートしています。Plug-in for MySQL Databaseは、WindowsとLinuxのどちらの環境でも使用できます。Windows環境では、MySQLは手動リソースとしてサポートされます。

Plug-in for MySQL Databaseがインストールされている場合は、SnapCenterとNetApp SnapMirrorテクノロジを使用して、バックアップ セットのミラー コピーを別のボリュームに作成できます。また、このプラグインをNetApp SnapVaultテクノロジとともに使用して、標準への準拠を目的としたディスクツーディスク バックアップ レプリケーションを実行することもできます。

SnapCenter Plug-in for MySQLは、ONTAPおよびAzure NetApp Filesストレージ レイアウトでNFSとSANをサポートします。

VMDK、vVol、RDM 仮想ストレージ レイアウトがサポートされています。

シンボリック リンクはサポートされません。
